package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * Analysisprop generated by hbm2java
 */
public class Analysisprop implements java.io.Serializable {

	private int analysispropId;
	private Analysis analysis;
	private Cvterm cvterm;
	private String value;
	private int rank;

	public Analysisprop() {
	}

	public Analysisprop(int analysispropId, Analysis analysis, Cvterm cvterm,
			int rank) {
		this.analysispropId = analysispropId;
		this.analysis = analysis;
		this.cvterm = cvterm;
		this.rank = rank;
	}

	public Analysisprop(int analysispropId, Analysis analysis, Cvterm cvterm,
			String value, int rank) {
		this.analysispropId = analysispropId;
		this.analysis = analysis;
		this.cvterm = cvterm;
		this.value = value;
		this.rank = rank;
	}

	public int getAnalysispropId() {
		return this.analysispropId;
	}

	public void setAnalysispropId(int analysispropId) {
		this.analysispropId = analysispropId;
	}

	public Analysis getAnalysis() {
		return this.analysis;
	}

	public void setAnalysis(Analysis analysis) {
		this.analysis = analysis;
	}

	public Cvterm getCvterm() {
		return this.cvterm;
	}

	public void setCvterm(Cvterm cvterm) {
		this.cvterm = cvterm;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public int getRank() {
		return this.rank;
	}

	public void setRank(int rank) {
		this.rank = rank;
	}

}
