package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * Analysisfeatureprop generated by hbm2java
 */
public class Analysisfeatureprop implements java.io.Serializable {

	private int analysisfeaturepropId;
	private Analysisfeature analysisfeature;
	private Cvterm cvterm;
	private String value;
	private int rank;

	public Analysisfeatureprop() {
	}

	public Analysisfeatureprop(int analysisfeaturepropId,
			Analysisfeature analysisfeature, Cvterm cvterm, int rank) {
		this.analysisfeaturepropId = analysisfeaturepropId;
		this.analysisfeature = analysisfeature;
		this.cvterm = cvterm;
		this.rank = rank;
	}

	public Analysisfeatureprop(int analysisfeaturepropId,
			Analysisfeature analysisfeature, Cvterm cvterm, String value,
			int rank) {
		this.analysisfeaturepropId = analysisfeaturepropId;
		this.analysisfeature = analysisfeature;
		this.cvterm = cvterm;
		this.value = value;
		this.rank = rank;
	}

	public int getAnalysisfeaturepropId() {
		return this.analysisfeaturepropId;
	}

	public void setAnalysisfeaturepropId(int analysisfeaturepropId) {
		this.analysisfeaturepropId = analysisfeaturepropId;
	}

	public Analysisfeature getAnalysisfeature() {
		return this.analysisfeature;
	}

	public void setAnalysisfeature(Analysisfeature analysisfeature) {
		this.analysisfeature = analysisfeature;
	}

	public Cvterm getCvterm() {
		return this.cvterm;
	}

	public void setCvterm(Cvterm cvterm) {
		this.cvterm = cvterm;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public int getRank() {
		return this.rank;
	}

	public void setRank(int rank) {
		this.rank = rank;
	}

}
