package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * AssayProject generated by hbm2java
 */
public class AssayProject implements java.io.Serializable {

	private int assayProjectId;
	private Project project;
	private Assay assay;

	public AssayProject() {
	}

	public AssayProject(int assayProjectId, Project project, Assay assay) {
		this.assayProjectId = assayProjectId;
		this.project = project;
		this.assay = assay;
	}

	public int getAssayProjectId() {
		return this.assayProjectId;
	}

	public void setAssayProjectId(int assayProjectId) {
		this.assayProjectId = assayProjectId;
	}

	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public Assay getAssay() {
		return this.assay;
	}

	public void setAssay(Assay assay) {
		this.assay = assay;
	}

}
