package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * Assayprop generated by hbm2java
 */
public class Assayprop implements java.io.Serializable {

	private int assaypropId;
	private Assay assay;
	private Cvterm cvterm;
	private String value;
	private int rank;

	public Assayprop() {
	}

	public Assayprop(int assaypropId, Assay assay, Cvterm cvterm, int rank) {
		this.assaypropId = assaypropId;
		this.assay = assay;
		this.cvterm = cvterm;
		this.rank = rank;
	}

	public Assayprop(int assaypropId, Assay assay, Cvterm cvterm, String value,
			int rank) {
		this.assaypropId = assaypropId;
		this.assay = assay;
		this.cvterm = cvterm;
		this.value = value;
		this.rank = rank;
	}

	public int getAssaypropId() {
		return this.assaypropId;
	}

	public void setAssaypropId(int assaypropId) {
		this.assaypropId = assaypropId;
	}

	public Assay getAssay() {
		return this.assay;
	}

	public void setAssay(Assay assay) {
		this.assay = assay;
	}

	public Cvterm getCvterm() {
		return this.cvterm;
	}

	public void setCvterm(Cvterm cvterm) {
		this.cvterm = cvterm;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public int getRank() {
		return this.rank;
	}

	public void setRank(int rank) {
		this.rank = rank;
	}

}
