package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * BiomaterialRelationship generated by hbm2java
 */
public class BiomaterialRelationship implements java.io.Serializable {

	private int biomaterialRelationshipId;
	private Biomaterial biomaterialByObjectId;
	private Biomaterial biomaterialBySubjectId;
	private Cvterm cvterm;

	public BiomaterialRelationship() {
	}

	public BiomaterialRelationship(int biomaterialRelationshipId,
			Biomaterial biomaterialByObjectId,
			Biomaterial biomaterialBySubjectId, Cvterm cvterm) {
		this.biomaterialRelationshipId = biomaterialRelationshipId;
		this.biomaterialByObjectId = biomaterialByObjectId;
		this.biomaterialBySubjectId = biomaterialBySubjectId;
		this.cvterm = cvterm;
	}

	public int getBiomaterialRelationshipId() {
		return this.biomaterialRelationshipId;
	}

	public void setBiomaterialRelationshipId(int biomaterialRelationshipId) {
		this.biomaterialRelationshipId = biomaterialRelationshipId;
	}

	public Biomaterial getBiomaterialByObjectId() {
		return this.biomaterialByObjectId;
	}

	public void setBiomaterialByObjectId(Biomaterial biomaterialByObjectId) {
		this.biomaterialByObjectId = biomaterialByObjectId;
	}

	public Biomaterial getBiomaterialBySubjectId() {
		return this.biomaterialBySubjectId;
	}

	public void setBiomaterialBySubjectId(Biomaterial biomaterialBySubjectId) {
		this.biomaterialBySubjectId = biomaterialBySubjectId;
	}

	public Cvterm getCvterm() {
		return this.cvterm;
	}

	public void setCvterm(Cvterm cvterm) {
		this.cvterm = cvterm;
	}

}
