package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Biomaterial generated by hbm2java
 */
public class Biomaterial implements java.io.Serializable {

	private int biomaterialId;
	private Dbxref dbxref;
	private Contact contact;
	private Organism organism;
	private String name;
	private String description;
	private Set biomaterialRelationshipsForObjectId = new HashSet(0);
	private Set biomaterialprops = new HashSet(0);
	private Set assayBiomaterials = new HashSet(0);
	private Set biomaterialDbxrefs = new HashSet(0);
	private Set biomaterialRelationshipsForSubjectId = new HashSet(0);
	private Set treatments = new HashSet(0);
	private Set biomaterialTreatments = new HashSet(0);

	public Biomaterial() {
	}

	public Biomaterial(int biomaterialId) {
		this.biomaterialId = biomaterialId;
	}

	public Biomaterial(int biomaterialId, Dbxref dbxref, Contact contact,
			Organism organism, String name, String description,
			Set biomaterialRelationshipsForObjectId, Set biomaterialprops,
			Set assayBiomaterials, Set biomaterialDbxrefs,
			Set biomaterialRelationshipsForSubjectId, Set treatments,
			Set biomaterialTreatments) {
		this.biomaterialId = biomaterialId;
		this.dbxref = dbxref;
		this.contact = contact;
		this.organism = organism;
		this.name = name;
		this.description = description;
		this.biomaterialRelationshipsForObjectId = biomaterialRelationshipsForObjectId;
		this.biomaterialprops = biomaterialprops;
		this.assayBiomaterials = assayBiomaterials;
		this.biomaterialDbxrefs = biomaterialDbxrefs;
		this.biomaterialRelationshipsForSubjectId = biomaterialRelationshipsForSubjectId;
		this.treatments = treatments;
		this.biomaterialTreatments = biomaterialTreatments;
	}

	public int getBiomaterialId() {
		return this.biomaterialId;
	}

	public void setBiomaterialId(int biomaterialId) {
		this.biomaterialId = biomaterialId;
	}

	public Dbxref getDbxref() {
		return this.dbxref;
	}

	public void setDbxref(Dbxref dbxref) {
		this.dbxref = dbxref;
	}

	public Contact getContact() {
		return this.contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

	public Organism getOrganism() {
		return this.organism;
	}

	public void setOrganism(Organism organism) {
		this.organism = organism;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getBiomaterialRelationshipsForObjectId() {
		return this.biomaterialRelationshipsForObjectId;
	}

	public void setBiomaterialRelationshipsForObjectId(
			Set biomaterialRelationshipsForObjectId) {
		this.biomaterialRelationshipsForObjectId = biomaterialRelationshipsForObjectId;
	}

	public Set getBiomaterialprops() {
		return this.biomaterialprops;
	}

	public void setBiomaterialprops(Set biomaterialprops) {
		this.biomaterialprops = biomaterialprops;
	}

	public Set getAssayBiomaterials() {
		return this.assayBiomaterials;
	}

	public void setAssayBiomaterials(Set assayBiomaterials) {
		this.assayBiomaterials = assayBiomaterials;
	}

	public Set getBiomaterialDbxrefs() {
		return this.biomaterialDbxrefs;
	}

	public void setBiomaterialDbxrefs(Set biomaterialDbxrefs) {
		this.biomaterialDbxrefs = biomaterialDbxrefs;
	}

	public Set getBiomaterialRelationshipsForSubjectId() {
		return this.biomaterialRelationshipsForSubjectId;
	}

	public void setBiomaterialRelationshipsForSubjectId(
			Set biomaterialRelationshipsForSubjectId) {
		this.biomaterialRelationshipsForSubjectId = biomaterialRelationshipsForSubjectId;
	}

	public Set getTreatments() {
		return this.treatments;
	}

	public void setTreatments(Set treatments) {
		this.treatments = treatments;
	}

	public Set getBiomaterialTreatments() {
		return this.biomaterialTreatments;
	}

	public void setBiomaterialTreatments(Set biomaterialTreatments) {
		this.biomaterialTreatments = biomaterialTreatments;
	}

}
