package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * CellLineRelationship generated by hbm2java
 */
public class CellLineRelationship implements java.io.Serializable {

	private int cellLineRelationshipId;
	private CellLine cellLineByObjectId;
	private CellLine cellLineBySubjectId;
	private Cvterm cvterm;

	public CellLineRelationship() {
	}

	public CellLineRelationship(int cellLineRelationshipId,
			CellLine cellLineByObjectId, CellLine cellLineBySubjectId,
			Cvterm cvterm) {
		this.cellLineRelationshipId = cellLineRelationshipId;
		this.cellLineByObjectId = cellLineByObjectId;
		this.cellLineBySubjectId = cellLineBySubjectId;
		this.cvterm = cvterm;
	}

	public int getCellLineRelationshipId() {
		return this.cellLineRelationshipId;
	}

	public void setCellLineRelationshipId(int cellLineRelationshipId) {
		this.cellLineRelationshipId = cellLineRelationshipId;
	}

	public CellLine getCellLineByObjectId() {
		return this.cellLineByObjectId;
	}

	public void setCellLineByObjectId(CellLine cellLineByObjectId) {
		this.cellLineByObjectId = cellLineByObjectId;
	}

	public CellLine getCellLineBySubjectId() {
		return this.cellLineBySubjectId;
	}

	public void setCellLineBySubjectId(CellLine cellLineBySubjectId) {
		this.cellLineBySubjectId = cellLineBySubjectId;
	}

	public Cvterm getCvterm() {
		return this.cvterm;
	}

	public void setCvterm(Cvterm cvterm) {
		this.cvterm = cvterm;
	}

}
