package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * Chadoprop generated by hbm2java
 */
public class Chadoprop implements java.io.Serializable {

	private int chadopropId;
	private Cvterm cvterm;
	private String value;
	private int rank;

	public Chadoprop() {
	}

	public Chadoprop(int chadopropId, Cvterm cvterm, int rank) {
		this.chadopropId = chadopropId;
		this.cvterm = cvterm;
		this.rank = rank;
	}

	public Chadoprop(int chadopropId, Cvterm cvterm, String value, int rank) {
		this.chadopropId = chadopropId;
		this.cvterm = cvterm;
		this.value = value;
		this.rank = rank;
	}

	public int getChadopropId() {
		return this.chadopropId;
	}

	public void setChadopropId(int chadopropId) {
		this.chadopropId = chadopropId;
	}

	public Cvterm getCvterm() {
		return this.cvterm;
	}

	public void setCvterm(Cvterm cvterm) {
		this.cvterm = cvterm;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public int getRank() {
		return this.rank;
	}

	public void setRank(int rank) {
		this.rank = rank;
	}

}
