package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Channel generated by hbm2java
 */
public class Channel implements java.io.Serializable {

	private int channelId;
	private String name;
	private String definition;
	private Set acquisitions = new HashSet(0);
	private Set assayBiomaterials = new HashSet(0);

	public Channel() {
	}

	public Channel(int channelId, String name, String definition) {
		this.channelId = channelId;
		this.name = name;
		this.definition = definition;
	}

	public Channel(int channelId, String name, String definition,
			Set acquisitions, Set assayBiomaterials) {
		this.channelId = channelId;
		this.name = name;
		this.definition = definition;
		this.acquisitions = acquisitions;
		this.assayBiomaterials = assayBiomaterials;
	}

	public int getChannelId() {
		return this.channelId;
	}

	public void setChannelId(int channelId) {
		this.channelId = channelId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDefinition() {
		return this.definition;
	}

	public void setDefinition(String definition) {
		this.definition = definition;
	}

	public Set getAcquisitions() {
		return this.acquisitions;
	}

	public void setAcquisitions(Set acquisitions) {
		this.acquisitions = acquisitions;
	}

	public Set getAssayBiomaterials() {
		return this.assayBiomaterials;
	}

	public void setAssayBiomaterials(Set assayBiomaterials) {
		this.assayBiomaterials = assayBiomaterials;
	}

}
