package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * CommonAncestorCvterm generated by hbm2java
 */
public class CommonAncestorCvterm implements java.io.Serializable {

	private CommonAncestorCvtermId id;

	public CommonAncestorCvterm() {
	}

	public CommonAncestorCvterm(CommonAncestorCvtermId id) {
		this.id = id;
	}

	public CommonAncestorCvtermId getId() {
		return this.id;
	}

	public void setId(CommonAncestorCvtermId id) {
		this.id = id;
	}

}
