package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * CvCvtermCountId generated by hbm2java
 */
public class CvCvtermCountId implements java.io.Serializable {

	private String name;
	private Long numTermsExclObs;

	public CvCvtermCountId() {
	}

	public CvCvtermCountId(String name, Long numTermsExclObs) {
		this.name = name;
		this.numTermsExclObs = numTermsExclObs;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Long getNumTermsExclObs() {
		return this.numTermsExclObs;
	}

	public void setNumTermsExclObs(Long numTermsExclObs) {
		this.numTermsExclObs = numTermsExclObs;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CvCvtermCountId))
			return false;
		CvCvtermCountId castOther = (CvCvtermCountId) other;

		return ((this.getName() == castOther.getName()) || (this.getName() != null
				&& castOther.getName() != null && this.getName().equals(
				castOther.getName())))
				&& ((this.getNumTermsExclObs() == castOther
						.getNumTermsExclObs()) || (this.getNumTermsExclObs() != null
						&& castOther.getNumTermsExclObs() != null && this
						.getNumTermsExclObs().equals(
								castOther.getNumTermsExclObs())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37
				* result
				+ (getNumTermsExclObs() == null ? 0 : this.getNumTermsExclObs()
						.hashCode());
		return result;
	}

}
