package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * CvLinkCount generated by hbm2java
 */
public class CvLinkCount implements java.io.Serializable {

	private CvLinkCountId id;

	public CvLinkCount() {
	}

	public CvLinkCount(CvLinkCountId id) {
		this.id = id;
	}

	public CvLinkCountId getId() {
		return this.id;
	}

	public void setId(CvLinkCountId id) {
		this.id = id;
	}

}
