package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * Cvprop generated by hbm2java
 */
public class Cvprop implements java.io.Serializable {

	private int cvpropId;
	private Cv cv;
	private Cvterm cvterm;
	private String value;
	private int rank;

	public Cvprop() {
	}

	public Cvprop(int cvpropId, Cv cv, Cvterm cvterm, int rank) {
		this.cvpropId = cvpropId;
		this.cv = cv;
		this.cvterm = cvterm;
		this.rank = rank;
	}

	public Cvprop(int cvpropId, Cv cv, Cvterm cvterm, String value, int rank) {
		this.cvpropId = cvpropId;
		this.cv = cv;
		this.cvterm = cvterm;
		this.value = value;
		this.rank = rank;
	}

	public int getCvpropId() {
		return this.cvpropId;
	}

	public void setCvpropId(int cvpropId) {
		this.cvpropId = cvpropId;
	}

	public Cv getCv() {
		return this.cv;
	}

	public void setCv(Cv cv) {
		this.cv = cv;
	}

	public Cvterm getCvterm() {
		return this.cvterm;
	}

	public void setCvterm(Cvterm cvterm) {
		this.cvterm = cvterm;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public int getRank() {
		return this.rank;
	}

	public void setRank(int rank) {
		this.rank = rank;
	}

}
