package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Cvterm generated by hbm2java
 */
public class Cvterm implements java.io.Serializable {

	private int cvtermId;
	private Dbxref dbxref;
	private Cv cv;
	private String name;
	private String definition;
	private int isObsolete;
	private int isRelationshiptype;
	private Set phenotypesForAttrId = new HashSet(0);
	private Set expressionCvtermsForCvtermId = new HashSet(0);
	private Set expressionprops = new HashSet(0);
	private Set chadoprops = new HashSet(0);
	private Set featureCvterms = new HashSet(0);
	private Set expressionCvtermsForCvtermTypeId = new HashSet(0);
	private Set arraydesignsForSubstratetypeId = new HashSet(0);
	private Set phendescs = new HashSet(0);
	private Set ndProtocolprops = new HashSet(0);
	private Set pubprops = new HashSet(0);
	private Set featuremaps = new HashSet(0);
	private Set featureRelationships = new HashSet(0);
	private Set cellLineRelationships = new HashSet(0);
	private Set featurePubprops = new HashSet(0);
	private Set biomaterialRelationships = new HashSet(0);
	private Set phenotypeCvterms = new HashSet(0);
	private Set elementRelationships = new HashSet(0);
	private Set cvtermRelationshipsForSubjectId = new HashSet(0);
	private Set ndReagentprops = new HashSet(0);
	private Set phylonodes = new HashSet(0);
	private Set ndReagents = new HashSet(0);
	private Set phenotypesForCvalueId = new HashSet(0);
	private Set genotypes = new HashSet(0);
	private Set genotypeprops = new HashSet(0);
	private Set environmentCvterms = new HashSet(0);
	private Set ndReagentRelationships = new HashSet(0);
	private Set phylonodeRelationships = new HashSet(0);
	private Set cvtermpathsForTypeId = new HashSet(0);
	private Set contacts = new HashSet(0);
	private Set features = new HashSet(0);
	private Set cellLineCvterms = new HashSet(0);
	private Set organismprops = new HashSet(0);
	private Set stockRelationships = new HashSet(0);
	private Set phenotypeComparisonCvterms = new HashSet(0);
	private Set treatments = new HashSet(0);
	private Set elementresultRelationships = new HashSet(0);
	private Set ndExperimentStocks = new HashSet(0);
	private Set biomaterialprops = new HashSet(0);
	private Set biomaterialTreatments = new HashSet(0);
	private Set featureRelationshipprops = new HashSet(0);
	private Set cvtermpropsForTypeId = new HashSet(0);
	private Set phenotypesForObservableId = new HashSet(0);
	private Set cellLineprops = new HashSet(0);
	private Set expressionCvtermprops = new HashSet(0);
	private Set featureGenotypes = new HashSet(0);
	private Set contactRelationships = new HashSet(0);
	private Set phylonodeprops = new HashSet(0);
	private Set cvtermRelationshipsForObjectId = new HashSet(0);
	private Set ndProtocols = new HashSet(0);
	private Set libraryprops = new HashSet(0);
	private Set quantificationRelationships = new HashSet(0);
	private Set cvtermsynonymsForCvtermId = new HashSet(0);
	private Set cvtermDbxrefs = new HashSet(0);
	private Set featureCvtermprops = new HashSet(0);
	private Set analysisfeatureprops = new HashSet(0);
	private Set ndExperimentStockprops = new HashSet(0);
	private Set quantificationprops = new HashSet(0);
	private Set stockprops = new HashSet(0);
	private Set pubRelationships = new HashSet(0);
	private Set stocks = new HashSet(0);
	private Set cvtermpathsForSubjectId = new HashSet(0);
	private Set ndExperimentprops = new HashSet(0);
	private Set dbxrefprops = new HashSet(0);
	private Set studyprops = new HashSet(0);
	private Set protocolparamsForUnittypeId = new HashSet(0);
	private Set featureExpressionprops = new HashSet(0);
	private Set phenstatements = new HashSet(0);
	private Set arraydesignprops = new HashSet(0);
	private Set cellLineCvtermprops = new HashSet(0);
	private Set libraries = new HashSet(0);
	private Set stockCvtermprops = new HashSet(0);
	private Set protocols = new HashSet(0);
	private Set featureprops = new HashSet(0);
	private Set controls = new HashSet(0);
	private Set acquisitionRelationships = new HashSet(0);
	private Set libraryCvterms = new HashSet(0);
	private Set phylotrees = new HashSet(0);
	private Set projectprops = new HashSet(0);
	private Set cvtermRelationshipsForTypeId = new HashSet(0);
	private Set cvtermpathsForObjectId = new HashSet(0);
	private Set arraydesignsForPlatformtypeId = new HashSet(0);
	private Set ndGeolocationprops = new HashSet(0);
	private Set stockCvterms = new HashSet(0);
	private Set synonyms = new HashSet(0);
	private Set stockcollections = new HashSet(0);
	private Set cvtermsynonymsForTypeId = new HashSet(0);
	private Set stockDbxrefprops = new HashSet(0);
	private Set studypropFeatures = new HashSet(0);
	private Set ndProtocolReagents = new HashSet(0);
	private Set phenotypesForAssayId = new HashSet(0);
	private Set projectRelationships = new HashSet(0);
	private Set studydesignprops = new HashSet(0);
	private Set elements = new HashSet(0);
	private Set stockcollectionprops = new HashSet(0);
	private Set cvtermpropsForCvtermId = new HashSet(0);
	private Set cvprops = new HashSet(0);
	private Set protocolparamsForDatatypeId = new HashSet(0);
	private Set acquisitionprops = new HashSet(0);
	private Set assayprops = new HashSet(0);
	private Set pubs = new HashSet(0);
	private Set stockRelationshipCvterms = new HashSet(0);
	private Set studyfactors = new HashSet(0);
	private Set analysisprops = new HashSet(0);
	private Set ndExperiments = new HashSet(0);

	public Cvterm() {
	}

	public Cvterm(int cvtermId, Dbxref dbxref, Cv cv, String name,
			int isObsolete, int isRelationshiptype) {
		this.cvtermId = cvtermId;
		this.dbxref = dbxref;
		this.cv = cv;
		this.name = name;
		this.isObsolete = isObsolete;
		this.isRelationshiptype = isRelationshiptype;
	}

	public Cvterm(int cvtermId, Dbxref dbxref, Cv cv, String name,
			String definition, int isObsolete, int isRelationshiptype,
			Set phenotypesForAttrId, Set expressionCvtermsForCvtermId,
			Set expressionprops, Set chadoprops, Set featureCvterms,
			Set expressionCvtermsForCvtermTypeId,
			Set arraydesignsForSubstratetypeId, Set phendescs,
			Set ndProtocolprops, Set pubprops, Set featuremaps,
			Set featureRelationships, Set cellLineRelationships,
			Set featurePubprops, Set biomaterialRelationships,
			Set phenotypeCvterms, Set elementRelationships,
			Set cvtermRelationshipsForSubjectId, Set ndReagentprops,
			Set phylonodes, Set ndReagents, Set phenotypesForCvalueId,
			Set genotypes, Set genotypeprops, Set environmentCvterms,
			Set ndReagentRelationships, Set phylonodeRelationships,
			Set cvtermpathsForTypeId, Set contacts, Set features,
			Set cellLineCvterms, Set organismprops, Set stockRelationships,
			Set phenotypeComparisonCvterms, Set treatments,
			Set elementresultRelationships, Set ndExperimentStocks,
			Set biomaterialprops, Set biomaterialTreatments,
			Set featureRelationshipprops, Set cvtermpropsForTypeId,
			Set phenotypesForObservableId, Set cellLineprops,
			Set expressionCvtermprops, Set featureGenotypes,
			Set contactRelationships, Set phylonodeprops,
			Set cvtermRelationshipsForObjectId, Set ndProtocols,
			Set libraryprops, Set quantificationRelationships,
			Set cvtermsynonymsForCvtermId, Set cvtermDbxrefs,
			Set featureCvtermprops, Set analysisfeatureprops,
			Set ndExperimentStockprops, Set quantificationprops,
			Set stockprops, Set pubRelationships, Set stocks,
			Set cvtermpathsForSubjectId, Set ndExperimentprops,
			Set dbxrefprops, Set studyprops, Set protocolparamsForUnittypeId,
			Set featureExpressionprops, Set phenstatements,
			Set arraydesignprops, Set cellLineCvtermprops, Set libraries,
			Set stockCvtermprops, Set protocols, Set featureprops,
			Set controls, Set acquisitionRelationships, Set libraryCvterms,
			Set phylotrees, Set projectprops, Set cvtermRelationshipsForTypeId,
			Set cvtermpathsForObjectId, Set arraydesignsForPlatformtypeId,
			Set ndGeolocationprops, Set stockCvterms, Set synonyms,
			Set stockcollections, Set cvtermsynonymsForTypeId,
			Set stockDbxrefprops, Set studypropFeatures,
			Set ndProtocolReagents, Set phenotypesForAssayId,
			Set projectRelationships, Set studydesignprops, Set elements,
			Set stockcollectionprops, Set cvtermpropsForCvtermId, Set cvprops,
			Set protocolparamsForDatatypeId, Set acquisitionprops,
			Set assayprops, Set pubs, Set stockRelationshipCvterms,
			Set studyfactors, Set analysisprops, Set ndExperiments) {
		this.cvtermId = cvtermId;
		this.dbxref = dbxref;
		this.cv = cv;
		this.name = name;
		this.definition = definition;
		this.isObsolete = isObsolete;
		this.isRelationshiptype = isRelationshiptype;
		this.phenotypesForAttrId = phenotypesForAttrId;
		this.expressionCvtermsForCvtermId = expressionCvtermsForCvtermId;
		this.expressionprops = expressionprops;
		this.chadoprops = chadoprops;
		this.featureCvterms = featureCvterms;
		this.expressionCvtermsForCvtermTypeId = expressionCvtermsForCvtermTypeId;
		this.arraydesignsForSubstratetypeId = arraydesignsForSubstratetypeId;
		this.phendescs = phendescs;
		this.ndProtocolprops = ndProtocolprops;
		this.pubprops = pubprops;
		this.featuremaps = featuremaps;
		this.featureRelationships = featureRelationships;
		this.cellLineRelationships = cellLineRelationships;
		this.featurePubprops = featurePubprops;
		this.biomaterialRelationships = biomaterialRelationships;
		this.phenotypeCvterms = phenotypeCvterms;
		this.elementRelationships = elementRelationships;
		this.cvtermRelationshipsForSubjectId = cvtermRelationshipsForSubjectId;
		this.ndReagentprops = ndReagentprops;
		this.phylonodes = phylonodes;
		this.ndReagents = ndReagents;
		this.phenotypesForCvalueId = phenotypesForCvalueId;
		this.genotypes = genotypes;
		this.genotypeprops = genotypeprops;
		this.environmentCvterms = environmentCvterms;
		this.ndReagentRelationships = ndReagentRelationships;
		this.phylonodeRelationships = phylonodeRelationships;
		this.cvtermpathsForTypeId = cvtermpathsForTypeId;
		this.contacts = contacts;
		this.features = features;
		this.cellLineCvterms = cellLineCvterms;
		this.organismprops = organismprops;
		this.stockRelationships = stockRelationships;
		this.phenotypeComparisonCvterms = phenotypeComparisonCvterms;
		this.treatments = treatments;
		this.elementresultRelationships = elementresultRelationships;
		this.ndExperimentStocks = ndExperimentStocks;
		this.biomaterialprops = biomaterialprops;
		this.biomaterialTreatments = biomaterialTreatments;
		this.featureRelationshipprops = featureRelationshipprops;
		this.cvtermpropsForTypeId = cvtermpropsForTypeId;
		this.phenotypesForObservableId = phenotypesForObservableId;
		this.cellLineprops = cellLineprops;
		this.expressionCvtermprops = expressionCvtermprops;
		this.featureGenotypes = featureGenotypes;
		this.contactRelationships = contactRelationships;
		this.phylonodeprops = phylonodeprops;
		this.cvtermRelationshipsForObjectId = cvtermRelationshipsForObjectId;
		this.ndProtocols = ndProtocols;
		this.libraryprops = libraryprops;
		this.quantificationRelationships = quantificationRelationships;
		this.cvtermsynonymsForCvtermId = cvtermsynonymsForCvtermId;
		this.cvtermDbxrefs = cvtermDbxrefs;
		this.featureCvtermprops = featureCvtermprops;
		this.analysisfeatureprops = analysisfeatureprops;
		this.ndExperimentStockprops = ndExperimentStockprops;
		this.quantificationprops = quantificationprops;
		this.stockprops = stockprops;
		this.pubRelationships = pubRelationships;
		this.stocks = stocks;
		this.cvtermpathsForSubjectId = cvtermpathsForSubjectId;
		this.ndExperimentprops = ndExperimentprops;
		this.dbxrefprops = dbxrefprops;
		this.studyprops = studyprops;
		this.protocolparamsForUnittypeId = protocolparamsForUnittypeId;
		this.featureExpressionprops = featureExpressionprops;
		this.phenstatements = phenstatements;
		this.arraydesignprops = arraydesignprops;
		this.cellLineCvtermprops = cellLineCvtermprops;
		this.libraries = libraries;
		this.stockCvtermprops = stockCvtermprops;
		this.protocols = protocols;
		this.featureprops = featureprops;
		this.controls = controls;
		this.acquisitionRelationships = acquisitionRelationships;
		this.libraryCvterms = libraryCvterms;
		this.phylotrees = phylotrees;
		this.projectprops = projectprops;
		this.cvtermRelationshipsForTypeId = cvtermRelationshipsForTypeId;
		this.cvtermpathsForObjectId = cvtermpathsForObjectId;
		this.arraydesignsForPlatformtypeId = arraydesignsForPlatformtypeId;
		this.ndGeolocationprops = ndGeolocationprops;
		this.stockCvterms = stockCvterms;
		this.synonyms = synonyms;
		this.stockcollections = stockcollections;
		this.cvtermsynonymsForTypeId = cvtermsynonymsForTypeId;
		this.stockDbxrefprops = stockDbxrefprops;
		this.studypropFeatures = studypropFeatures;
		this.ndProtocolReagents = ndProtocolReagents;
		this.phenotypesForAssayId = phenotypesForAssayId;
		this.projectRelationships = projectRelationships;
		this.studydesignprops = studydesignprops;
		this.elements = elements;
		this.stockcollectionprops = stockcollectionprops;
		this.cvtermpropsForCvtermId = cvtermpropsForCvtermId;
		this.cvprops = cvprops;
		this.protocolparamsForDatatypeId = protocolparamsForDatatypeId;
		this.acquisitionprops = acquisitionprops;
		this.assayprops = assayprops;
		this.pubs = pubs;
		this.stockRelationshipCvterms = stockRelationshipCvterms;
		this.studyfactors = studyfactors;
		this.analysisprops = analysisprops;
		this.ndExperiments = ndExperiments;
	}

	public int getCvtermId() {
		return this.cvtermId;
	}

	public void setCvtermId(int cvtermId) {
		this.cvtermId = cvtermId;
	}

	public Dbxref getDbxref() {
		return this.dbxref;
	}

	public void setDbxref(Dbxref dbxref) {
		this.dbxref = dbxref;
	}

	public Cv getCv() {
		return this.cv;
	}

	public void setCv(Cv cv) {
		this.cv = cv;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDefinition() {
		return this.definition;
	}

	public void setDefinition(String definition) {
		this.definition = definition;
	}

	public int getIsObsolete() {
		return this.isObsolete;
	}

	public void setIsObsolete(int isObsolete) {
		this.isObsolete = isObsolete;
	}

	public int getIsRelationshiptype() {
		return this.isRelationshiptype;
	}

	public void setIsRelationshiptype(int isRelationshiptype) {
		this.isRelationshiptype = isRelationshiptype;
	}

	public Set getPhenotypesForAttrId() {
		return this.phenotypesForAttrId;
	}

	public void setPhenotypesForAttrId(Set phenotypesForAttrId) {
		this.phenotypesForAttrId = phenotypesForAttrId;
	}

	public Set getExpressionCvtermsForCvtermId() {
		return this.expressionCvtermsForCvtermId;
	}

	public void setExpressionCvtermsForCvtermId(Set expressionCvtermsForCvtermId) {
		this.expressionCvtermsForCvtermId = expressionCvtermsForCvtermId;
	}

	public Set getExpressionprops() {
		return this.expressionprops;
	}

	public void setExpressionprops(Set expressionprops) {
		this.expressionprops = expressionprops;
	}

	public Set getChadoprops() {
		return this.chadoprops;
	}

	public void setChadoprops(Set chadoprops) {
		this.chadoprops = chadoprops;
	}

	public Set getFeatureCvterms() {
		return this.featureCvterms;
	}

	public void setFeatureCvterms(Set featureCvterms) {
		this.featureCvterms = featureCvterms;
	}

	public Set getExpressionCvtermsForCvtermTypeId() {
		return this.expressionCvtermsForCvtermTypeId;
	}

	public void setExpressionCvtermsForCvtermTypeId(
			Set expressionCvtermsForCvtermTypeId) {
		this.expressionCvtermsForCvtermTypeId = expressionCvtermsForCvtermTypeId;
	}

	public Set getArraydesignsForSubstratetypeId() {
		return this.arraydesignsForSubstratetypeId;
	}

	public void setArraydesignsForSubstratetypeId(
			Set arraydesignsForSubstratetypeId) {
		this.arraydesignsForSubstratetypeId = arraydesignsForSubstratetypeId;
	}

	public Set getPhendescs() {
		return this.phendescs;
	}

	public void setPhendescs(Set phendescs) {
		this.phendescs = phendescs;
	}

	public Set getNdProtocolprops() {
		return this.ndProtocolprops;
	}

	public void setNdProtocolprops(Set ndProtocolprops) {
		this.ndProtocolprops = ndProtocolprops;
	}

	public Set getPubprops() {
		return this.pubprops;
	}

	public void setPubprops(Set pubprops) {
		this.pubprops = pubprops;
	}

	public Set getFeaturemaps() {
		return this.featuremaps;
	}

	public void setFeaturemaps(Set featuremaps) {
		this.featuremaps = featuremaps;
	}

	public Set getFeatureRelationships() {
		return this.featureRelationships;
	}

	public void setFeatureRelationships(Set featureRelationships) {
		this.featureRelationships = featureRelationships;
	}

	public Set getCellLineRelationships() {
		return this.cellLineRelationships;
	}

	public void setCellLineRelationships(Set cellLineRelationships) {
		this.cellLineRelationships = cellLineRelationships;
	}

	public Set getFeaturePubprops() {
		return this.featurePubprops;
	}

	public void setFeaturePubprops(Set featurePubprops) {
		this.featurePubprops = featurePubprops;
	}

	public Set getBiomaterialRelationships() {
		return this.biomaterialRelationships;
	}

	public void setBiomaterialRelationships(Set biomaterialRelationships) {
		this.biomaterialRelationships = biomaterialRelationships;
	}

	public Set getPhenotypeCvterms() {
		return this.phenotypeCvterms;
	}

	public void setPhenotypeCvterms(Set phenotypeCvterms) {
		this.phenotypeCvterms = phenotypeCvterms;
	}

	public Set getElementRelationships() {
		return this.elementRelationships;
	}

	public void setElementRelationships(Set elementRelationships) {
		this.elementRelationships = elementRelationships;
	}

	public Set getCvtermRelationshipsForSubjectId() {
		return this.cvtermRelationshipsForSubjectId;
	}

	public void setCvtermRelationshipsForSubjectId(
			Set cvtermRelationshipsForSubjectId) {
		this.cvtermRelationshipsForSubjectId = cvtermRelationshipsForSubjectId;
	}

	public Set getNdReagentprops() {
		return this.ndReagentprops;
	}

	public void setNdReagentprops(Set ndReagentprops) {
		this.ndReagentprops = ndReagentprops;
	}

	public Set getPhylonodes() {
		return this.phylonodes;
	}

	public void setPhylonodes(Set phylonodes) {
		this.phylonodes = phylonodes;
	}

	public Set getNdReagents() {
		return this.ndReagents;
	}

	public void setNdReagents(Set ndReagents) {
		this.ndReagents = ndReagents;
	}

	public Set getPhenotypesForCvalueId() {
		return this.phenotypesForCvalueId;
	}

	public void setPhenotypesForCvalueId(Set phenotypesForCvalueId) {
		this.phenotypesForCvalueId = phenotypesForCvalueId;
	}

	public Set getGenotypes() {
		return this.genotypes;
	}

	public void setGenotypes(Set genotypes) {
		this.genotypes = genotypes;
	}

	public Set getGenotypeprops() {
		return this.genotypeprops;
	}

	public void setGenotypeprops(Set genotypeprops) {
		this.genotypeprops = genotypeprops;
	}

	public Set getEnvironmentCvterms() {
		return this.environmentCvterms;
	}

	public void setEnvironmentCvterms(Set environmentCvterms) {
		this.environmentCvterms = environmentCvterms;
	}

	public Set getNdReagentRelationships() {
		return this.ndReagentRelationships;
	}

	public void setNdReagentRelationships(Set ndReagentRelationships) {
		this.ndReagentRelationships = ndReagentRelationships;
	}

	public Set getPhylonodeRelationships() {
		return this.phylonodeRelationships;
	}

	public void setPhylonodeRelationships(Set phylonodeRelationships) {
		this.phylonodeRelationships = phylonodeRelationships;
	}

	public Set getCvtermpathsForTypeId() {
		return this.cvtermpathsForTypeId;
	}

	public void setCvtermpathsForTypeId(Set cvtermpathsForTypeId) {
		this.cvtermpathsForTypeId = cvtermpathsForTypeId;
	}

	public Set getContacts() {
		return this.contacts;
	}

	public void setContacts(Set contacts) {
		this.contacts = contacts;
	}

	public Set getFeatures() {
		return this.features;
	}

	public void setFeatures(Set features) {
		this.features = features;
	}

	public Set getCellLineCvterms() {
		return this.cellLineCvterms;
	}

	public void setCellLineCvterms(Set cellLineCvterms) {
		this.cellLineCvterms = cellLineCvterms;
	}

	public Set getOrganismprops() {
		return this.organismprops;
	}

	public void setOrganismprops(Set organismprops) {
		this.organismprops = organismprops;
	}

	public Set getStockRelationships() {
		return this.stockRelationships;
	}

	public void setStockRelationships(Set stockRelationships) {
		this.stockRelationships = stockRelationships;
	}

	public Set getPhenotypeComparisonCvterms() {
		return this.phenotypeComparisonCvterms;
	}

	public void setPhenotypeComparisonCvterms(Set phenotypeComparisonCvterms) {
		this.phenotypeComparisonCvterms = phenotypeComparisonCvterms;
	}

	public Set getTreatments() {
		return this.treatments;
	}

	public void setTreatments(Set treatments) {
		this.treatments = treatments;
	}

	public Set getElementresultRelationships() {
		return this.elementresultRelationships;
	}

	public void setElementresultRelationships(Set elementresultRelationships) {
		this.elementresultRelationships = elementresultRelationships;
	}

	public Set getNdExperimentStocks() {
		return this.ndExperimentStocks;
	}

	public void setNdExperimentStocks(Set ndExperimentStocks) {
		this.ndExperimentStocks = ndExperimentStocks;
	}

	public Set getBiomaterialprops() {
		return this.biomaterialprops;
	}

	public void setBiomaterialprops(Set biomaterialprops) {
		this.biomaterialprops = biomaterialprops;
	}

	public Set getBiomaterialTreatments() {
		return this.biomaterialTreatments;
	}

	public void setBiomaterialTreatments(Set biomaterialTreatments) {
		this.biomaterialTreatments = biomaterialTreatments;
	}

	public Set getFeatureRelationshipprops() {
		return this.featureRelationshipprops;
	}

	public void setFeatureRelationshipprops(Set featureRelationshipprops) {
		this.featureRelationshipprops = featureRelationshipprops;
	}

	public Set getCvtermpropsForTypeId() {
		return this.cvtermpropsForTypeId;
	}

	public void setCvtermpropsForTypeId(Set cvtermpropsForTypeId) {
		this.cvtermpropsForTypeId = cvtermpropsForTypeId;
	}

	public Set getPhenotypesForObservableId() {
		return this.phenotypesForObservableId;
	}

	public void setPhenotypesForObservableId(Set phenotypesForObservableId) {
		this.phenotypesForObservableId = phenotypesForObservableId;
	}

	public Set getCellLineprops() {
		return this.cellLineprops;
	}

	public void setCellLineprops(Set cellLineprops) {
		this.cellLineprops = cellLineprops;
	}

	public Set getExpressionCvtermprops() {
		return this.expressionCvtermprops;
	}

	public void setExpressionCvtermprops(Set expressionCvtermprops) {
		this.expressionCvtermprops = expressionCvtermprops;
	}

	public Set getFeatureGenotypes() {
		return this.featureGenotypes;
	}

	public void setFeatureGenotypes(Set featureGenotypes) {
		this.featureGenotypes = featureGenotypes;
	}

	public Set getContactRelationships() {
		return this.contactRelationships;
	}

	public void setContactRelationships(Set contactRelationships) {
		this.contactRelationships = contactRelationships;
	}

	public Set getPhylonodeprops() {
		return this.phylonodeprops;
	}

	public void setPhylonodeprops(Set phylonodeprops) {
		this.phylonodeprops = phylonodeprops;
	}

	public Set getCvtermRelationshipsForObjectId() {
		return this.cvtermRelationshipsForObjectId;
	}

	public void setCvtermRelationshipsForObjectId(
			Set cvtermRelationshipsForObjectId) {
		this.cvtermRelationshipsForObjectId = cvtermRelationshipsForObjectId;
	}

	public Set getNdProtocols() {
		return this.ndProtocols;
	}

	public void setNdProtocols(Set ndProtocols) {
		this.ndProtocols = ndProtocols;
	}

	public Set getLibraryprops() {
		return this.libraryprops;
	}

	public void setLibraryprops(Set libraryprops) {
		this.libraryprops = libraryprops;
	}

	public Set getQuantificationRelationships() {
		return this.quantificationRelationships;
	}

	public void setQuantificationRelationships(Set quantificationRelationships) {
		this.quantificationRelationships = quantificationRelationships;
	}

	public Set getCvtermsynonymsForCvtermId() {
		return this.cvtermsynonymsForCvtermId;
	}

	public void setCvtermsynonymsForCvtermId(Set cvtermsynonymsForCvtermId) {
		this.cvtermsynonymsForCvtermId = cvtermsynonymsForCvtermId;
	}

	public Set getCvtermDbxrefs() {
		return this.cvtermDbxrefs;
	}

	public void setCvtermDbxrefs(Set cvtermDbxrefs) {
		this.cvtermDbxrefs = cvtermDbxrefs;
	}

	public Set getFeatureCvtermprops() {
		return this.featureCvtermprops;
	}

	public void setFeatureCvtermprops(Set featureCvtermprops) {
		this.featureCvtermprops = featureCvtermprops;
	}

	public Set getAnalysisfeatureprops() {
		return this.analysisfeatureprops;
	}

	public void setAnalysisfeatureprops(Set analysisfeatureprops) {
		this.analysisfeatureprops = analysisfeatureprops;
	}

	public Set getNdExperimentStockprops() {
		return this.ndExperimentStockprops;
	}

	public void setNdExperimentStockprops(Set ndExperimentStockprops) {
		this.ndExperimentStockprops = ndExperimentStockprops;
	}

	public Set getQuantificationprops() {
		return this.quantificationprops;
	}

	public void setQuantificationprops(Set quantificationprops) {
		this.quantificationprops = quantificationprops;
	}

	public Set getStockprops() {
		return this.stockprops;
	}

	public void setStockprops(Set stockprops) {
		this.stockprops = stockprops;
	}

	public Set getPubRelationships() {
		return this.pubRelationships;
	}

	public void setPubRelationships(Set pubRelationships) {
		this.pubRelationships = pubRelationships;
	}

	public Set getStocks() {
		return this.stocks;
	}

	public void setStocks(Set stocks) {
		this.stocks = stocks;
	}

	public Set getCvtermpathsForSubjectId() {
		return this.cvtermpathsForSubjectId;
	}

	public void setCvtermpathsForSubjectId(Set cvtermpathsForSubjectId) {
		this.cvtermpathsForSubjectId = cvtermpathsForSubjectId;
	}

	public Set getNdExperimentprops() {
		return this.ndExperimentprops;
	}

	public void setNdExperimentprops(Set ndExperimentprops) {
		this.ndExperimentprops = ndExperimentprops;
	}

	public Set getDbxrefprops() {
		return this.dbxrefprops;
	}

	public void setDbxrefprops(Set dbxrefprops) {
		this.dbxrefprops = dbxrefprops;
	}

	public Set getStudyprops() {
		return this.studyprops;
	}

	public void setStudyprops(Set studyprops) {
		this.studyprops = studyprops;
	}

	public Set getProtocolparamsForUnittypeId() {
		return this.protocolparamsForUnittypeId;
	}

	public void setProtocolparamsForUnittypeId(Set protocolparamsForUnittypeId) {
		this.protocolparamsForUnittypeId = protocolparamsForUnittypeId;
	}

	public Set getFeatureExpressionprops() {
		return this.featureExpressionprops;
	}

	public void setFeatureExpressionprops(Set featureExpressionprops) {
		this.featureExpressionprops = featureExpressionprops;
	}

	public Set getPhenstatements() {
		return this.phenstatements;
	}

	public void setPhenstatements(Set phenstatements) {
		this.phenstatements = phenstatements;
	}

	public Set getArraydesignprops() {
		return this.arraydesignprops;
	}

	public void setArraydesignprops(Set arraydesignprops) {
		this.arraydesignprops = arraydesignprops;
	}

	public Set getCellLineCvtermprops() {
		return this.cellLineCvtermprops;
	}

	public void setCellLineCvtermprops(Set cellLineCvtermprops) {
		this.cellLineCvtermprops = cellLineCvtermprops;
	}

	public Set getLibraries() {
		return this.libraries;
	}

	public void setLibraries(Set libraries) {
		this.libraries = libraries;
	}

	public Set getStockCvtermprops() {
		return this.stockCvtermprops;
	}

	public void setStockCvtermprops(Set stockCvtermprops) {
		this.stockCvtermprops = stockCvtermprops;
	}

	public Set getProtocols() {
		return this.protocols;
	}

	public void setProtocols(Set protocols) {
		this.protocols = protocols;
	}

	public Set getFeatureprops() {
		return this.featureprops;
	}

	public void setFeatureprops(Set featureprops) {
		this.featureprops = featureprops;
	}

	public Set getControls() {
		return this.controls;
	}

	public void setControls(Set controls) {
		this.controls = controls;
	}

	public Set getAcquisitionRelationships() {
		return this.acquisitionRelationships;
	}

	public void setAcquisitionRelationships(Set acquisitionRelationships) {
		this.acquisitionRelationships = acquisitionRelationships;
	}

	public Set getLibraryCvterms() {
		return this.libraryCvterms;
	}

	public void setLibraryCvterms(Set libraryCvterms) {
		this.libraryCvterms = libraryCvterms;
	}

	public Set getPhylotrees() {
		return this.phylotrees;
	}

	public void setPhylotrees(Set phylotrees) {
		this.phylotrees = phylotrees;
	}

	public Set getProjectprops() {
		return this.projectprops;
	}

	public void setProjectprops(Set projectprops) {
		this.projectprops = projectprops;
	}

	public Set getCvtermRelationshipsForTypeId() {
		return this.cvtermRelationshipsForTypeId;
	}

	public void setCvtermRelationshipsForTypeId(Set cvtermRelationshipsForTypeId) {
		this.cvtermRelationshipsForTypeId = cvtermRelationshipsForTypeId;
	}

	public Set getCvtermpathsForObjectId() {
		return this.cvtermpathsForObjectId;
	}

	public void setCvtermpathsForObjectId(Set cvtermpathsForObjectId) {
		this.cvtermpathsForObjectId = cvtermpathsForObjectId;
	}

	public Set getArraydesignsForPlatformtypeId() {
		return this.arraydesignsForPlatformtypeId;
	}

	public void setArraydesignsForPlatformtypeId(
			Set arraydesignsForPlatformtypeId) {
		this.arraydesignsForPlatformtypeId = arraydesignsForPlatformtypeId;
	}

	public Set getNdGeolocationprops() {
		return this.ndGeolocationprops;
	}

	public void setNdGeolocationprops(Set ndGeolocationprops) {
		this.ndGeolocationprops = ndGeolocationprops;
	}

	public Set getStockCvterms() {
		return this.stockCvterms;
	}

	public void setStockCvterms(Set stockCvterms) {
		this.stockCvterms = stockCvterms;
	}

	public Set getSynonyms() {
		return this.synonyms;
	}

	public void setSynonyms(Set synonyms) {
		this.synonyms = synonyms;
	}

	public Set getStockcollections() {
		return this.stockcollections;
	}

	public void setStockcollections(Set stockcollections) {
		this.stockcollections = stockcollections;
	}

	public Set getCvtermsynonymsForTypeId() {
		return this.cvtermsynonymsForTypeId;
	}

	public void setCvtermsynonymsForTypeId(Set cvtermsynonymsForTypeId) {
		this.cvtermsynonymsForTypeId = cvtermsynonymsForTypeId;
	}

	public Set getStockDbxrefprops() {
		return this.stockDbxrefprops;
	}

	public void setStockDbxrefprops(Set stockDbxrefprops) {
		this.stockDbxrefprops = stockDbxrefprops;
	}

	public Set getStudypropFeatures() {
		return this.studypropFeatures;
	}

	public void setStudypropFeatures(Set studypropFeatures) {
		this.studypropFeatures = studypropFeatures;
	}

	public Set getNdProtocolReagents() {
		return this.ndProtocolReagents;
	}

	public void setNdProtocolReagents(Set ndProtocolReagents) {
		this.ndProtocolReagents = ndProtocolReagents;
	}

	public Set getPhenotypesForAssayId() {
		return this.phenotypesForAssayId;
	}

	public void setPhenotypesForAssayId(Set phenotypesForAssayId) {
		this.phenotypesForAssayId = phenotypesForAssayId;
	}

	public Set getProjectRelationships() {
		return this.projectRelationships;
	}

	public void setProjectRelationships(Set projectRelationships) {
		this.projectRelationships = projectRelationships;
	}

	public Set getStudydesignprops() {
		return this.studydesignprops;
	}

	public void setStudydesignprops(Set studydesignprops) {
		this.studydesignprops = studydesignprops;
	}

	public Set getElements() {
		return this.elements;
	}

	public void setElements(Set elements) {
		this.elements = elements;
	}

	public Set getStockcollectionprops() {
		return this.stockcollectionprops;
	}

	public void setStockcollectionprops(Set stockcollectionprops) {
		this.stockcollectionprops = stockcollectionprops;
	}

	public Set getCvtermpropsForCvtermId() {
		return this.cvtermpropsForCvtermId;
	}

	public void setCvtermpropsForCvtermId(Set cvtermpropsForCvtermId) {
		this.cvtermpropsForCvtermId = cvtermpropsForCvtermId;
	}

	public Set getCvprops() {
		return this.cvprops;
	}

	public void setCvprops(Set cvprops) {
		this.cvprops = cvprops;
	}

	public Set getProtocolparamsForDatatypeId() {
		return this.protocolparamsForDatatypeId;
	}

	public void setProtocolparamsForDatatypeId(Set protocolparamsForDatatypeId) {
		this.protocolparamsForDatatypeId = protocolparamsForDatatypeId;
	}

	public Set getAcquisitionprops() {
		return this.acquisitionprops;
	}

	public void setAcquisitionprops(Set acquisitionprops) {
		this.acquisitionprops = acquisitionprops;
	}

	public Set getAssayprops() {
		return this.assayprops;
	}

	public void setAssayprops(Set assayprops) {
		this.assayprops = assayprops;
	}

	public Set getPubs() {
		return this.pubs;
	}

	public void setPubs(Set pubs) {
		this.pubs = pubs;
	}

	public Set getStockRelationshipCvterms() {
		return this.stockRelationshipCvterms;
	}

	public void setStockRelationshipCvterms(Set stockRelationshipCvterms) {
		this.stockRelationshipCvterms = stockRelationshipCvterms;
	}

	public Set getStudyfactors() {
		return this.studyfactors;
	}

	public void setStudyfactors(Set studyfactors) {
		this.studyfactors = studyfactors;
	}

	public Set getAnalysisprops() {
		return this.analysisprops;
	}

	public void setAnalysisprops(Set analysisprops) {
		this.analysisprops = analysisprops;
	}

	public Set getNdExperiments() {
		return this.ndExperiments;
	}

	public void setNdExperiments(Set ndExperiments) {
		this.ndExperiments = ndExperiments;
	}

}
