package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * Cvtermsynonym generated by hbm2java
 */
public class Cvtermsynonym implements java.io.Serializable {

	private int cvtermsynonymId;
	private Cvterm cvtermByCvtermId;
	private Cvterm cvtermByTypeId;
	private String synonym;

	public Cvtermsynonym() {
	}

	public Cvtermsynonym(int cvtermsynonymId, Cvterm cvtermByCvtermId,
			String synonym) {
		this.cvtermsynonymId = cvtermsynonymId;
		this.cvtermByCvtermId = cvtermByCvtermId;
		this.synonym = synonym;
	}

	public Cvtermsynonym(int cvtermsynonymId, Cvterm cvtermByCvtermId,
			Cvterm cvtermByTypeId, String synonym) {
		this.cvtermsynonymId = cvtermsynonymId;
		this.cvtermByCvtermId = cvtermByCvtermId;
		this.cvtermByTypeId = cvtermByTypeId;
		this.synonym = synonym;
	}

	public int getCvtermsynonymId() {
		return this.cvtermsynonymId;
	}

	public void setCvtermsynonymId(int cvtermsynonymId) {
		this.cvtermsynonymId = cvtermsynonymId;
	}

	public Cvterm getCvtermByCvtermId() {
		return this.cvtermByCvtermId;
	}

	public void setCvtermByCvtermId(Cvterm cvtermByCvtermId) {
		this.cvtermByCvtermId = cvtermByCvtermId;
	}

	public Cvterm getCvtermByTypeId() {
		return this.cvtermByTypeId;
	}

	public void setCvtermByTypeId(Cvterm cvtermByTypeId) {
		this.cvtermByTypeId = cvtermByTypeId;
	}

	public String getSynonym() {
		return this.synonym;
	}

	public void setSynonym(String synonym) {
		this.synonym = synonym;
	}

}
