package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * ExpressionCvtermprop generated by hbm2java
 */
public class ExpressionCvtermprop implements java.io.Serializable {

	private int expressionCvtermpropId;
	private ExpressionCvterm expressionCvterm;
	private Cvterm cvterm;
	private String value;
	private int rank;

	public ExpressionCvtermprop() {
	}

	public ExpressionCvtermprop(int expressionCvtermpropId,
			ExpressionCvterm expressionCvterm, Cvterm cvterm, int rank) {
		this.expressionCvtermpropId = expressionCvtermpropId;
		this.expressionCvterm = expressionCvterm;
		this.cvterm = cvterm;
		this.rank = rank;
	}

	public ExpressionCvtermprop(int expressionCvtermpropId,
			ExpressionCvterm expressionCvterm, Cvterm cvterm, String value,
			int rank) {
		this.expressionCvtermpropId = expressionCvtermpropId;
		this.expressionCvterm = expressionCvterm;
		this.cvterm = cvterm;
		this.value = value;
		this.rank = rank;
	}

	public int getExpressionCvtermpropId() {
		return this.expressionCvtermpropId;
	}

	public void setExpressionCvtermpropId(int expressionCvtermpropId) {
		this.expressionCvtermpropId = expressionCvtermpropId;
	}

	public ExpressionCvterm getExpressionCvterm() {
		return this.expressionCvterm;
	}

	public void setExpressionCvterm(ExpressionCvterm expressionCvterm) {
		this.expressionCvterm = expressionCvterm;
	}

	public Cvterm getCvterm() {
		return this.cvterm;
	}

	public void setCvterm(Cvterm cvterm) {
		this.cvterm = cvterm;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public int getRank() {
		return this.rank;
	}

	public void setRank(int rank) {
		this.rank = rank;
	}

}
