package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * ExpressionPub generated by hbm2java
 */
public class ExpressionPub implements java.io.Serializable {

	private int expressionPubId;
	private Pub pub;
	private Expression expression;

	public ExpressionPub() {
	}

	public ExpressionPub(int expressionPubId, Pub pub, Expression expression) {
		this.expressionPubId = expressionPubId;
		this.pub = pub;
		this.expression = expression;
	}

	public int getExpressionPubId() {
		return this.expressionPubId;
	}

	public void setExpressionPubId(int expressionPubId) {
		this.expressionPubId = expressionPubId;
	}

	public Pub getPub() {
		return this.pub;
	}

	public void setPub(Pub pub) {
		this.pub = pub;
	}

	public Expression getExpression() {
		return this.expression;
	}

	public void setExpression(Expression expression) {
		this.expression = expression;
	}

}
