package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * FeaturePub generated by hbm2java
 */
public class FeaturePub implements java.io.Serializable {

	private int featurePubId;
	private Pub pub;
	private Feature feature;
	private Set featurePubprops = new HashSet(0);

	public FeaturePub() {
	}

	public FeaturePub(int featurePubId, Pub pub, Feature feature) {
		this.featurePubId = featurePubId;
		this.pub = pub;
		this.feature = feature;
	}

	public FeaturePub(int featurePubId, Pub pub, Feature feature,
			Set featurePubprops) {
		this.featurePubId = featurePubId;
		this.pub = pub;
		this.feature = feature;
		this.featurePubprops = featurePubprops;
	}

	public int getFeaturePubId() {
		return this.featurePubId;
	}

	public void setFeaturePubId(int featurePubId) {
		this.featurePubId = featurePubId;
	}

	public Pub getPub() {
		return this.pub;
	}

	public void setPub(Pub pub) {
		this.pub = pub;
	}

	public Feature getFeature() {
		return this.feature;
	}

	public void setFeature(Feature feature) {
		this.feature = feature;
	}

	public Set getFeaturePubprops() {
		return this.featurePubprops;
	}

	public void setFeaturePubprops(Set featurePubprops) {
		this.featurePubprops = featurePubprops;
	}

}
