package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * FeatureMeetsOnSameStrand generated by hbm2java
 */
public class FeatureMeetsOnSameStrand implements java.io.Serializable {

	private FeatureMeetsOnSameStrandId id;

	public FeatureMeetsOnSameStrand() {
	}

	public FeatureMeetsOnSameStrand(FeatureMeetsOnSameStrandId id) {
		this.id = id;
	}

	public FeatureMeetsOnSameStrandId getId() {
		return this.id;
	}

	public void setId(FeatureMeetsOnSameStrandId id) {
		this.id = id;
	}

}
