package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * FeatureCvtermPub generated by hbm2java
 */
public class FeatureCvtermPub implements java.io.Serializable {

	private int featureCvtermPubId;
	private Pub pub;
	private FeatureCvterm featureCvterm;

	public FeatureCvtermPub() {
	}

	public FeatureCvtermPub(int featureCvtermPubId, Pub pub,
			FeatureCvterm featureCvterm) {
		this.featureCvtermPubId = featureCvtermPubId;
		this.pub = pub;
		this.featureCvterm = featureCvterm;
	}

	public int getFeatureCvtermPubId() {
		return this.featureCvtermPubId;
	}

	public void setFeatureCvtermPubId(int featureCvtermPubId) {
		this.featureCvtermPubId = featureCvtermPubId;
	}

	public Pub getPub() {
		return this.pub;
	}

	public void setPub(Pub pub) {
		this.pub = pub;
	}

	public FeatureCvterm getFeatureCvterm() {
		return this.featureCvterm;
	}

	public void setFeatureCvterm(FeatureCvterm featureCvterm) {
		this.featureCvterm = featureCvterm;
	}

}
