package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * FeaturePhenotype generated by hbm2java
 */
public class FeaturePhenotype implements java.io.Serializable {

	private int featurePhenotypeId;
	private Feature feature;
	private Phenotype phenotype;

	public FeaturePhenotype() {
	}

	public FeaturePhenotype(int featurePhenotypeId, Feature feature,
			Phenotype phenotype) {
		this.featurePhenotypeId = featurePhenotypeId;
		this.feature = feature;
		this.phenotype = phenotype;
	}

	public int getFeaturePhenotypeId() {
		return this.featurePhenotypeId;
	}

	public void setFeaturePhenotypeId(int featurePhenotypeId) {
		this.featurePhenotypeId = featurePhenotypeId;
	}

	public Feature getFeature() {
		return this.feature;
	}

	public void setFeature(Feature feature) {
		this.feature = feature;
	}

	public Phenotype getPhenotype() {
		return this.phenotype;
	}

	public void setPhenotype(Phenotype phenotype) {
		this.phenotype = phenotype;
	}

}
