package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * FeatureCvterm generated by hbm2java
 */
public class FeatureCvterm implements java.io.Serializable {

	private int featureCvtermId;
	private Pub pub;
	private Feature feature;
	private Cvterm cvterm;
	private boolean isNot;
	private int rank;
	private Set featureCvtermprops = new HashSet(0);
	private Set featureCvtermDbxrefs = new HashSet(0);
	private Set featureCvtermPubs = new HashSet(0);

	public FeatureCvterm() {
	}

	public FeatureCvterm(int featureCvtermId, Pub pub, Feature feature,
			Cvterm cvterm, boolean isNot, int rank) {
		this.featureCvtermId = featureCvtermId;
		this.pub = pub;
		this.feature = feature;
		this.cvterm = cvterm;
		this.isNot = isNot;
		this.rank = rank;
	}

	public FeatureCvterm(int featureCvtermId, Pub pub, Feature feature,
			Cvterm cvterm, boolean isNot, int rank, Set featureCvtermprops,
			Set featureCvtermDbxrefs, Set featureCvtermPubs) {
		this.featureCvtermId = featureCvtermId;
		this.pub = pub;
		this.feature = feature;
		this.cvterm = cvterm;
		this.isNot = isNot;
		this.rank = rank;
		this.featureCvtermprops = featureCvtermprops;
		this.featureCvtermDbxrefs = featureCvtermDbxrefs;
		this.featureCvtermPubs = featureCvtermPubs;
	}

	public int getFeatureCvtermId() {
		return this.featureCvtermId;
	}

	public void setFeatureCvtermId(int featureCvtermId) {
		this.featureCvtermId = featureCvtermId;
	}

	public Pub getPub() {
		return this.pub;
	}

	public void setPub(Pub pub) {
		this.pub = pub;
	}

	public Feature getFeature() {
		return this.feature;
	}

	public void setFeature(Feature feature) {
		this.feature = feature;
	}

	public Cvterm getCvterm() {
		return this.cvterm;
	}

	public void setCvterm(Cvterm cvterm) {
		this.cvterm = cvterm;
	}

	public boolean isIsNot() {
		return this.isNot;
	}

	public void setIsNot(boolean isNot) {
		this.isNot = isNot;
	}

	public int getRank() {
		return this.rank;
	}

	public void setRank(int rank) {
		this.rank = rank;
	}

	public Set getFeatureCvtermprops() {
		return this.featureCvtermprops;
	}

	public void setFeatureCvtermprops(Set featureCvtermprops) {
		this.featureCvtermprops = featureCvtermprops;
	}

	public Set getFeatureCvtermDbxrefs() {
		return this.featureCvtermDbxrefs;
	}

	public void setFeatureCvtermDbxrefs(Set featureCvtermDbxrefs) {
		this.featureCvtermDbxrefs = featureCvtermDbxrefs;
	}

	public Set getFeatureCvtermPubs() {
		return this.featureCvtermPubs;
	}

	public void setFeatureCvtermPubs(Set featureCvtermPubs) {
		this.featureCvtermPubs = featureCvtermPubs;
	}

}
