package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * Featuregroup generated by hbm2java
 */
public class Featuregroup implements java.io.Serializable {

	private int featuregroupId;
	private Feature featureByObjectId;
	private Feature featureBySrcfeatureId;
	private Feature featureBySubjectId;
	private Feature featureByGroupId;
	private Integer fmin;
	private Integer fmax;
	private Integer strand;
	private int isRoot;

	public Featuregroup() {
	}

	public Featuregroup(int featuregroupId, Feature featureByObjectId,
			Feature featureBySubjectId, Feature featureByGroupId, int isRoot) {
		this.featuregroupId = featuregroupId;
		this.featureByObjectId = featureByObjectId;
		this.featureBySubjectId = featureBySubjectId;
		this.featureByGroupId = featureByGroupId;
		this.isRoot = isRoot;
	}

	public Featuregroup(int featuregroupId, Feature featureByObjectId,
			Feature featureBySrcfeatureId, Feature featureBySubjectId,
			Feature featureByGroupId, Integer fmin, Integer fmax,
			Integer strand, int isRoot) {
		this.featuregroupId = featuregroupId;
		this.featureByObjectId = featureByObjectId;
		this.featureBySrcfeatureId = featureBySrcfeatureId;
		this.featureBySubjectId = featureBySubjectId;
		this.featureByGroupId = featureByGroupId;
		this.fmin = fmin;
		this.fmax = fmax;
		this.strand = strand;
		this.isRoot = isRoot;
	}

	public int getFeaturegroupId() {
		return this.featuregroupId;
	}

	public void setFeaturegroupId(int featuregroupId) {
		this.featuregroupId = featuregroupId;
	}

	public Feature getFeatureByObjectId() {
		return this.featureByObjectId;
	}

	public void setFeatureByObjectId(Feature featureByObjectId) {
		this.featureByObjectId = featureByObjectId;
	}

	public Feature getFeatureBySrcfeatureId() {
		return this.featureBySrcfeatureId;
	}

	public void setFeatureBySrcfeatureId(Feature featureBySrcfeatureId) {
		this.featureBySrcfeatureId = featureBySrcfeatureId;
	}

	public Feature getFeatureBySubjectId() {
		return this.featureBySubjectId;
	}

	public void setFeatureBySubjectId(Feature featureBySubjectId) {
		this.featureBySubjectId = featureBySubjectId;
	}

	public Feature getFeatureByGroupId() {
		return this.featureByGroupId;
	}

	public void setFeatureByGroupId(Feature featureByGroupId) {
		this.featureByGroupId = featureByGroupId;
	}

	public Integer getFmin() {
		return this.fmin;
	}

	public void setFmin(Integer fmin) {
		this.fmin = fmin;
	}

	public Integer getFmax() {
		return this.fmax;
	}

	public void setFmax(Integer fmax) {
		this.fmax = fmax;
	}

	public Integer getStrand() {
		return this.strand;
	}

	public void setStrand(Integer strand) {
		this.strand = strand;
	}

	public int getIsRoot() {
		return this.isRoot;
	}

	public void setIsRoot(int isRoot) {
		this.isRoot = isRoot;
	}

}
