package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * FeaturepropPub generated by hbm2java
 */
public class FeaturepropPub implements java.io.Serializable {

	private int featurepropPubId;
	private Pub pub;
	private Featureprop featureprop;

	public FeaturepropPub() {
	}

	public FeaturepropPub(int featurepropPubId, Pub pub, Featureprop featureprop) {
		this.featurepropPubId = featurepropPubId;
		this.pub = pub;
		this.featureprop = featureprop;
	}

	public int getFeaturepropPubId() {
		return this.featurepropPubId;
	}

	public void setFeaturepropPubId(int featurepropPubId) {
		this.featurepropPubId = featurepropPubId;
	}

	public Pub getPub() {
		return this.pub;
	}

	public void setPub(Pub pub) {
		this.pub = pub;
	}

	public Featureprop getFeatureprop() {
		return this.featureprop;
	}

	public void setFeatureprop(Featureprop featureprop) {
		this.featureprop = featureprop;
	}

}
