package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * FeatureDbxref generated by hbm2java
 */
public class FeatureDbxref implements java.io.Serializable {

	private int featureDbxrefId;
	private Feature feature;
	private Dbxref dbxref;
	private boolean isCurrent;

	public FeatureDbxref() {
	}

	public FeatureDbxref(int featureDbxrefId, Feature feature, Dbxref dbxref,
			boolean isCurrent) {
		this.featureDbxrefId = featureDbxrefId;
		this.feature = feature;
		this.dbxref = dbxref;
		this.isCurrent = isCurrent;
	}

	public int getFeatureDbxrefId() {
		return this.featureDbxrefId;
	}

	public void setFeatureDbxrefId(int featureDbxrefId) {
		this.featureDbxrefId = featureDbxrefId;
	}

	public Feature getFeature() {
		return this.feature;
	}

	public void setFeature(Feature feature) {
		this.feature = feature;
	}

	public Dbxref getDbxref() {
		return this.dbxref;
	}

	public void setDbxref(Dbxref dbxref) {
		this.dbxref = dbxref;
	}

	public boolean isIsCurrent() {
		return this.isCurrent;
	}

	public void setIsCurrent(boolean isCurrent) {
		this.isCurrent = isCurrent;
	}

}
