package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * FLocId generated by hbm2java
 */
public class FLocId implements java.io.Serializable {

	private Integer featureId;
	private String name;
	private Integer dbxrefId;
	private Integer nbeg;
	private Integer nend;
	private Short strand;

	public FLocId() {
	}

	public FLocId(Integer featureId, String name, Integer dbxrefId,
			Integer nbeg, Integer nend, Short strand) {
		this.featureId = featureId;
		this.name = name;
		this.dbxrefId = dbxrefId;
		this.nbeg = nbeg;
		this.nend = nend;
		this.strand = strand;
	}

	public Integer getFeatureId() {
		return this.featureId;
	}

	public void setFeatureId(Integer featureId) {
		this.featureId = featureId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getDbxrefId() {
		return this.dbxrefId;
	}

	public void setDbxrefId(Integer dbxrefId) {
		this.dbxrefId = dbxrefId;
	}

	public Integer getNbeg() {
		return this.nbeg;
	}

	public void setNbeg(Integer nbeg) {
		this.nbeg = nbeg;
	}

	public Integer getNend() {
		return this.nend;
	}

	public void setNend(Integer nend) {
		this.nend = nend;
	}

	public Short getStrand() {
		return this.strand;
	}

	public void setStrand(Short strand) {
		this.strand = strand;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FLocId))
			return false;
		FLocId castOther = (FLocId) other;

		return ((this.getFeatureId() == castOther.getFeatureId()) || (this
				.getFeatureId() != null && castOther.getFeatureId() != null && this
				.getFeatureId().equals(castOther.getFeatureId())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())))
				&& ((this.getDbxrefId() == castOther.getDbxrefId()) || (this
						.getDbxrefId() != null
						&& castOther.getDbxrefId() != null && this
						.getDbxrefId().equals(castOther.getDbxrefId())))
				&& ((this.getNbeg() == castOther.getNbeg()) || (this.getNbeg() != null
						&& castOther.getNbeg() != null && this.getNbeg()
						.equals(castOther.getNbeg())))
				&& ((this.getNend() == castOther.getNend()) || (this.getNend() != null
						&& castOther.getNend() != null && this.getNend()
						.equals(castOther.getNend())))
				&& ((this.getStrand() == castOther.getStrand()) || (this
						.getStrand() != null && castOther.getStrand() != null && this
						.getStrand().equals(castOther.getStrand())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getFeatureId() == null ? 0 : this.getFeatureId().hashCode());
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result
				+ (getDbxrefId() == null ? 0 : this.getDbxrefId().hashCode());
		result = 37 * result
				+ (getNbeg() == null ? 0 : this.getNbeg().hashCode());
		result = 37 * result
				+ (getNend() == null ? 0 : this.getNend().hashCode());
		result = 37 * result
				+ (getStrand() == null ? 0 : this.getStrand().hashCode());
		return result;
	}

}
