package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * GencodeCodonAaId generated by hbm2java
 */
public class GencodeCodonAaId implements java.io.Serializable {

	private int gencodeId;
	private String codon;
	private char aa;

	public GencodeCodonAaId() {
	}

	public GencodeCodonAaId(int gencodeId, String codon, char aa) {
		this.gencodeId = gencodeId;
		this.codon = codon;
		this.aa = aa;
	}

	public int getGencodeId() {
		return this.gencodeId;
	}

	public void setGencodeId(int gencodeId) {
		this.gencodeId = gencodeId;
	}

	public String getCodon() {
		return this.codon;
	}

	public void setCodon(String codon) {
		this.codon = codon;
	}

	public char getAa() {
		return this.aa;
	}

	public void setAa(char aa) {
		this.aa = aa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GencodeCodonAaId))
			return false;
		GencodeCodonAaId castOther = (GencodeCodonAaId) other;

		return (this.getGencodeId() == castOther.getGencodeId())
				&& ((this.getCodon() == castOther.getCodon()) || (this
						.getCodon() != null && castOther.getCodon() != null && this
						.getCodon().equals(castOther.getCodon())))
				&& (this.getAa() == castOther.getAa());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getGencodeId();
		result = 37 * result
				+ (getCodon() == null ? 0 : this.getCodon().hashCode());
		result = 37 * result + this.getAa();
		return result;
	}

}
