package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * Gff3atts generated by hbm2java
 */
public class Gff3atts implements java.io.Serializable {

	private Gff3attsId id;

	public Gff3atts() {
	}

	public Gff3atts(Gff3attsId id) {
		this.id = id;
	}

	public Gff3attsId getId() {
		return this.id;
	}

	public void setId(Gff3attsId id) {
		this.id = id;
	}

}
