package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * Gff3viewId generated by hbm2java
 */
public class Gff3viewId implements java.io.Serializable {

	private Integer featureId;
	private String ref;
	private String source;
	private String type;
	private Integer fstart;
	private Integer fend;
	private String score;
	private String strand;
	private String phase;
	private Integer seqlen;
	private String name;
	private Integer organismId;

	public Gff3viewId() {
	}

	public Gff3viewId(Integer featureId, String ref, String source,
			String type, Integer fstart, Integer fend, String score,
			String strand, String phase, Integer seqlen, String name,
			Integer organismId) {
		this.featureId = featureId;
		this.ref = ref;
		this.source = source;
		this.type = type;
		this.fstart = fstart;
		this.fend = fend;
		this.score = score;
		this.strand = strand;
		this.phase = phase;
		this.seqlen = seqlen;
		this.name = name;
		this.organismId = organismId;
	}

	public Integer getFeatureId() {
		return this.featureId;
	}

	public void setFeatureId(Integer featureId) {
		this.featureId = featureId;
	}

	public String getRef() {
		return this.ref;
	}

	public void setRef(String ref) {
		this.ref = ref;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Integer getFstart() {
		return this.fstart;
	}

	public void setFstart(Integer fstart) {
		this.fstart = fstart;
	}

	public Integer getFend() {
		return this.fend;
	}

	public void setFend(Integer fend) {
		this.fend = fend;
	}

	public String getScore() {
		return this.score;
	}

	public void setScore(String score) {
		this.score = score;
	}

	public String getStrand() {
		return this.strand;
	}

	public void setStrand(String strand) {
		this.strand = strand;
	}

	public String getPhase() {
		return this.phase;
	}

	public void setPhase(String phase) {
		this.phase = phase;
	}

	public Integer getSeqlen() {
		return this.seqlen;
	}

	public void setSeqlen(Integer seqlen) {
		this.seqlen = seqlen;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getOrganismId() {
		return this.organismId;
	}

	public void setOrganismId(Integer organismId) {
		this.organismId = organismId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Gff3viewId))
			return false;
		Gff3viewId castOther = (Gff3viewId) other;

		return ((this.getFeatureId() == castOther.getFeatureId()) || (this
				.getFeatureId() != null && castOther.getFeatureId() != null && this
				.getFeatureId().equals(castOther.getFeatureId())))
				&& ((this.getRef() == castOther.getRef()) || (this.getRef() != null
						&& castOther.getRef() != null && this.getRef().equals(
						castOther.getRef())))
				&& ((this.getSource() == castOther.getSource()) || (this
						.getSource() != null && castOther.getSource() != null && this
						.getSource().equals(castOther.getSource())))
				&& ((this.getType() == castOther.getType()) || (this.getType() != null
						&& castOther.getType() != null && this.getType()
						.equals(castOther.getType())))
				&& ((this.getFstart() == castOther.getFstart()) || (this
						.getFstart() != null && castOther.getFstart() != null && this
						.getFstart().equals(castOther.getFstart())))
				&& ((this.getFend() == castOther.getFend()) || (this.getFend() != null
						&& castOther.getFend() != null && this.getFend()
						.equals(castOther.getFend())))
				&& ((this.getScore() == castOther.getScore()) || (this
						.getScore() != null && castOther.getScore() != null && this
						.getScore().equals(castOther.getScore())))
				&& ((this.getStrand() == castOther.getStrand()) || (this
						.getStrand() != null && castOther.getStrand() != null && this
						.getStrand().equals(castOther.getStrand())))
				&& ((this.getPhase() == castOther.getPhase()) || (this
						.getPhase() != null && castOther.getPhase() != null && this
						.getPhase().equals(castOther.getPhase())))
				&& ((this.getSeqlen() == castOther.getSeqlen()) || (this
						.getSeqlen() != null && castOther.getSeqlen() != null && this
						.getSeqlen().equals(castOther.getSeqlen())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())))
				&& ((this.getOrganismId() == castOther.getOrganismId()) || (this
						.getOrganismId() != null
						&& castOther.getOrganismId() != null && this
						.getOrganismId().equals(castOther.getOrganismId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getFeatureId() == null ? 0 : this.getFeatureId().hashCode());
		result = 37 * result
				+ (getRef() == null ? 0 : this.getRef().hashCode());
		result = 37 * result
				+ (getSource() == null ? 0 : this.getSource().hashCode());
		result = 37 * result
				+ (getType() == null ? 0 : this.getType().hashCode());
		result = 37 * result
				+ (getFstart() == null ? 0 : this.getFstart().hashCode());
		result = 37 * result
				+ (getFend() == null ? 0 : this.getFend().hashCode());
		result = 37 * result
				+ (getScore() == null ? 0 : this.getScore().hashCode());
		result = 37 * result
				+ (getStrand() == null ? 0 : this.getStrand().hashCode());
		result = 37 * result
				+ (getPhase() == null ? 0 : this.getPhase().hashCode());
		result = 37 * result
				+ (getSeqlen() == null ? 0 : this.getSeqlen().hashCode());
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37
				* result
				+ (getOrganismId() == null ? 0 : this.getOrganismId()
						.hashCode());
		return result;
	}

}
