package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * IntronlocView generated by hbm2java
 */
public class IntronlocView implements java.io.Serializable {

	private IntronlocViewId id;

	public IntronlocView() {
	}

	public IntronlocView(IntronlocViewId id) {
		this.id = id;
	}

	public IntronlocViewId getId() {
		return this.id;
	}

	public void setId(IntronlocViewId id) {
		this.id = id;
	}

}
