package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * LibraryPub generated by hbm2java
 */
public class LibraryPub implements java.io.Serializable {

	private int libraryPubId;
	private Pub pub;
	private Library library;

	public LibraryPub() {
	}

	public LibraryPub(int libraryPubId, Pub pub, Library library) {
		this.libraryPubId = libraryPubId;
		this.pub = pub;
		this.library = library;
	}

	public int getLibraryPubId() {
		return this.libraryPubId;
	}

	public void setLibraryPubId(int libraryPubId) {
		this.libraryPubId = libraryPubId;
	}

	public Pub getPub() {
		return this.pub;
	}

	public void setPub(Pub pub) {
		this.pub = pub;
	}

	public Library getLibrary() {
		return this.library;
	}

	public void setLibrary(Library library) {
		this.library = library;
	}

}
