package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * NdExperimentDbxref generated by hbm2java
 */
public class NdExperimentDbxref implements java.io.Serializable {

	private int ndExperimentDbxrefId;
	private Dbxref dbxref;
	private NdExperiment ndExperiment;

	public NdExperimentDbxref() {
	}

	public NdExperimentDbxref(int ndExperimentDbxrefId, Dbxref dbxref,
			NdExperiment ndExperiment) {
		this.ndExperimentDbxrefId = ndExperimentDbxrefId;
		this.dbxref = dbxref;
		this.ndExperiment = ndExperiment;
	}

	public int getNdExperimentDbxrefId() {
		return this.ndExperimentDbxrefId;
	}

	public void setNdExperimentDbxrefId(int ndExperimentDbxrefId) {
		this.ndExperimentDbxrefId = ndExperimentDbxrefId;
	}

	public Dbxref getDbxref() {
		return this.dbxref;
	}

	public void setDbxref(Dbxref dbxref) {
		this.dbxref = dbxref;
	}

	public NdExperiment getNdExperiment() {
		return this.ndExperiment;
	}

	public void setNdExperiment(NdExperiment ndExperiment) {
		this.ndExperiment = ndExperiment;
	}

}
