package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * NdExperimentprop generated by hbm2java
 */
public class NdExperimentprop implements java.io.Serializable {

	private int ndExperimentpropId;
	private NdExperiment ndExperiment;
	private Cvterm cvterm;
	private String value;
	private int rank;

	public NdExperimentprop() {
	}

	public NdExperimentprop(int ndExperimentpropId, NdExperiment ndExperiment,
			Cvterm cvterm, int rank) {
		this.ndExperimentpropId = ndExperimentpropId;
		this.ndExperiment = ndExperiment;
		this.cvterm = cvterm;
		this.rank = rank;
	}

	public NdExperimentprop(int ndExperimentpropId, NdExperiment ndExperiment,
			Cvterm cvterm, String value, int rank) {
		this.ndExperimentpropId = ndExperimentpropId;
		this.ndExperiment = ndExperiment;
		this.cvterm = cvterm;
		this.value = value;
		this.rank = rank;
	}

	public int getNdExperimentpropId() {
		return this.ndExperimentpropId;
	}

	public void setNdExperimentpropId(int ndExperimentpropId) {
		this.ndExperimentpropId = ndExperimentpropId;
	}

	public NdExperiment getNdExperiment() {
		return this.ndExperiment;
	}

	public void setNdExperiment(NdExperiment ndExperiment) {
		this.ndExperiment = ndExperiment;
	}

	public Cvterm getCvterm() {
		return this.cvterm;
	}

	public void setCvterm(Cvterm cvterm) {
		this.cvterm = cvterm;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public int getRank() {
		return this.rank;
	}

	public void setRank(int rank) {
		this.rank = rank;
	}

}
