package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * NdExperimentPub generated by hbm2java
 */
public class NdExperimentPub implements java.io.Serializable {

	private int ndExperimentPubId;
	private Pub pub;
	private NdExperiment ndExperiment;

	public NdExperimentPub() {
	}

	public NdExperimentPub(int ndExperimentPubId, Pub pub,
			NdExperiment ndExperiment) {
		this.ndExperimentPubId = ndExperimentPubId;
		this.pub = pub;
		this.ndExperiment = ndExperiment;
	}

	public int getNdExperimentPubId() {
		return this.ndExperimentPubId;
	}

	public void setNdExperimentPubId(int ndExperimentPubId) {
		this.ndExperimentPubId = ndExperimentPubId;
	}

	public Pub getPub() {
		return this.pub;
	}

	public void setPub(Pub pub) {
		this.pub = pub;
	}

	public NdExperiment getNdExperiment() {
		return this.ndExperiment;
	}

	public void setNdExperiment(NdExperiment ndExperiment) {
		this.ndExperiment = ndExperiment;
	}

}
