package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * NdReagentRelationship generated by hbm2java
 */
public class NdReagentRelationship implements java.io.Serializable {

	private int ndReagentRelationshipId;
	private NdReagent ndReagentByObjectReagentId;
	private NdReagent ndReagentBySubjectReagentId;
	private Cvterm cvterm;

	public NdReagentRelationship() {
	}

	public NdReagentRelationship(int ndReagentRelationshipId,
			NdReagent ndReagentByObjectReagentId,
			NdReagent ndReagentBySubjectReagentId, Cvterm cvterm) {
		this.ndReagentRelationshipId = ndReagentRelationshipId;
		this.ndReagentByObjectReagentId = ndReagentByObjectReagentId;
		this.ndReagentBySubjectReagentId = ndReagentBySubjectReagentId;
		this.cvterm = cvterm;
	}

	public int getNdReagentRelationshipId() {
		return this.ndReagentRelationshipId;
	}

	public void setNdReagentRelationshipId(int ndReagentRelationshipId) {
		this.ndReagentRelationshipId = ndReagentRelationshipId;
	}

	public NdReagent getNdReagentByObjectReagentId() {
		return this.ndReagentByObjectReagentId;
	}

	public void setNdReagentByObjectReagentId(
			NdReagent ndReagentByObjectReagentId) {
		this.ndReagentByObjectReagentId = ndReagentByObjectReagentId;
	}

	public NdReagent getNdReagentBySubjectReagentId() {
		return this.ndReagentBySubjectReagentId;
	}

	public void setNdReagentBySubjectReagentId(
			NdReagent ndReagentBySubjectReagentId) {
		this.ndReagentBySubjectReagentId = ndReagentBySubjectReagentId;
	}

	public Cvterm getCvterm() {
		return this.cvterm;
	}

	public void setCvterm(Cvterm cvterm) {
		this.cvterm = cvterm;
	}

}
