package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Organism generated by hbm2java
 */
public class Organism implements java.io.Serializable {

	private int organismId;
	private String abbreviation;
	private String genus;
	private String species;
	private String commonName;
	private String comment;
	private Set organismprops = new HashSet(0);
	private Set libraries = new HashSet(0);
	private Set biomaterials = new HashSet(0);
	private Set phylonodeOrganisms = new HashSet(0);
	private Set phenotypeComparisons = new HashSet(0);
	private Set stocks = new HashSet(0);
	private Set features = new HashSet(0);
	private Set organismDbxrefs = new HashSet(0);
	private Set cellLines = new HashSet(0);

	public Organism() {
	}

	public Organism(int organismId, String genus, String species) {
		this.organismId = organismId;
		this.genus = genus;
		this.species = species;
	}

	public Organism(int organismId, String abbreviation, String genus,
			String species, String commonName, String comment,
			Set organismprops, Set libraries, Set biomaterials,
			Set phylonodeOrganisms, Set phenotypeComparisons, Set stocks,
			Set features, Set organismDbxrefs, Set cellLines) {
		this.organismId = organismId;
		this.abbreviation = abbreviation;
		this.genus = genus;
		this.species = species;
		this.commonName = commonName;
		this.comment = comment;
		this.organismprops = organismprops;
		this.libraries = libraries;
		this.biomaterials = biomaterials;
		this.phylonodeOrganisms = phylonodeOrganisms;
		this.phenotypeComparisons = phenotypeComparisons;
		this.stocks = stocks;
		this.features = features;
		this.organismDbxrefs = organismDbxrefs;
		this.cellLines = cellLines;
	}

	public int getOrganismId() {
		return this.organismId;
	}

	public void setOrganismId(int organismId) {
		this.organismId = organismId;
	}

	public String getAbbreviation() {
		return this.abbreviation;
	}

	public void setAbbreviation(String abbreviation) {
		this.abbreviation = abbreviation;
	}

	public String getGenus() {
		return this.genus;
	}

	public void setGenus(String genus) {
		this.genus = genus;
	}

	public String getSpecies() {
		return this.species;
	}

	public void setSpecies(String species) {
		this.species = species;
	}

	public String getCommonName() {
		return this.commonName;
	}

	public void setCommonName(String commonName) {
		this.commonName = commonName;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Set getOrganismprops() {
		return this.organismprops;
	}

	public void setOrganismprops(Set organismprops) {
		this.organismprops = organismprops;
	}

	public Set getLibraries() {
		return this.libraries;
	}

	public void setLibraries(Set libraries) {
		this.libraries = libraries;
	}

	public Set getBiomaterials() {
		return this.biomaterials;
	}

	public void setBiomaterials(Set biomaterials) {
		this.biomaterials = biomaterials;
	}

	public Set getPhylonodeOrganisms() {
		return this.phylonodeOrganisms;
	}

	public void setPhylonodeOrganisms(Set phylonodeOrganisms) {
		this.phylonodeOrganisms = phylonodeOrganisms;
	}

	public Set getPhenotypeComparisons() {
		return this.phenotypeComparisons;
	}

	public void setPhenotypeComparisons(Set phenotypeComparisons) {
		this.phenotypeComparisons = phenotypeComparisons;
	}

	public Set getStocks() {
		return this.stocks;
	}

	public void setStocks(Set stocks) {
		this.stocks = stocks;
	}

	public Set getFeatures() {
		return this.features;
	}

	public void setFeatures(Set features) {
		this.features = features;
	}

	public Set getOrganismDbxrefs() {
		return this.organismDbxrefs;
	}

	public void setOrganismDbxrefs(Set organismDbxrefs) {
		this.organismDbxrefs = organismDbxrefs;
	}

	public Set getCellLines() {
		return this.cellLines;
	}

	public void setCellLines(Set cellLines) {
		this.cellLines = cellLines;
	}

}
