package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * OrganismDbxref generated by hbm2java
 */
public class OrganismDbxref implements java.io.Serializable {

	private int organismDbxrefId;
	private Dbxref dbxref;
	private Organism organism;

	public OrganismDbxref() {
	}

	public OrganismDbxref(int organismDbxrefId, Dbxref dbxref, Organism organism) {
		this.organismDbxrefId = organismDbxrefId;
		this.dbxref = dbxref;
		this.organism = organism;
	}

	public int getOrganismDbxrefId() {
		return this.organismDbxrefId;
	}

	public void setOrganismDbxrefId(int organismDbxrefId) {
		this.organismDbxrefId = organismDbxrefId;
	}

	public Dbxref getDbxref() {
		return this.dbxref;
	}

	public void setDbxref(Dbxref dbxref) {
		this.dbxref = dbxref;
	}

	public Organism getOrganism() {
		return this.organism;
	}

	public void setOrganism(Organism organism) {
		this.organism = organism;
	}

}
