package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * Phendesc generated by hbm2java
 */
public class Phendesc implements java.io.Serializable {

	private int phendescId;
	private Pub pub;
	private Environment environment;
	private Genotype genotype;
	private Cvterm cvterm;
	private String description;

	public Phendesc() {
	}

	public Phendesc(int phendescId, Pub pub, Environment environment,
			Genotype genotype, Cvterm cvterm, String description) {
		this.phendescId = phendescId;
		this.pub = pub;
		this.environment = environment;
		this.genotype = genotype;
		this.cvterm = cvterm;
		this.description = description;
	}

	public int getPhendescId() {
		return this.phendescId;
	}

	public void setPhendescId(int phendescId) {
		this.phendescId = phendescId;
	}

	public Pub getPub() {
		return this.pub;
	}

	public void setPub(Pub pub) {
		this.pub = pub;
	}

	public Environment getEnvironment() {
		return this.environment;
	}

	public void setEnvironment(Environment environment) {
		this.environment = environment;
	}

	public Genotype getGenotype() {
		return this.genotype;
	}

	public void setGenotype(Genotype genotype) {
		this.genotype = genotype;
	}

	public Cvterm getCvterm() {
		return this.cvterm;
	}

	public void setCvterm(Cvterm cvterm) {
		this.cvterm = cvterm;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
