package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * PhenotypeCvterm generated by hbm2java
 */
public class PhenotypeCvterm implements java.io.Serializable {

	private int phenotypeCvtermId;
	private Cvterm cvterm;
	private Phenotype phenotype;
	private int rank;

	public PhenotypeCvterm() {
	}

	public PhenotypeCvterm(int phenotypeCvtermId, Cvterm cvterm,
			Phenotype phenotype, int rank) {
		this.phenotypeCvtermId = phenotypeCvtermId;
		this.cvterm = cvterm;
		this.phenotype = phenotype;
		this.rank = rank;
	}

	public int getPhenotypeCvtermId() {
		return this.phenotypeCvtermId;
	}

	public void setPhenotypeCvtermId(int phenotypeCvtermId) {
		this.phenotypeCvtermId = phenotypeCvtermId;
	}

	public Cvterm getCvterm() {
		return this.cvterm;
	}

	public void setCvterm(Cvterm cvterm) {
		this.cvterm = cvterm;
	}

	public Phenotype getPhenotype() {
		return this.phenotype;
	}

	public void setPhenotype(Phenotype phenotype) {
		this.phenotype = phenotype;
	}

	public int getRank() {
		return this.rank;
	}

	public void setRank(int rank) {
		this.rank = rank;
	}

}
