package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * PhenotypeComparisonCvterm generated by hbm2java
 */
public class PhenotypeComparisonCvterm implements java.io.Serializable {

	private int phenotypeComparisonCvtermId;
	private Pub pub;
	private PhenotypeComparison phenotypeComparison;
	private Cvterm cvterm;
	private int rank;

	public PhenotypeComparisonCvterm() {
	}

	public PhenotypeComparisonCvterm(int phenotypeComparisonCvtermId, Pub pub,
			PhenotypeComparison phenotypeComparison, Cvterm cvterm, int rank) {
		this.phenotypeComparisonCvtermId = phenotypeComparisonCvtermId;
		this.pub = pub;
		this.phenotypeComparison = phenotypeComparison;
		this.cvterm = cvterm;
		this.rank = rank;
	}

	public int getPhenotypeComparisonCvtermId() {
		return this.phenotypeComparisonCvtermId;
	}

	public void setPhenotypeComparisonCvtermId(int phenotypeComparisonCvtermId) {
		this.phenotypeComparisonCvtermId = phenotypeComparisonCvtermId;
	}

	public Pub getPub() {
		return this.pub;
	}

	public void setPub(Pub pub) {
		this.pub = pub;
	}

	public PhenotypeComparison getPhenotypeComparison() {
		return this.phenotypeComparison;
	}

	public void setPhenotypeComparison(PhenotypeComparison phenotypeComparison) {
		this.phenotypeComparison = phenotypeComparison;
	}

	public Cvterm getCvterm() {
		return this.cvterm;
	}

	public void setCvterm(Cvterm cvterm) {
		this.cvterm = cvterm;
	}

	public int getRank() {
		return this.rank;
	}

	public void setRank(int rank) {
		this.rank = rank;
	}

}
