package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * PhylotreePub generated by hbm2java
 */
public class PhylotreePub implements java.io.Serializable {

	private int phylotreePubId;
	private Pub pub;
	private Phylotree phylotree;

	public PhylotreePub() {
	}

	public PhylotreePub(int phylotreePubId, Pub pub, Phylotree phylotree) {
		this.phylotreePubId = phylotreePubId;
		this.pub = pub;
		this.phylotree = phylotree;
	}

	public int getPhylotreePubId() {
		return this.phylotreePubId;
	}

	public void setPhylotreePubId(int phylotreePubId) {
		this.phylotreePubId = phylotreePubId;
	}

	public Pub getPub() {
		return this.pub;
	}

	public void setPub(Pub pub) {
		this.pub = pub;
	}

	public Phylotree getPhylotree() {
		return this.phylotree;
	}

	public void setPhylotree(Phylotree phylotree) {
		this.phylotree = phylotree;
	}

}
