package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * ProjectRelationship generated by hbm2java
 */
public class ProjectRelationship implements java.io.Serializable {

	private int projectRelationshipId;
	private Project projectByObjectProjectId;
	private Project projectBySubjectProjectId;
	private Cvterm cvterm;

	public ProjectRelationship() {
	}

	public ProjectRelationship(int projectRelationshipId,
			Project projectByObjectProjectId,
			Project projectBySubjectProjectId, Cvterm cvterm) {
		this.projectRelationshipId = projectRelationshipId;
		this.projectByObjectProjectId = projectByObjectProjectId;
		this.projectBySubjectProjectId = projectBySubjectProjectId;
		this.cvterm = cvterm;
	}

	public int getProjectRelationshipId() {
		return this.projectRelationshipId;
	}

	public void setProjectRelationshipId(int projectRelationshipId) {
		this.projectRelationshipId = projectRelationshipId;
	}

	public Project getProjectByObjectProjectId() {
		return this.projectByObjectProjectId;
	}

	public void setProjectByObjectProjectId(Project projectByObjectProjectId) {
		this.projectByObjectProjectId = projectByObjectProjectId;
	}

	public Project getProjectBySubjectProjectId() {
		return this.projectBySubjectProjectId;
	}

	public void setProjectBySubjectProjectId(Project projectBySubjectProjectId) {
		this.projectBySubjectProjectId = projectBySubjectProjectId;
	}

	public Cvterm getCvterm() {
		return this.cvterm;
	}

	public void setCvterm(Cvterm cvterm) {
		this.cvterm = cvterm;
	}

}
