package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * ProteinCodingGene generated by hbm2java
 */
public class ProteinCodingGene implements java.io.Serializable {

	private ProteinCodingGeneId id;

	public ProteinCodingGene() {
	}

	public ProteinCodingGene(ProteinCodingGeneId id) {
		this.id = id;
	}

	public ProteinCodingGeneId getId() {
		return this.id;
	}

	public void setId(ProteinCodingGeneId id) {
		this.id = id;
	}

}
