package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Pub generated by hbm2java
 */
public class Pub implements java.io.Serializable {

	private int pubId;
	private Cvterm cvterm;
	private String title;
	private String volumetitle;
	private String volume;
	private String seriesName;
	private String issue;
	private String pyear;
	private String pages;
	private String miniref;
	private String uniquename;
	private Boolean isObsolete;
	private String publisher;
	private String pubplace;
	private Set stockRelationshipPubs = new HashSet(0);
	private Set featurePubs = new HashSet(0);
	private Set stockPubs = new HashSet(0);
	private Set cellLineSynonyms = new HashSet(0);
	private Set cellLineCvterms = new HashSet(0);
	private Set featureSynonyms = new HashSet(0);
	private Set stockRelationshipCvterms = new HashSet(0);
	private Set phenstatements = new HashSet(0);
	private Set cellLinePubs = new HashSet(0);
	private Set featuremapPubs = new HashSet(0);
	private Set featurepropPubs = new HashSet(0);
	private Set ndExperimentPubs = new HashSet(0);
	private Set phendescs = new HashSet(0);
	private Set phenotypeComparisons = new HashSet(0);
	private Set cellLinepropPubs = new HashSet(0);
	private Set stockpropPubs = new HashSet(0);
	private Set pubprops = new HashSet(0);
	private Set librarypropPubs = new HashSet(0);
	private Set featureCvtermPubs = new HashSet(0);
	private Set librarySynonyms = new HashSet(0);
	private Set cellLineLibraries = new HashSet(0);
	private Set featurelocPubs = new HashSet(0);
	private Set libraryPubs = new HashSet(0);
	private Set cellLineFeatures = new HashSet(0);
	private Set projectPubs = new HashSet(0);
	private Set featureRelationshippropPubs = new HashSet(0);
	private Set libraryCvterms = new HashSet(0);
	private Set studies = new HashSet(0);
	private Set pubDbxrefs = new HashSet(0);
	private Set featureCvterms = new HashSet(0);
	private Set stockCvterms = new HashSet(0);
	private Set featureExpressions = new HashSet(0);
	private Set expressionPubs = new HashSet(0);
	private Set phylonodePubs = new HashSet(0);
	private Set protocols = new HashSet(0);
	private Set featureRelationshipPubs = new HashSet(0);
	private Set phylotreePubs = new HashSet(0);
	private Set phenotypeComparisonCvterms = new HashSet(0);
	private Set pubRelationshipsForObjectId = new HashSet(0);
	private Set pubRelationshipsForSubjectId = new HashSet(0);
	private Set pubauthors = new HashSet(0);

	public Pub() {
	}

	public Pub(int pubId, Cvterm cvterm, String uniquename) {
		this.pubId = pubId;
		this.cvterm = cvterm;
		this.uniquename = uniquename;
	}

	public Pub(int pubId, Cvterm cvterm, String title, String volumetitle,
			String volume, String seriesName, String issue, String pyear,
			String pages, String miniref, String uniquename,
			Boolean isObsolete, String publisher, String pubplace,
			Set stockRelationshipPubs, Set featurePubs, Set stockPubs,
			Set cellLineSynonyms, Set cellLineCvterms, Set featureSynonyms,
			Set stockRelationshipCvterms, Set phenstatements, Set cellLinePubs,
			Set featuremapPubs, Set featurepropPubs, Set ndExperimentPubs,
			Set phendescs, Set phenotypeComparisons, Set cellLinepropPubs,
			Set stockpropPubs, Set pubprops, Set librarypropPubs,
			Set featureCvtermPubs, Set librarySynonyms, Set cellLineLibraries,
			Set featurelocPubs, Set libraryPubs, Set cellLineFeatures,
			Set projectPubs, Set featureRelationshippropPubs,
			Set libraryCvterms, Set studies, Set pubDbxrefs,
			Set featureCvterms, Set stockCvterms, Set featureExpressions,
			Set expressionPubs, Set phylonodePubs, Set protocols,
			Set featureRelationshipPubs, Set phylotreePubs,
			Set phenotypeComparisonCvterms, Set pubRelationshipsForObjectId,
			Set pubRelationshipsForSubjectId, Set pubauthors) {
		this.pubId = pubId;
		this.cvterm = cvterm;
		this.title = title;
		this.volumetitle = volumetitle;
		this.volume = volume;
		this.seriesName = seriesName;
		this.issue = issue;
		this.pyear = pyear;
		this.pages = pages;
		this.miniref = miniref;
		this.uniquename = uniquename;
		this.isObsolete = isObsolete;
		this.publisher = publisher;
		this.pubplace = pubplace;
		this.stockRelationshipPubs = stockRelationshipPubs;
		this.featurePubs = featurePubs;
		this.stockPubs = stockPubs;
		this.cellLineSynonyms = cellLineSynonyms;
		this.cellLineCvterms = cellLineCvterms;
		this.featureSynonyms = featureSynonyms;
		this.stockRelationshipCvterms = stockRelationshipCvterms;
		this.phenstatements = phenstatements;
		this.cellLinePubs = cellLinePubs;
		this.featuremapPubs = featuremapPubs;
		this.featurepropPubs = featurepropPubs;
		this.ndExperimentPubs = ndExperimentPubs;
		this.phendescs = phendescs;
		this.phenotypeComparisons = phenotypeComparisons;
		this.cellLinepropPubs = cellLinepropPubs;
		this.stockpropPubs = stockpropPubs;
		this.pubprops = pubprops;
		this.librarypropPubs = librarypropPubs;
		this.featureCvtermPubs = featureCvtermPubs;
		this.librarySynonyms = librarySynonyms;
		this.cellLineLibraries = cellLineLibraries;
		this.featurelocPubs = featurelocPubs;
		this.libraryPubs = libraryPubs;
		this.cellLineFeatures = cellLineFeatures;
		this.projectPubs = projectPubs;
		this.featureRelationshippropPubs = featureRelationshippropPubs;
		this.libraryCvterms = libraryCvterms;
		this.studies = studies;
		this.pubDbxrefs = pubDbxrefs;
		this.featureCvterms = featureCvterms;
		this.stockCvterms = stockCvterms;
		this.featureExpressions = featureExpressions;
		this.expressionPubs = expressionPubs;
		this.phylonodePubs = phylonodePubs;
		this.protocols = protocols;
		this.featureRelationshipPubs = featureRelationshipPubs;
		this.phylotreePubs = phylotreePubs;
		this.phenotypeComparisonCvterms = phenotypeComparisonCvterms;
		this.pubRelationshipsForObjectId = pubRelationshipsForObjectId;
		this.pubRelationshipsForSubjectId = pubRelationshipsForSubjectId;
		this.pubauthors = pubauthors;
	}

	public int getPubId() {
		return this.pubId;
	}

	public void setPubId(int pubId) {
		this.pubId = pubId;
	}

	public Cvterm getCvterm() {
		return this.cvterm;
	}

	public void setCvterm(Cvterm cvterm) {
		this.cvterm = cvterm;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getVolumetitle() {
		return this.volumetitle;
	}

	public void setVolumetitle(String volumetitle) {
		this.volumetitle = volumetitle;
	}

	public String getVolume() {
		return this.volume;
	}

	public void setVolume(String volume) {
		this.volume = volume;
	}

	public String getSeriesName() {
		return this.seriesName;
	}

	public void setSeriesName(String seriesName) {
		this.seriesName = seriesName;
	}

	public String getIssue() {
		return this.issue;
	}

	public void setIssue(String issue) {
		this.issue = issue;
	}

	public String getPyear() {
		return this.pyear;
	}

	public void setPyear(String pyear) {
		this.pyear = pyear;
	}

	public String getPages() {
		return this.pages;
	}

	public void setPages(String pages) {
		this.pages = pages;
	}

	public String getMiniref() {
		return this.miniref;
	}

	public void setMiniref(String miniref) {
		this.miniref = miniref;
	}

	public String getUniquename() {
		return this.uniquename;
	}

	public void setUniquename(String uniquename) {
		this.uniquename = uniquename;
	}

	public Boolean getIsObsolete() {
		return this.isObsolete;
	}

	public void setIsObsolete(Boolean isObsolete) {
		this.isObsolete = isObsolete;
	}

	public String getPublisher() {
		return this.publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	public String getPubplace() {
		return this.pubplace;
	}

	public void setPubplace(String pubplace) {
		this.pubplace = pubplace;
	}

	public Set getStockRelationshipPubs() {
		return this.stockRelationshipPubs;
	}

	public void setStockRelationshipPubs(Set stockRelationshipPubs) {
		this.stockRelationshipPubs = stockRelationshipPubs;
	}

	public Set getFeaturePubs() {
		return this.featurePubs;
	}

	public void setFeaturePubs(Set featurePubs) {
		this.featurePubs = featurePubs;
	}

	public Set getStockPubs() {
		return this.stockPubs;
	}

	public void setStockPubs(Set stockPubs) {
		this.stockPubs = stockPubs;
	}

	public Set getCellLineSynonyms() {
		return this.cellLineSynonyms;
	}

	public void setCellLineSynonyms(Set cellLineSynonyms) {
		this.cellLineSynonyms = cellLineSynonyms;
	}

	public Set getCellLineCvterms() {
		return this.cellLineCvterms;
	}

	public void setCellLineCvterms(Set cellLineCvterms) {
		this.cellLineCvterms = cellLineCvterms;
	}

	public Set getFeatureSynonyms() {
		return this.featureSynonyms;
	}

	public void setFeatureSynonyms(Set featureSynonyms) {
		this.featureSynonyms = featureSynonyms;
	}

	public Set getStockRelationshipCvterms() {
		return this.stockRelationshipCvterms;
	}

	public void setStockRelationshipCvterms(Set stockRelationshipCvterms) {
		this.stockRelationshipCvterms = stockRelationshipCvterms;
	}

	public Set getPhenstatements() {
		return this.phenstatements;
	}

	public void setPhenstatements(Set phenstatements) {
		this.phenstatements = phenstatements;
	}

	public Set getCellLinePubs() {
		return this.cellLinePubs;
	}

	public void setCellLinePubs(Set cellLinePubs) {
		this.cellLinePubs = cellLinePubs;
	}

	public Set getFeaturemapPubs() {
		return this.featuremapPubs;
	}

	public void setFeaturemapPubs(Set featuremapPubs) {
		this.featuremapPubs = featuremapPubs;
	}

	public Set getFeaturepropPubs() {
		return this.featurepropPubs;
	}

	public void setFeaturepropPubs(Set featurepropPubs) {
		this.featurepropPubs = featurepropPubs;
	}

	public Set getNdExperimentPubs() {
		return this.ndExperimentPubs;
	}

	public void setNdExperimentPubs(Set ndExperimentPubs) {
		this.ndExperimentPubs = ndExperimentPubs;
	}

	public Set getPhendescs() {
		return this.phendescs;
	}

	public void setPhendescs(Set phendescs) {
		this.phendescs = phendescs;
	}

	public Set getPhenotypeComparisons() {
		return this.phenotypeComparisons;
	}

	public void setPhenotypeComparisons(Set phenotypeComparisons) {
		this.phenotypeComparisons = phenotypeComparisons;
	}

	public Set getCellLinepropPubs() {
		return this.cellLinepropPubs;
	}

	public void setCellLinepropPubs(Set cellLinepropPubs) {
		this.cellLinepropPubs = cellLinepropPubs;
	}

	public Set getStockpropPubs() {
		return this.stockpropPubs;
	}

	public void setStockpropPubs(Set stockpropPubs) {
		this.stockpropPubs = stockpropPubs;
	}

	public Set getPubprops() {
		return this.pubprops;
	}

	public void setPubprops(Set pubprops) {
		this.pubprops = pubprops;
	}

	public Set getLibrarypropPubs() {
		return this.librarypropPubs;
	}

	public void setLibrarypropPubs(Set librarypropPubs) {
		this.librarypropPubs = librarypropPubs;
	}

	public Set getFeatureCvtermPubs() {
		return this.featureCvtermPubs;
	}

	public void setFeatureCvtermPubs(Set featureCvtermPubs) {
		this.featureCvtermPubs = featureCvtermPubs;
	}

	public Set getLibrarySynonyms() {
		return this.librarySynonyms;
	}

	public void setLibrarySynonyms(Set librarySynonyms) {
		this.librarySynonyms = librarySynonyms;
	}

	public Set getCellLineLibraries() {
		return this.cellLineLibraries;
	}

	public void setCellLineLibraries(Set cellLineLibraries) {
		this.cellLineLibraries = cellLineLibraries;
	}

	public Set getFeaturelocPubs() {
		return this.featurelocPubs;
	}

	public void setFeaturelocPubs(Set featurelocPubs) {
		this.featurelocPubs = featurelocPubs;
	}

	public Set getLibraryPubs() {
		return this.libraryPubs;
	}

	public void setLibraryPubs(Set libraryPubs) {
		this.libraryPubs = libraryPubs;
	}

	public Set getCellLineFeatures() {
		return this.cellLineFeatures;
	}

	public void setCellLineFeatures(Set cellLineFeatures) {
		this.cellLineFeatures = cellLineFeatures;
	}

	public Set getProjectPubs() {
		return this.projectPubs;
	}

	public void setProjectPubs(Set projectPubs) {
		this.projectPubs = projectPubs;
	}

	public Set getFeatureRelationshippropPubs() {
		return this.featureRelationshippropPubs;
	}

	public void setFeatureRelationshippropPubs(Set featureRelationshippropPubs) {
		this.featureRelationshippropPubs = featureRelationshippropPubs;
	}

	public Set getLibraryCvterms() {
		return this.libraryCvterms;
	}

	public void setLibraryCvterms(Set libraryCvterms) {
		this.libraryCvterms = libraryCvterms;
	}

	public Set getStudies() {
		return this.studies;
	}

	public void setStudies(Set studies) {
		this.studies = studies;
	}

	public Set getPubDbxrefs() {
		return this.pubDbxrefs;
	}

	public void setPubDbxrefs(Set pubDbxrefs) {
		this.pubDbxrefs = pubDbxrefs;
	}

	public Set getFeatureCvterms() {
		return this.featureCvterms;
	}

	public void setFeatureCvterms(Set featureCvterms) {
		this.featureCvterms = featureCvterms;
	}

	public Set getStockCvterms() {
		return this.stockCvterms;
	}

	public void setStockCvterms(Set stockCvterms) {
		this.stockCvterms = stockCvterms;
	}

	public Set getFeatureExpressions() {
		return this.featureExpressions;
	}

	public void setFeatureExpressions(Set featureExpressions) {
		this.featureExpressions = featureExpressions;
	}

	public Set getExpressionPubs() {
		return this.expressionPubs;
	}

	public void setExpressionPubs(Set expressionPubs) {
		this.expressionPubs = expressionPubs;
	}

	public Set getPhylonodePubs() {
		return this.phylonodePubs;
	}

	public void setPhylonodePubs(Set phylonodePubs) {
		this.phylonodePubs = phylonodePubs;
	}

	public Set getProtocols() {
		return this.protocols;
	}

	public void setProtocols(Set protocols) {
		this.protocols = protocols;
	}

	public Set getFeatureRelationshipPubs() {
		return this.featureRelationshipPubs;
	}

	public void setFeatureRelationshipPubs(Set featureRelationshipPubs) {
		this.featureRelationshipPubs = featureRelationshipPubs;
	}

	public Set getPhylotreePubs() {
		return this.phylotreePubs;
	}

	public void setPhylotreePubs(Set phylotreePubs) {
		this.phylotreePubs = phylotreePubs;
	}

	public Set getPhenotypeComparisonCvterms() {
		return this.phenotypeComparisonCvterms;
	}

	public void setPhenotypeComparisonCvterms(Set phenotypeComparisonCvterms) {
		this.phenotypeComparisonCvterms = phenotypeComparisonCvterms;
	}

	public Set getPubRelationshipsForObjectId() {
		return this.pubRelationshipsForObjectId;
	}

	public void setPubRelationshipsForObjectId(Set pubRelationshipsForObjectId) {
		this.pubRelationshipsForObjectId = pubRelationshipsForObjectId;
	}

	public Set getPubRelationshipsForSubjectId() {
		return this.pubRelationshipsForSubjectId;
	}

	public void setPubRelationshipsForSubjectId(Set pubRelationshipsForSubjectId) {
		this.pubRelationshipsForSubjectId = pubRelationshipsForSubjectId;
	}

	public Set getPubauthors() {
		return this.pubauthors;
	}

	public void setPubauthors(Set pubauthors) {
		this.pubauthors = pubauthors;
	}

}
