package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * QuantificationRelationship generated by hbm2java
 */
public class QuantificationRelationship implements java.io.Serializable {

	private int quantificationRelationshipId;
	private Quantification quantificationByObjectId;
	private Quantification quantificationBySubjectId;
	private Cvterm cvterm;

	public QuantificationRelationship() {
	}

	public QuantificationRelationship(int quantificationRelationshipId,
			Quantification quantificationByObjectId,
			Quantification quantificationBySubjectId, Cvterm cvterm) {
		this.quantificationRelationshipId = quantificationRelationshipId;
		this.quantificationByObjectId = quantificationByObjectId;
		this.quantificationBySubjectId = quantificationBySubjectId;
		this.cvterm = cvterm;
	}

	public int getQuantificationRelationshipId() {
		return this.quantificationRelationshipId;
	}

	public void setQuantificationRelationshipId(int quantificationRelationshipId) {
		this.quantificationRelationshipId = quantificationRelationshipId;
	}

	public Quantification getQuantificationByObjectId() {
		return this.quantificationByObjectId;
	}

	public void setQuantificationByObjectId(
			Quantification quantificationByObjectId) {
		this.quantificationByObjectId = quantificationByObjectId;
	}

	public Quantification getQuantificationBySubjectId() {
		return this.quantificationBySubjectId;
	}

	public void setQuantificationBySubjectId(
			Quantification quantificationBySubjectId) {
		this.quantificationBySubjectId = quantificationBySubjectId;
	}

	public Cvterm getCvterm() {
		return this.cvterm;
	}

	public void setCvterm(Cvterm cvterm) {
		this.cvterm = cvterm;
	}

}
