package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Quantification generated by hbm2java
 */
public class Quantification implements java.io.Serializable {

	private int quantificationId;
	private Contact contact;
	private Acquisition acquisition;
	private Protocol protocol;
	private Analysis analysis;
	private Date quantificationdate;
	private String name;
	private String uri;
	private Set quantificationprops = new HashSet(0);
	private Set elementresults = new HashSet(0);
	private Set quantificationRelationshipsForSubjectId = new HashSet(0);
	private Set quantificationRelationshipsForObjectId = new HashSet(0);

	public Quantification() {
	}

	public Quantification(int quantificationId, Acquisition acquisition,
			Analysis analysis) {
		this.quantificationId = quantificationId;
		this.acquisition = acquisition;
		this.analysis = analysis;
	}

	public Quantification(int quantificationId, Contact contact,
			Acquisition acquisition, Protocol protocol, Analysis analysis,
			Date quantificationdate, String name, String uri,
			Set quantificationprops, Set elementresults,
			Set quantificationRelationshipsForSubjectId,
			Set quantificationRelationshipsForObjectId) {
		this.quantificationId = quantificationId;
		this.contact = contact;
		this.acquisition = acquisition;
		this.protocol = protocol;
		this.analysis = analysis;
		this.quantificationdate = quantificationdate;
		this.name = name;
		this.uri = uri;
		this.quantificationprops = quantificationprops;
		this.elementresults = elementresults;
		this.quantificationRelationshipsForSubjectId = quantificationRelationshipsForSubjectId;
		this.quantificationRelationshipsForObjectId = quantificationRelationshipsForObjectId;
	}

	public int getQuantificationId() {
		return this.quantificationId;
	}

	public void setQuantificationId(int quantificationId) {
		this.quantificationId = quantificationId;
	}

	public Contact getContact() {
		return this.contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

	public Acquisition getAcquisition() {
		return this.acquisition;
	}

	public void setAcquisition(Acquisition acquisition) {
		this.acquisition = acquisition;
	}

	public Protocol getProtocol() {
		return this.protocol;
	}

	public void setProtocol(Protocol protocol) {
		this.protocol = protocol;
	}

	public Analysis getAnalysis() {
		return this.analysis;
	}

	public void setAnalysis(Analysis analysis) {
		this.analysis = analysis;
	}

	public Date getQuantificationdate() {
		return this.quantificationdate;
	}

	public void setQuantificationdate(Date quantificationdate) {
		this.quantificationdate = quantificationdate;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUri() {
		return this.uri;
	}

	public void setUri(String uri) {
		this.uri = uri;
	}

	public Set getQuantificationprops() {
		return this.quantificationprops;
	}

	public void setQuantificationprops(Set quantificationprops) {
		this.quantificationprops = quantificationprops;
	}

	public Set getElementresults() {
		return this.elementresults;
	}

	public void setElementresults(Set elementresults) {
		this.elementresults = elementresults;
	}

	public Set getQuantificationRelationshipsForSubjectId() {
		return this.quantificationRelationshipsForSubjectId;
	}

	public void setQuantificationRelationshipsForSubjectId(
			Set quantificationRelationshipsForSubjectId) {
		this.quantificationRelationshipsForSubjectId = quantificationRelationshipsForSubjectId;
	}

	public Set getQuantificationRelationshipsForObjectId() {
		return this.quantificationRelationshipsForObjectId;
	}

	public void setQuantificationRelationshipsForObjectId(
			Set quantificationRelationshipsForObjectId) {
		this.quantificationRelationshipsForObjectId = quantificationRelationshipsForObjectId;
	}

}
