package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * StockRelationship generated by hbm2java
 */
public class StockRelationship implements java.io.Serializable {

	private int stockRelationshipId;
	private Stock stockByObjectId;
	private Stock stockBySubjectId;
	private Cvterm cvterm;
	private String value;
	private int rank;
	private Set stockRelationshipCvterms = new HashSet(0);
	private Set stockRelationshipPubs = new HashSet(0);

	public StockRelationship() {
	}

	public StockRelationship(int stockRelationshipId, Stock stockByObjectId,
			Stock stockBySubjectId, Cvterm cvterm, int rank) {
		this.stockRelationshipId = stockRelationshipId;
		this.stockByObjectId = stockByObjectId;
		this.stockBySubjectId = stockBySubjectId;
		this.cvterm = cvterm;
		this.rank = rank;
	}

	public StockRelationship(int stockRelationshipId, Stock stockByObjectId,
			Stock stockBySubjectId, Cvterm cvterm, String value, int rank,
			Set stockRelationshipCvterms, Set stockRelationshipPubs) {
		this.stockRelationshipId = stockRelationshipId;
		this.stockByObjectId = stockByObjectId;
		this.stockBySubjectId = stockBySubjectId;
		this.cvterm = cvterm;
		this.value = value;
		this.rank = rank;
		this.stockRelationshipCvterms = stockRelationshipCvterms;
		this.stockRelationshipPubs = stockRelationshipPubs;
	}

	public int getStockRelationshipId() {
		return this.stockRelationshipId;
	}

	public void setStockRelationshipId(int stockRelationshipId) {
		this.stockRelationshipId = stockRelationshipId;
	}

	public Stock getStockByObjectId() {
		return this.stockByObjectId;
	}

	public void setStockByObjectId(Stock stockByObjectId) {
		this.stockByObjectId = stockByObjectId;
	}

	public Stock getStockBySubjectId() {
		return this.stockBySubjectId;
	}

	public void setStockBySubjectId(Stock stockBySubjectId) {
		this.stockBySubjectId = stockBySubjectId;
	}

	public Cvterm getCvterm() {
		return this.cvterm;
	}

	public void setCvterm(Cvterm cvterm) {
		this.cvterm = cvterm;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public int getRank() {
		return this.rank;
	}

	public void setRank(int rank) {
		this.rank = rank;
	}

	public Set getStockRelationshipCvterms() {
		return this.stockRelationshipCvterms;
	}

	public void setStockRelationshipCvterms(Set stockRelationshipCvterms) {
		this.stockRelationshipCvterms = stockRelationshipCvterms;
	}

	public Set getStockRelationshipPubs() {
		return this.stockRelationshipPubs;
	}

	public void setStockRelationshipPubs(Set stockRelationshipPubs) {
		this.stockRelationshipPubs = stockRelationshipPubs;
	}

}
