package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * StudyAssay generated by hbm2java
 */
public class StudyAssay implements java.io.Serializable {

	private int studyAssayId;
	private Study study;
	private Assay assay;

	public StudyAssay() {
	}

	public StudyAssay(int studyAssayId, Study study, Assay assay) {
		this.studyAssayId = studyAssayId;
		this.study = study;
		this.assay = assay;
	}

	public int getStudyAssayId() {
		return this.studyAssayId;
	}

	public void setStudyAssayId(int studyAssayId) {
		this.studyAssayId = studyAssayId;
	}

	public Study getStudy() {
		return this.study;
	}

	public void setStudy(Study study) {
		this.study = study;
	}

	public Assay getAssay() {
		return this.assay;
	}

	public void setAssay(Assay assay) {
		this.assay = assay;
	}

}
