package org.irri.iric.chado;

// Generated 05 26, 14 1:29:45 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Synonym generated by hbm2java
 */
public class Synonym implements java.io.Serializable {

	private int synonymId;
	private Cvterm cvterm;
	private String name;
	private String synonymSgml;
	private Set librarySynonyms = new HashSet(0);
	private Set featureSynonyms = new HashSet(0);
	private Set cellLineSynonyms = new HashSet(0);

	public Synonym() {
	}

	public Synonym(int synonymId, Cvterm cvterm, String name, String synonymSgml) {
		this.synonymId = synonymId;
		this.cvterm = cvterm;
		this.name = name;
		this.synonymSgml = synonymSgml;
	}

	public Synonym(int synonymId, Cvterm cvterm, String name,
			String synonymSgml, Set librarySynonyms, Set featureSynonyms,
			Set cellLineSynonyms) {
		this.synonymId = synonymId;
		this.cvterm = cvterm;
		this.name = name;
		this.synonymSgml = synonymSgml;
		this.librarySynonyms = librarySynonyms;
		this.featureSynonyms = featureSynonyms;
		this.cellLineSynonyms = cellLineSynonyms;
	}

	public int getSynonymId() {
		return this.synonymId;
	}

	public void setSynonymId(int synonymId) {
		this.synonymId = synonymId;
	}

	public Cvterm getCvterm() {
		return this.cvterm;
	}

	public void setCvterm(Cvterm cvterm) {
		this.cvterm = cvterm;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSynonymSgml() {
		return this.synonymSgml;
	}

	public void setSynonymSgml(String synonymSgml) {
		this.synonymSgml = synonymSgml;
	}

	public Set getLibrarySynonyms() {
		return this.librarySynonyms;
	}

	public void setLibrarySynonyms(Set librarySynonyms) {
		this.librarySynonyms = librarySynonyms;
	}

	public Set getFeatureSynonyms() {
		return this.featureSynonyms;
	}

	public void setFeatureSynonyms(Set featureSynonyms) {
		this.featureSynonyms = featureSynonyms;
	}

	public Set getCellLineSynonyms() {
		return this.cellLineSynonyms;
	}

	public void setCellLineSynonyms(Set cellLineSynonyms) {
		this.cellLineSynonyms = cellLineSynonyms;
	}

}
