package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ABoxType1 generated by hbm2java
 */
public class ABoxType1 implements java.io.Serializable {

	private ABoxType1Id id;

	public ABoxType1() {
	}

	public ABoxType1(ABoxType1Id id) {
		this.id = id;
	}

	public ABoxType1Id getId() {
		return this.id;
	}

	public void setId(ABoxType1Id id) {
		this.id = id;
	}

}
