package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * AdaptiveIsland generated by hbm2java
 */
public class AdaptiveIsland implements java.io.Serializable {

	private AdaptiveIslandId id;

	public AdaptiveIsland() {
	}

	public AdaptiveIsland(AdaptiveIslandId id) {
		this.id = id;
	}

	public AdaptiveIslandId getId() {
		return this.id;
	}

	public void setId(AdaptiveIslandId id) {
		this.id = id;
	}

}
