package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * AlanineTrnaPrimaryTranscript generated by hbm2java
 */
public class AlanineTrnaPrimaryTranscript implements java.io.Serializable {

	private AlanineTrnaPrimaryTranscriptId id;

	public AlanineTrnaPrimaryTranscript() {
	}

	public AlanineTrnaPrimaryTranscript(AlanineTrnaPrimaryTranscriptId id) {
		this.id = id;
	}

	public AlanineTrnaPrimaryTranscriptId getId() {
		return this.id;
	}

	public void setId(AlanineTrnaPrimaryTranscriptId id) {
		this.id = id;
	}

}
