package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * AllelicallyExcluded generated by hbm2java
 */
public class AllelicallyExcluded implements java.io.Serializable {

	private AllelicallyExcludedId id;

	public AllelicallyExcluded() {
	}

	public AllelicallyExcluded(AllelicallyExcludedId id) {
		this.id = id;
	}

	public AllelicallyExcludedId getId() {
		return this.id;
	}

	public void setId(AllelicallyExcludedId id) {
		this.id = id;
	}

}
