package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * AlphaHelix generated by hbm2java
 */
public class AlphaHelix implements java.io.Serializable {

	private AlphaHelixId id;

	public AlphaHelix() {
	}

	public AlphaHelix(AlphaHelixId id) {
		this.id = id;
	}

	public AlphaHelixId getId() {
		return this.id;
	}

	public void setId(AlphaHelixId id) {
		this.id = id;
	}

}
