package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * AlternativelySplicedTranscript generated by hbm2java
 */
public class AlternativelySplicedTranscript implements java.io.Serializable {

	private AlternativelySplicedTranscriptId id;

	public AlternativelySplicedTranscript() {
	}

	public AlternativelySplicedTranscript(AlternativelySplicedTranscriptId id) {
		this.id = id;
	}

	public AlternativelySplicedTranscriptId getId() {
		return this.id;
	}

	public void setId(AlternativelySplicedTranscriptId id) {
		this.id = id;
	}

}
