package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * AmbisenseSsrnaViralSequence generated by hbm2java
 */
public class AmbisenseSsrnaViralSequence implements java.io.Serializable {

	private AmbisenseSsrnaViralSequenceId id;

	public AmbisenseSsrnaViralSequence() {
	}

	public AmbisenseSsrnaViralSequence(AmbisenseSsrnaViralSequenceId id) {
		this.id = id;
	}

	public AmbisenseSsrnaViralSequenceId getId() {
		return this.id;
	}

	public void setId(AmbisenseSsrnaViralSequenceId id) {
		this.id = id;
	}

}
