package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * AminoAcidInsertion generated by hbm2java
 */
public class AminoAcidInsertion implements java.io.Serializable {

	private AminoAcidInsertionId id;

	public AminoAcidInsertion() {
	}

	public AminoAcidInsertion(AminoAcidInsertionId id) {
		this.id = id;
	}

	public AminoAcidInsertionId getId() {
		return this.id;
	}

	public void setId(AminoAcidInsertionId id) {
		this.id = id;
	}

}
