package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * AnnotationDirectedImprovedDraft generated by hbm2java
 */
public class AnnotationDirectedImprovedDraft implements java.io.Serializable {

	private AnnotationDirectedImprovedDraftId id;

	public AnnotationDirectedImprovedDraft() {
	}

	public AnnotationDirectedImprovedDraft(AnnotationDirectedImprovedDraftId id) {
		this.id = id;
	}

	public AnnotationDirectedImprovedDraftId getId() {
		return this.id;
	}

	public void setId(AnnotationDirectedImprovedDraftId id) {
		this.id = id;
	}

}
