package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Antisense generated by hbm2java
 */
public class Antisense implements java.io.Serializable {

	private AntisenseId id;

	public Antisense() {
	}

	public Antisense(AntisenseId id) {
		this.id = id;
	}

	public AntisenseId getId() {
		return this.id;
	}

	public void setId(AntisenseId id) {
		this.id = id;
	}

}
