package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ApicoplastSequence generated by hbm2java
 */
public class ApicoplastSequence implements java.io.Serializable {

	private ApicoplastSequenceId id;

	public ApicoplastSequence() {
	}

	public ApicoplastSequence(ApicoplastSequenceId id) {
		this.id = id;
	}

	public ApicoplastSequenceId getId() {
		return this.id;
	}

	public void setId(ApicoplastSequenceId id) {
		this.id = id;
	}

}
