package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Aptamer generated by hbm2java
 */
public class Aptamer implements java.io.Serializable {

	private AptamerId id;

	public Aptamer() {
	}

	public Aptamer(AptamerId id) {
		this.id = id;
	}

	public AptamerId getId() {
		return this.id;
	}

	public void setId(AptamerId id) {
		this.id = id;
	}

}
