package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Arginine generated by hbm2java
 */
public class Arginine implements java.io.Serializable {

	private ArginineId id;

	public Arginine() {
	}

	public Arginine(ArginineId id) {
		this.id = id;
	}

	public ArginineId getId() {
		return this.id;
	}

	public void setId(ArginineId id) {
		this.id = id;
	}

}
