package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ArginylTrna generated by hbm2java
 */
public class ArginylTrna implements java.io.Serializable {

	private ArginylTrnaId id;

	public ArginylTrna() {
	}

	public ArginylTrna(ArginylTrnaId id) {
		this.id = id;
	}

	public ArginylTrnaId getId() {
		return this.id;
	}

	public void setId(ArginylTrnaId id) {
		this.id = id;
	}

}
