package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Ars generated by hbm2java
 */
public class Ars implements java.io.Serializable {

	private ArsId id;

	public Ars() {
	}

	public Ars(ArsId id) {
		this.id = id;
	}

	public ArsId getId() {
		return this.id;
	}

	public void setId(ArsId id) {
		this.id = id;
	}

}
