package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Asparagine generated by hbm2java
 */
public class Asparagine implements java.io.Serializable {

	private AsparagineId id;

	public Asparagine() {
	}

	public Asparagine(AsparagineId id) {
		this.id = id;
	}

	public AsparagineId getId() {
		return this.id;
	}

	public void setId(AsparagineId id) {
		this.id = id;
	}

}
