package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * AsparaginylTrna generated by hbm2java
 */
public class AsparaginylTrna implements java.io.Serializable {

	private AsparaginylTrnaId id;

	public AsparaginylTrna() {
	}

	public AsparaginylTrna(AsparaginylTrnaId id) {
		this.id = id;
	}

	public AsparaginylTrnaId getId() {
		return this.id;
	}

	public void setId(AsparaginylTrnaId id) {
		this.id = id;
	}

}
