package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * AssortmentDerivedDeficiencyPlusDuplication generated by hbm2java
 */
public class AssortmentDerivedDeficiencyPlusDuplication implements
		java.io.Serializable {

	private AssortmentDerivedDeficiencyPlusDuplicationId id;

	public AssortmentDerivedDeficiencyPlusDuplication() {
	}

	public AssortmentDerivedDeficiencyPlusDuplication(
			AssortmentDerivedDeficiencyPlusDuplicationId id) {
		this.id = id;
	}

	public AssortmentDerivedDeficiencyPlusDuplicationId getId() {
		return this.id;
	}

	public void setId(AssortmentDerivedDeficiencyPlusDuplicationId id) {
		this.id = id;
	}

}
