package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * AssortmentDerivedAneuploid generated by hbm2java
 */
public class AssortmentDerivedAneuploid implements java.io.Serializable {

	private AssortmentDerivedAneuploidId id;

	public AssortmentDerivedAneuploid() {
	}

	public AssortmentDerivedAneuploid(AssortmentDerivedAneuploidId id) {
		this.id = id;
	}

	public AssortmentDerivedAneuploidId getId() {
		return this.id;
	}

	public void setId(AssortmentDerivedAneuploidId id) {
		this.id = id;
	}

}
