package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * AssortmentDerivedVariation generated by hbm2java
 */
public class AssortmentDerivedVariation implements java.io.Serializable {

	private AssortmentDerivedVariationId id;

	public AssortmentDerivedVariation() {
	}

	public AssortmentDerivedVariation(AssortmentDerivedVariationId id) {
		this.id = id;
	}

	public AssortmentDerivedVariationId getId() {
		return this.id;
	}

	public void setId(AssortmentDerivedVariationId id) {
		this.id = id;
	}

}
