package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * AsxTurnLeftHandedTypeOne generated by hbm2java
 */
public class AsxTurnLeftHandedTypeOne implements java.io.Serializable {

	private AsxTurnLeftHandedTypeOneId id;

	public AsxTurnLeftHandedTypeOne() {
	}

	public AsxTurnLeftHandedTypeOne(AsxTurnLeftHandedTypeOneId id) {
		this.id = id;
	}

	public AsxTurnLeftHandedTypeOneId getId() {
		return this.id;
	}

	public void setId(AsxTurnLeftHandedTypeOneId id) {
		this.id = id;
	}

}
