package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * AsymmetricRnaInternalLoop generated by hbm2java
 */
public class AsymmetricRnaInternalLoop implements java.io.Serializable {

	private AsymmetricRnaInternalLoopId id;

	public AsymmetricRnaInternalLoop() {
	}

	public AsymmetricRnaInternalLoop(AsymmetricRnaInternalLoopId id) {
		this.id = id;
	}

	public AsymmetricRnaInternalLoopId getId() {
		return this.id;
	}

	public void setId(AsymmetricRnaInternalLoopId id) {
		this.id = id;
	}

}
