package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * AttbSite generated by hbm2java
 */
public class AttbSite implements java.io.Serializable {

	private AttbSiteId id;

	public AttbSite() {
	}

	public AttbSite(AttbSiteId id) {
		this.id = id;
	}

	public AttbSiteId getId() {
		return this.id;
	}

	public void setId(AttbSiteId id) {
		this.id = id;
	}

}
