package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Bac generated by hbm2java
 */
public class Bac implements java.io.Serializable {

	private BacId id;

	public Bac() {
	}

	public Bac(BacId id) {
		this.id = id;
	}

	public BacId getId() {
		return this.id;
	}

	public void setId(BacId id) {
		this.id = id;
	}

}
