package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * BasePair generated by hbm2java
 */
public class BasePair implements java.io.Serializable {

	private BasePairId id;

	public BasePair() {
	}

	public BasePair(BasePairId id) {
		this.id = id;
	}

	public BasePairId getId() {
		return this.id;
	}

	public void setId(BasePairId id) {
		this.id = id;
	}

}
