package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * BetaTurnTypeSixAOne generated by hbm2java
 */
public class BetaTurnTypeSixAOne implements java.io.Serializable {

	private BetaTurnTypeSixAOneId id;

	public BetaTurnTypeSixAOne() {
	}

	public BetaTurnTypeSixAOne(BetaTurnTypeSixAOneId id) {
		this.id = id;
	}

	public BetaTurnTypeSixAOneId getId() {
		return this.id;
	}

	public void setId(BetaTurnTypeSixAOneId id) {
		this.id = id;
	}

}
