package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * BetaTurnLeftHandedTypeTwo generated by hbm2java
 */
public class BetaTurnLeftHandedTypeTwo implements java.io.Serializable {

	private BetaTurnLeftHandedTypeTwoId id;

	public BetaTurnLeftHandedTypeTwo() {
	}

	public BetaTurnLeftHandedTypeTwo(BetaTurnLeftHandedTypeTwoId id) {
		this.id = id;
	}

	public BetaTurnLeftHandedTypeTwoId getId() {
		return this.id;
	}

	public void setId(BetaTurnLeftHandedTypeTwoId id) {
		this.id = id;
	}

}
