package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * BetaBulgeLoopSix generated by hbm2java
 */
public class BetaBulgeLoopSix implements java.io.Serializable {

	private BetaBulgeLoopSixId id;

	public BetaBulgeLoopSix() {
	}

	public BetaBulgeLoopSix(BetaBulgeLoopSixId id) {
		this.id = id;
	}

	public BetaBulgeLoopSixId getId() {
		return this.id;
	}

	public void setId(BetaBulgeLoopSixId id) {
		this.id = id;
	}

}
