package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * BlockedReadingFrame generated by hbm2java
 */
public class BlockedReadingFrame implements java.io.Serializable {

	private BlockedReadingFrameId id;

	public BlockedReadingFrame() {
	}

	public BlockedReadingFrame(BlockedReadingFrameId id) {
		this.id = id;
	}

	public BlockedReadingFrameId getId() {
		return this.id;
	}

	public void setId(BlockedReadingFrameId id) {
		this.id = id;
	}

}
