package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * BluntEndRestrictionEnzymeCleavageSite generated by hbm2java
 */
public class BluntEndRestrictionEnzymeCleavageSite implements
		java.io.Serializable {

	private BluntEndRestrictionEnzymeCleavageSiteId id;

	public BluntEndRestrictionEnzymeCleavageSite() {
	}

	public BluntEndRestrictionEnzymeCleavageSite(
			BluntEndRestrictionEnzymeCleavageSiteId id) {
		this.id = id;
	}

	public BluntEndRestrictionEnzymeCleavageSiteId getId() {
		return this.id;
	}

	public void setId(BluntEndRestrictionEnzymeCleavageSiteId id) {
		this.id = id;
	}

}
