package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * BranchSite generated by hbm2java
 */
public class BranchSite implements java.io.Serializable {

	private BranchSiteId id;

	public BranchSite() {
	}

	public BranchSite(BranchSiteId id) {
		this.id = id;
	}

	public BranchSiteId getId() {
		return this.id;
	}

	public void setId(BranchSiteId id) {
		this.id = id;
	}

}
