package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * BredMotif generated by hbm2java
 */
public class BredMotif implements java.io.Serializable {

	private BredMotifId id;

	public BredMotif() {
	}

	public BredMotif(BredMotifId id) {
		this.id = id;
	}

	public BredMotifId getId() {
		return this.id;
	}

	public void setId(BredMotifId id) {
		this.id = id;
	}

}
