package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * BreuMotif generated by hbm2java
 */
public class BreuMotif implements java.io.Serializable {

	private BreuMotifId id;

	public BreuMotif() {
	}

	public BreuMotif(BreuMotifId id) {
		this.id = id;
	}

	public BreuMotifId getId() {
		return this.id;
	}

	public void setId(BreuMotifId id) {
		this.id = id;
	}

}
