package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * CanonicalThreePrimeSpliceSite generated by hbm2java
 */
public class CanonicalThreePrimeSpliceSite implements java.io.Serializable {

	private CanonicalThreePrimeSpliceSiteId id;

	public CanonicalThreePrimeSpliceSite() {
	}

	public CanonicalThreePrimeSpliceSite(CanonicalThreePrimeSpliceSiteId id) {
		this.id = id;
	}

	public CanonicalThreePrimeSpliceSiteId getId() {
		return this.id;
	}

	public void setId(CanonicalThreePrimeSpliceSiteId id) {
		this.id = id;
	}

}
