package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * CanonicalFivePrimeSpliceSite generated by hbm2java
 */
public class CanonicalFivePrimeSpliceSite implements java.io.Serializable {

	private CanonicalFivePrimeSpliceSiteId id;

	public CanonicalFivePrimeSpliceSite() {
	}

	public CanonicalFivePrimeSpliceSite(CanonicalFivePrimeSpliceSiteId id) {
		this.id = id;
	}

	public CanonicalFivePrimeSpliceSiteId getId() {
		return this.id;
	}

	public void setId(CanonicalFivePrimeSpliceSiteId id) {
		this.id = id;
	}

}
