package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Capped generated by hbm2java
 */
public class Capped implements java.io.Serializable {

	private CappedId id;

	public Capped() {
	}

	public Capped(CappedId id) {
		this.id = id;
	}

	public CappedId getId() {
		return this.id;
	}

	public void setId(CappedId id) {
		this.id = id;
	}

}
