package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * CassettePseudogene generated by hbm2java
 */
public class CassettePseudogene implements java.io.Serializable {

	private CassettePseudogeneId id;

	public CassettePseudogene() {
	}

	public CassettePseudogene(CassettePseudogeneId id) {
		this.id = id;
	}

	public CassettePseudogeneId getId() {
		return this.id;
	}

	public void setId(CassettePseudogeneId id) {
		this.id = id;
	}

}
