package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * CatmatRightHandedThree generated by hbm2java
 */
public class CatmatRightHandedThree implements java.io.Serializable {

	private CatmatRightHandedThreeId id;

	public CatmatRightHandedThree() {
	}

	public CatmatRightHandedThree(CatmatRightHandedThreeId id) {
		this.id = id;
	}

	public CatmatRightHandedThreeId getId() {
		return this.id;
	}

	public void setId(CatmatRightHandedThreeId id) {
		this.id = id;
	}

}
