package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * CdnaMatch generated by hbm2java
 */
public class CdnaMatch implements java.io.Serializable {

	private CdnaMatchId id;

	public CdnaMatch() {
	}

	public CdnaMatch(CdnaMatchId id) {
		this.id = id;
	}

	public CdnaMatchId getId() {
		return this.id;
	}

	public void setId(CdnaMatchId id) {
		this.id = id;
	}

}
