package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Cdna generated by hbm2java
 */
public class Cdna implements java.io.Serializable {

	private CdnaId id;

	public Cdna() {
	}

	public Cdna(CdnaId id) {
		this.id = id;
	}

	public CdnaId getId() {
		return this.id;
	}

	public void setId(CdnaId id) {
		this.id = id;
	}

}
