package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Cds generated by hbm2java
 */
public class Cds implements java.io.Serializable {

	private CdsId id;

	public Cds() {
	}

	public Cds(CdsId id) {
		this.id = id;
	}

	public CdsId getId() {
		return this.id;
	}

	public void setId(CdsId id) {
		this.id = id;
	}

}
