package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * CdsPredicted generated by hbm2java
 */
public class CdsPredicted implements java.io.Serializable {

	private CdsPredictedId id;

	public CdsPredicted() {
	}

	public CdsPredicted(CdsPredictedId id) {
		this.id = id;
	}

	public CdsPredictedId getId() {
		return this.id;
	}

	public void setId(CdsPredictedId id) {
		this.id = id;
	}

}
