package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * CentromereDnaElementIi generated by hbm2java
 */
public class CentromereDnaElementIi implements java.io.Serializable {

	private CentromereDnaElementIiId id;

	public CentromereDnaElementIi() {
	}

	public CentromereDnaElementIi(CentromereDnaElementIiId id) {
		this.id = id;
	}

	public CentromereDnaElementIiId getId() {
		return this.id;
	}

	public void setId(CentromereDnaElementIiId id) {
		this.id = id;
	}

}
