package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ChipSeqRegion generated by hbm2java
 */
public class ChipSeqRegion implements java.io.Serializable {

	private ChipSeqRegionId id;

	public ChipSeqRegion() {
	}

	public ChipSeqRegion(ChipSeqRegionId id) {
		this.id = id;
	}

	public ChipSeqRegionId getId() {
		return this.id;
	}

	public void setId(ChipSeqRegionId id) {
		this.id = id;
	}

}
