package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ChloroplastDna generated by hbm2java
 */
public class ChloroplastDna implements java.io.Serializable {

	private ChloroplastDnaId id;

	public ChloroplastDna() {
	}

	public ChloroplastDna(ChloroplastDnaId id) {
		this.id = id;
	}

	public ChloroplastDnaId getId() {
		return this.id;
	}

	public void setId(ChloroplastDnaId id) {
		this.id = id;
	}

}
