package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ChromosomalDeletion generated by hbm2java
 */
public class ChromosomalDeletion implements java.io.Serializable {

	private ChromosomalDeletionId id;

	public ChromosomalDeletion() {
	}

	public ChromosomalDeletion(ChromosomalDeletionId id) {
		this.id = id;
	}

	public ChromosomalDeletionId getId() {
		return this.id;
	}

	public void setId(ChromosomalDeletionId id) {
		this.id = id;
	}

}
