package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ChromosomePart generated by hbm2java
 */
public class ChromosomePart implements java.io.Serializable {

	private ChromosomePartId id;

	public ChromosomePart() {
	}

	public ChromosomePart(ChromosomePartId id) {
		this.id = id;
	}

	public ChromosomePartId getId() {
		return this.id;
	}

	public void setId(ChromosomePartId id) {
		this.id = id;
	}

}
