package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ChromosomalTranslocation generated by hbm2java
 */
public class ChromosomalTranslocation implements java.io.Serializable {

	private ChromosomalTranslocationId id;

	public ChromosomalTranslocation() {
	}

	public ChromosomalTranslocation(ChromosomalTranslocationId id) {
		this.id = id;
	}

	public ChromosomalTranslocationId getId() {
		return this.id;
	}

	public void setId(ChromosomalTranslocationId id) {
		this.id = id;
	}

}
