package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ChromosomalDuplication generated by hbm2java
 */
public class ChromosomalDuplication implements java.io.Serializable {

	private ChromosomalDuplicationId id;

	public ChromosomalDuplication() {
	}

	public ChromosomalDuplication(ChromosomalDuplicationId id) {
		this.id = id;
	}

	public ChromosomalDuplicationId getId() {
		return this.id;
	}

	public void setId(ChromosomalDuplicationId id) {
		this.id = id;
	}

}
