package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * CircularDoubleStrandedDnaChromosome generated by hbm2java
 */
public class CircularDoubleStrandedDnaChromosome implements
		java.io.Serializable {

	private CircularDoubleStrandedDnaChromosomeId id;

	public CircularDoubleStrandedDnaChromosome() {
	}

	public CircularDoubleStrandedDnaChromosome(
			CircularDoubleStrandedDnaChromosomeId id) {
		this.id = id;
	}

	public CircularDoubleStrandedDnaChromosomeId getId() {
		return this.id;
	}

	public void setId(CircularDoubleStrandedDnaChromosomeId id) {
		this.id = id;
	}

}
