package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * CisRegulatoryFrameshiftElement generated by hbm2java
 */
public class CisRegulatoryFrameshiftElement implements java.io.Serializable {

	private CisRegulatoryFrameshiftElementId id;

	public CisRegulatoryFrameshiftElement() {
	}

	public CisRegulatoryFrameshiftElement(CisRegulatoryFrameshiftElementId id) {
		this.id = id;
	}

	public CisRegulatoryFrameshiftElementId getId() {
		return this.id;
	}

	public void setId(CisRegulatoryFrameshiftElementId id) {
		this.id = id;
	}

}
