package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ClassIRna generated by hbm2java
 */
public class ClassIRna implements java.io.Serializable {

	private ClassIRnaId id;

	public ClassIRna() {
	}

	public ClassIRna(ClassIRnaId id) {
		this.id = id;
	}

	public ClassIRnaId getId() {
		return this.id;
	}

	public void setId(ClassIRnaId id) {
		this.id = id;
	}

}
