package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ClassIiRna generated by hbm2java
 */
public class ClassIiRna implements java.io.Serializable {

	private ClassIiRnaId id;

	public ClassIiRna() {
	}

	public ClassIiRna(ClassIiRnaId id) {
		this.id = id;
	}

	public ClassIiRnaId getId() {
		return this.id;
	}

	public void setId(ClassIiRnaId id) {
		this.id = id;
	}

}
