package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * CleavedForGpiAnchorRegion generated by hbm2java
 */
public class CleavedForGpiAnchorRegion implements java.io.Serializable {

	private CleavedForGpiAnchorRegionId id;

	public CleavedForGpiAnchorRegion() {
	}

	public CleavedForGpiAnchorRegion(CleavedForGpiAnchorRegionId id) {
		this.id = id;
	}

	public CleavedForGpiAnchorRegionId getId() {
		return this.id;
	}

	public void setId(CleavedForGpiAnchorRegionId id) {
		this.id = id;
	}

}
