package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * CloneInsertEnd generated by hbm2java
 */
public class CloneInsertEnd implements java.io.Serializable {

	private CloneInsertEndId id;

	public CloneInsertEnd() {
	}

	public CloneInsertEnd(CloneInsertEndId id) {
		this.id = id;
	}

	public CloneInsertEndId getId() {
		return this.id;
	}

	public void setId(CloneInsertEndId id) {
		this.id = id;
	}

}
