package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ClonedCdnaInsert generated by hbm2java
 */
public class ClonedCdnaInsert implements java.io.Serializable {

	private ClonedCdnaInsertId id;

	public ClonedCdnaInsert() {
	}

	public ClonedCdnaInsert(ClonedCdnaInsertId id) {
		this.id = id;
	}

	public ClonedCdnaInsertId getId() {
		return this.id;
	}

	public void setId(ClonedCdnaInsertId id) {
		this.id = id;
	}

}
