package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * CodingEnd generated by hbm2java
 */
public class CodingEnd implements java.io.Serializable {

	private CodingEndId id;

	public CodingEnd() {
	}

	public CodingEnd(CodingEndId id) {
		this.id = id;
	}

	public CodingEndId getId() {
		return this.id;
	}

	public void setId(CodingEndId id) {
		this.id = id;
	}

}
