package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * CointegratedPlasmid generated by hbm2java
 */
public class CointegratedPlasmid implements java.io.Serializable {

	private CointegratedPlasmidId id;

	public CointegratedPlasmid() {
	}

	public CointegratedPlasmid(CointegratedPlasmidId id) {
		this.id = id;
	}

	public CointegratedPlasmidId getId() {
		return this.id;
	}

	public void setId(CointegratedPlasmidId id) {
		this.id = id;
	}

}
