package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Complex3dStructuralVariant generated by hbm2java
 */
public class Complex3dStructuralVariant implements java.io.Serializable {

	private Complex3dStructuralVariantId id;

	public Complex3dStructuralVariant() {
	}

	public Complex3dStructuralVariant(Complex3dStructuralVariantId id) {
		this.id = id;
	}

	public Complex3dStructuralVariantId getId() {
		return this.id;
	}

	public void setId(Complex3dStructuralVariantId id) {
		this.id = id;
	}

}
