package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * CompositionallyBiasedRegionOfPeptide generated by hbm2java
 */
public class CompositionallyBiasedRegionOfPeptide implements
		java.io.Serializable {

	private CompositionallyBiasedRegionOfPeptideId id;

	public CompositionallyBiasedRegionOfPeptide() {
	}

	public CompositionallyBiasedRegionOfPeptide(
			CompositionallyBiasedRegionOfPeptideId id) {
		this.id = id;
	}

	public CompositionallyBiasedRegionOfPeptideId getId() {
		return this.id;
	}

	public void setId(CompositionallyBiasedRegionOfPeptideId id) {
		this.id = id;
	}

}
