package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ComplexStructuralAlteration generated by hbm2java
 */
public class ComplexStructuralAlteration implements java.io.Serializable {

	private ComplexStructuralAlterationId id;

	public ComplexStructuralAlteration() {
	}

	public ComplexStructuralAlteration(ComplexStructuralAlterationId id) {
		this.id = id;
	}

	public ComplexStructuralAlterationId getId() {
		return this.id;
	}

	public void setId(ComplexStructuralAlterationId id) {
		this.id = id;
	}

}
