package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ComplexChangeInTranscript generated by hbm2java
 */
public class ComplexChangeInTranscript implements java.io.Serializable {

	private ComplexChangeInTranscriptId id;

	public ComplexChangeInTranscript() {
	}

	public ComplexChangeInTranscript(ComplexChangeInTranscriptId id) {
		this.id = id;
	}

	public ComplexChangeInTranscriptId getId() {
		return this.id;
	}

	public void setId(ComplexChangeInTranscriptId id) {
		this.id = id;
	}

}
