package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Conserved generated by hbm2java
 */
public class Conserved implements java.io.Serializable {

	private ConservedId id;

	public Conserved() {
	}

	public Conserved(ConservedId id) {
		this.id = id;
	}

	public ConservedId getId() {
		return this.id;
	}

	public void setId(ConservedId id) {
		this.id = id;
	}

}
