package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ConsensusRegion generated by hbm2java
 */
public class ConsensusRegion implements java.io.Serializable {

	private ConsensusRegionId id;

	public ConsensusRegion() {
	}

	public ConsensusRegion(ConsensusRegionId id) {
		this.id = id;
	}

	public ConsensusRegionId getId() {
		return this.id;
	}

	public void setId(ConsensusRegionId id) {
		this.id = id;
	}

}
