package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ConsensusMrna generated by hbm2java
 */
public class ConsensusMrna implements java.io.Serializable {

	private ConsensusMrnaId id;

	public ConsensusMrna() {
	}

	public ConsensusMrna(ConsensusMrnaId id) {
		this.id = id;
	}

	public ConsensusMrnaId getId() {
		return this.id;
	}

	public void setId(ConsensusMrnaId id) {
		this.id = id;
	}

}
