package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ContigRead generated by hbm2java
 */
public class ContigRead implements java.io.Serializable {

	private ContigReadId id;

	public ContigRead() {
	}

	public ContigRead(ContigReadId id) {
		this.id = id;
	}

	public ContigReadId getId() {
		return this.id;
	}

	public void setId(ContigReadId id) {
		this.id = id;
	}

}
