package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ContigCollection generated by hbm2java
 */
public class ContigCollection implements java.io.Serializable {

	private ContigCollectionId id;

	public ContigCollection() {
	}

	public ContigCollection(ContigCollectionId id) {
		this.id = id;
	}

	public ContigCollectionId getId() {
		return this.id;
	}

	public void setId(ContigCollectionId id) {
		this.id = id;
	}

}
