package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Crm generated by hbm2java
 */
public class Crm implements java.io.Serializable {

	private CrmId id;

	public Crm() {
	}

	public Crm(CrmId id) {
		this.id = id;
	}

	public CrmId getId() {
		return this.id;
	}

	public void setId(CrmId id) {
		this.id = id;
	}

}
