package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * CrossGenomeMatch generated by hbm2java
 */
public class CrossGenomeMatch implements java.io.Serializable {

	private CrossGenomeMatchId id;

	public CrossGenomeMatch() {
	}

	public CrossGenomeMatch(CrossGenomeMatchId id) {
		this.id = id;
	}

	public CrossGenomeMatchId getId() {
		return this.id;
	}

	public void setId(CrossGenomeMatchId id) {
		this.id = id;
	}

}
