package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * CrypticProphage generated by hbm2java
 */
public class CrypticProphage implements java.io.Serializable {

	private CrypticProphageId id;

	public CrypticProphage() {
	}

	public CrypticProphage(CrypticProphageId id) {
		this.id = id;
	}

	public CrypticProphageId getId() {
		return this.id;
	}

	public void setId(CrypticProphageId id) {
		this.id = id;
	}

}
