package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * CToTTransitionAtPcpgSite generated by hbm2java
 */
public class CToTTransitionAtPcpgSite implements java.io.Serializable {

	private CToTTransitionAtPcpgSiteId id;

	public CToTTransitionAtPcpgSite() {
	}

	public CToTTransitionAtPcpgSite(CToTTransitionAtPcpgSiteId id) {
		this.id = id;
	}

	public CToTTransitionAtPcpgSiteId getId() {
		return this.id;
	}

	public void setId(CToTTransitionAtPcpgSiteId id) {
		this.id = id;
	}

}
