package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * CyanelleGene generated by hbm2java
 */
public class CyanelleGene implements java.io.Serializable {

	private CyanelleGeneId id;

	public CyanelleGene() {
	}

	public CyanelleGene(CyanelleGeneId id) {
		this.id = id;
	}

	public CyanelleGeneId getId() {
		return this.id;
	}

	public void setId(CyanelleGeneId id) {
		this.id = id;
	}

}
