package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * CyclicTranslocation generated by hbm2java
 */
public class CyclicTranslocation implements java.io.Serializable {

	private CyclicTranslocationId id;

	public CyclicTranslocation() {
	}

	public CyclicTranslocation(CyclicTranslocationId id) {
		this.id = id;
	}

	public CyclicTranslocationId getId() {
		return this.id;
	}

	public void setId(CyclicTranslocationId id) {
		this.id = id;
	}

}
