package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * CysteinylTrna generated by hbm2java
 */
public class CysteinylTrna implements java.io.Serializable {

	private CysteinylTrnaId id;

	public CysteinylTrna() {
	}

	public CysteinylTrna(CysteinylTrnaId id) {
		this.id = id;
	}

	public CysteinylTrnaId getId() {
		return this.id;
	}

	public void setId(CysteinylTrnaId id) {
		this.id = id;
	}

}
