package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * DceSiii generated by hbm2java
 */
public class DceSiii implements java.io.Serializable {

	private DceSiiiId id;

	public DceSiii() {
	}

	public DceSiii(DceSiiiId id) {
		this.id = id;
	}

	public DceSiiiId getId() {
		return this.id;
	}

	public void setId(DceSiiiId id) {
		this.id = id;
	}

}
