package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * DDjCCluster generated by hbm2java
 */
public class DDjCCluster implements java.io.Serializable {

	private DDjCClusterId id;

	public DDjCCluster() {
	}

	public DDjCCluster(DDjCClusterId id) {
		this.id = id;
	}

	public DDjCClusterId getId() {
		return this.id;
	}

	public void setId(DDjCClusterId id) {
		this.id = id;
	}

}
