package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * DecreasedTranslationalProductLevel generated by hbm2java
 */
public class DecreasedTranslationalProductLevel implements java.io.Serializable {

	private DecreasedTranslationalProductLevelId id;

	public DecreasedTranslationalProductLevel() {
	}

	public DecreasedTranslationalProductLevel(
			DecreasedTranslationalProductLevelId id) {
		this.id = id;
	}

	public DecreasedTranslationalProductLevelId getId() {
		return this.id;
	}

	public void setId(DecreasedTranslationalProductLevelId id) {
		this.id = id;
	}

}
