package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * DecreasedTranscriptStabilityVariant generated by hbm2java
 */
public class DecreasedTranscriptStabilityVariant implements
		java.io.Serializable {

	private DecreasedTranscriptStabilityVariantId id;

	public DecreasedTranscriptStabilityVariant() {
	}

	public DecreasedTranscriptStabilityVariant(
			DecreasedTranscriptStabilityVariantId id) {
		this.id = id;
	}

	public DecreasedTranscriptStabilityVariantId getId() {
		return this.id;
	}

	public void setId(DecreasedTranscriptStabilityVariantId id) {
		this.id = id;
	}

}
