package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * DeficientInversion generated by hbm2java
 */
public class DeficientInversion implements java.io.Serializable {

	private DeficientInversionId id;

	public DeficientInversion() {
	}

	public DeficientInversion(DeficientInversionId id) {
		this.id = id;
	}

	public DeficientInversionId getId() {
		return this.id;
	}

	public void setId(DeficientInversionId id) {
		this.id = id;
	}

}
