package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * DeletionBreakpoint generated by hbm2java
 */
public class DeletionBreakpoint implements java.io.Serializable {

	private DeletionBreakpointId id;

	public DeletionBreakpoint() {
	}

	public DeletionBreakpoint(DeletionBreakpointId id) {
		this.id = id;
	}

	public DeletionBreakpointId getId() {
		return this.id;
	}

	public void setId(DeletionBreakpointId id) {
		this.id = id;
	}

}
