package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * DIntrachrTransposition generated by hbm2java
 */
public class DIntrachrTransposition implements java.io.Serializable {

	private DIntrachrTranspositionId id;

	public DIntrachrTransposition() {
	}

	public DIntrachrTransposition(DIntrachrTranspositionId id) {
		this.id = id;
	}

	public DIntrachrTranspositionId getId() {
		return this.id;
	}

	public void setId(DIntrachrTranspositionId id) {
		this.id = id;
	}

}
