package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Diplotype generated by hbm2java
 */
public class Diplotype implements java.io.Serializable {

	private DiplotypeId id;

	public Diplotype() {
	}

	public Diplotype(DiplotypeId id) {
		this.id = id;
	}

	public DiplotypeId getId() {
		return this.id;
	}

	public void setId(DiplotypeId id) {
		this.id = id;
	}

}
