package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * DirectRepeat generated by hbm2java
 */
public class DirectRepeat implements java.io.Serializable {

	private DirectRepeatId id;

	public DirectRepeat() {
	}

	public DirectRepeat(DirectRepeatId id) {
		this.id = id;
	}

	public DirectRepeatId getId() {
		return this.id;
	}

	public void setId(DirectRepeatId id) {
		this.id = id;
	}

}
