package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * DispersedRepeat generated by hbm2java
 */
public class DispersedRepeat implements java.io.Serializable {

	private DispersedRepeatId id;

	public DispersedRepeat() {
	}

	public DispersedRepeat(DispersedRepeatId id) {
		this.id = id;
	}

	public DispersedRepeatId getId() {
		return this.id;
	}

	public void setId(DispersedRepeatId id) {
		this.id = id;
	}

}
