package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * DjCCluster generated by hbm2java
 */
public class DjCCluster implements java.io.Serializable {

	private DjCClusterId id;

	public DjCCluster() {
	}

	public DjCCluster(DjCClusterId id) {
		this.id = id;
	}

	public DjCClusterId getId() {
		return this.id;
	}

	public void setId(DjCClusterId id) {
		this.id = id;
	}

}
