package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Dmv4Motif generated by hbm2java
 */
public class Dmv4Motif implements java.io.Serializable {

	private Dmv4MotifId id;

	public Dmv4Motif() {
	}

	public Dmv4Motif(Dmv4MotifId id) {
		this.id = id;
	}

	public Dmv4MotifId getId() {
		return this.id;
	}

	public void setId(Dmv4MotifId id) {
		this.id = id;
	}

}
