package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * DnaAptamer generated by hbm2java
 */
public class DnaAptamer implements java.io.Serializable {

	private DnaAptamerId id;

	public DnaAptamer() {
	}

	public DnaAptamer(DnaAptamerId id) {
		this.id = id;
	}

	public DnaAptamerId getId() {
		return this.id;
	}

	public void setId(DnaAptamerId id) {
		this.id = id;
	}

}
