package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * DnaBindingSite generated by hbm2java
 */
public class DnaBindingSite implements java.io.Serializable {

	private DnaBindingSiteId id;

	public DnaBindingSite() {
	}

	public DnaBindingSite(DnaBindingSiteId id) {
		this.id = id;
	}

	public DnaBindingSiteId getId() {
		return this.id;
	}

	public void setId(DnaBindingSiteId id) {
		this.id = id;
	}

}
