package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * DnaTransposon generated by hbm2java
 */
public class DnaTransposon implements java.io.Serializable {

	private DnaTransposonId id;

	public DnaTransposon() {
	}

	public DnaTransposon(DnaTransposonId id) {
		this.id = id;
	}

	public DnaTransposonId getId() {
		return this.id;
	}

	public void setId(DnaTransposonId id) {
		this.id = id;
	}

}
