package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Double generated by hbm2java
 */
public class Double implements java.io.Serializable {

	private DoubleId id;

	public Double() {
	}

	public Double(DoubleId id) {
		this.id = id;
	}

	public DoubleId getId() {
		return this.id;
	}

	public void setId(DoubleId id) {
		this.id = id;
	}

}
