package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * DoubleStrandedCdna generated by hbm2java
 */
public class DoubleStrandedCdna implements java.io.Serializable {

	private DoubleStrandedCdnaId id;

	public DoubleStrandedCdna() {
	}

	public DoubleStrandedCdna(DoubleStrandedCdnaId id) {
		this.id = id;
	}

	public DoubleStrandedCdnaId getId() {
		return this.id;
	}

	public void setId(DoubleStrandedCdnaId id) {
		this.id = id;
	}

}
