package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * DownstreamGeneVariant generated by hbm2java
 */
public class DownstreamGeneVariant implements java.io.Serializable {

	private DownstreamGeneVariantId id;

	public DownstreamGeneVariant() {
	}

	public DownstreamGeneVariant(DownstreamGeneVariantId id) {
		this.id = id;
	}

	public DownstreamGeneVariantId getId() {
		return this.id;
	}

	public void setId(DownstreamGeneVariantId id) {
		this.id = id;
	}

}
