package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Dpe1Motif generated by hbm2java
 */
public class Dpe1Motif implements java.io.Serializable {

	private Dpe1MotifId id;

	public Dpe1Motif() {
	}

	public Dpe1Motif(Dpe1MotifId id) {
		this.id = id;
	}

	public Dpe1MotifId getId() {
		return this.id;
	}

	public void setId(Dpe1MotifId id) {
		this.id = id;
	}

}
