package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * DuplicatedPseudogene generated by hbm2java
 */
public class DuplicatedPseudogene implements java.io.Serializable {

	private DuplicatedPseudogeneId id;

	public DuplicatedPseudogene() {
	}

	public DuplicatedPseudogene(DuplicatedPseudogeneId id) {
		this.id = id;
	}

	public DuplicatedPseudogeneId getId() {
		return this.id;
	}

	public void setId(DuplicatedPseudogeneId id) {
		this.id = id;
	}

}
