package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditedTranscriptByAToISubstitution generated by hbm2java
 */
public class EditedTranscriptByAToISubstitution implements java.io.Serializable {

	private EditedTranscriptByAToISubstitutionId id;

	public EditedTranscriptByAToISubstitution() {
	}

	public EditedTranscriptByAToISubstitution(
			EditedTranscriptByAToISubstitutionId id) {
		this.id = id;
	}

	public EditedTranscriptByAToISubstitutionId getId() {
		return this.id;
	}

	public void setId(EditedTranscriptByAToISubstitutionId id) {
		this.id = id;
	}

}
