package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditedCds generated by hbm2java
 */
public class EditedCds implements java.io.Serializable {

	private EditedCdsId id;

	public EditedCds() {
	}

	public EditedCds(EditedCdsId id) {
		this.id = id;
	}

	public EditedCdsId getId() {
		return this.id;
	}

	public void setId(EditedCdsId id) {
		this.id = id;
	}

}
