package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * EditedMrna generated by hbm2java
 */
public class EditedMrna implements java.io.Serializable {

	private EditedMrnaId id;

	public EditedMrna() {
	}

	public EditedMrna(EditedMrnaId id) {
		this.id = id;
	}

	public EditedMrnaId getId() {
		return this.id;
	}

	public void setId(EditedMrnaId id) {
		this.id = id;
	}

}
