package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ElongatedPolypeptide generated by hbm2java
 */
public class ElongatedPolypeptide implements java.io.Serializable {

	private ElongatedPolypeptideId id;

	public ElongatedPolypeptide() {
	}

	public ElongatedPolypeptide(ElongatedPolypeptideId id) {
		this.id = id;
	}

	public ElongatedPolypeptideId getId() {
		return this.id;
	}

	public void setId(ElongatedPolypeptideId id) {
		this.id = id;
	}

}
