package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ElongatedInFramePolypeptideCTerminal generated by hbm2java
 */
public class ElongatedInFramePolypeptideCTerminal implements
		java.io.Serializable {

	private ElongatedInFramePolypeptideCTerminalId id;

	public ElongatedInFramePolypeptideCTerminal() {
	}

	public ElongatedInFramePolypeptideCTerminal(
			ElongatedInFramePolypeptideCTerminalId id) {
		this.id = id;
	}

	public ElongatedInFramePolypeptideCTerminalId getId() {
		return this.id;
	}

	public void setId(ElongatedInFramePolypeptideCTerminalId id) {
		this.id = id;
	}

}
