package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ElongatedInFramePolypeptideNTerminalElongation generated by hbm2java
 */
public class ElongatedInFramePolypeptideNTerminalElongation implements
		java.io.Serializable {

	private ElongatedInFramePolypeptideNTerminalElongationId id;

	public ElongatedInFramePolypeptideNTerminalElongation() {
	}

	public ElongatedInFramePolypeptideNTerminalElongation(
			ElongatedInFramePolypeptideNTerminalElongationId id) {
		this.id = id;
	}

	public ElongatedInFramePolypeptideNTerminalElongationId getId() {
		return this.id;
	}

	public void setId(ElongatedInFramePolypeptideNTerminalElongationId id) {
		this.id = id;
	}

}
