package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * EncodesOverlappingPeptidesDifferentStart generated by hbm2java
 */
public class EncodesOverlappingPeptidesDifferentStart implements
		java.io.Serializable {

	private EncodesOverlappingPeptidesDifferentStartId id;

	public EncodesOverlappingPeptidesDifferentStart() {
	}

	public EncodesOverlappingPeptidesDifferentStart(
			EncodesOverlappingPeptidesDifferentStartId id) {
		this.id = id;
	}

	public EncodesOverlappingPeptidesDifferentStartId getId() {
		return this.id;
	}

	public void setId(EncodesOverlappingPeptidesDifferentStartId id) {
		this.id = id;
	}

}
