package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * EncodesOverlappingPolypeptidesDifferentStartAndStop generated by hbm2java
 */
public class EncodesOverlappingPolypeptidesDifferentStartAndStop implements
		java.io.Serializable {

	private EncodesOverlappingPolypeptidesDifferentStartAndStopId id;

	public EncodesOverlappingPolypeptidesDifferentStartAndStop() {
	}

	public EncodesOverlappingPolypeptidesDifferentStartAndStop(
			EncodesOverlappingPolypeptidesDifferentStartAndStopId id) {
		this.id = id;
	}

	public EncodesOverlappingPolypeptidesDifferentStartAndStopId getId() {
		return this.id;
	}

	public void setId(EncodesOverlappingPolypeptidesDifferentStartAndStopId id) {
		this.id = id;
	}

}
