package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * EncodesAlternatelySplicedTranscripts generated by hbm2java
 */
public class EncodesAlternatelySplicedTranscripts implements
		java.io.Serializable {

	private EncodesAlternatelySplicedTranscriptsId id;

	public EncodesAlternatelySplicedTranscripts() {
	}

	public EncodesAlternatelySplicedTranscripts(
			EncodesAlternatelySplicedTranscriptsId id) {
		this.id = id;
	}

	public EncodesAlternatelySplicedTranscriptsId getId() {
		return this.id;
	}

	public void setId(EncodesAlternatelySplicedTranscriptsId id) {
		this.id = id;
	}

}
