package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * EngineeredEpisome generated by hbm2java
 */
public class EngineeredEpisome implements java.io.Serializable {

	private EngineeredEpisomeId id;

	public EngineeredEpisome() {
	}

	public EngineeredEpisome(EngineeredEpisomeId id) {
		this.id = id;
	}

	public EngineeredEpisomeId getId() {
		return this.id;
	}

	public void setId(EngineeredEpisomeId id) {
		this.id = id;
	}

}
