package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * EngineeredForeignRepetitiveElement generated by hbm2java
 */
public class EngineeredForeignRepetitiveElement implements java.io.Serializable {

	private EngineeredForeignRepetitiveElementId id;

	public EngineeredForeignRepetitiveElement() {
	}

	public EngineeredForeignRepetitiveElement(
			EngineeredForeignRepetitiveElementId id) {
		this.id = id;
	}

	public EngineeredForeignRepetitiveElementId getId() {
		return this.id;
	}

	public void setId(EngineeredForeignRepetitiveElementId id) {
		this.id = id;
	}

}
