package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * EngineeredInsert generated by hbm2java
 */
public class EngineeredInsert implements java.io.Serializable {

	private EngineeredInsertId id;

	public EngineeredInsert() {
	}

	public EngineeredInsert(EngineeredInsertId id) {
		this.id = id;
	}

	public EngineeredInsertId getId() {
		return this.id;
	}

	public void setId(EngineeredInsertId id) {
		this.id = id;
	}

}
