package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * EngineeredTransposableElement generated by hbm2java
 */
public class EngineeredTransposableElement implements java.io.Serializable {

	private EngineeredTransposableElementId id;

	public EngineeredTransposableElement() {
	}

	public EngineeredTransposableElement(EngineeredTransposableElementId id) {
		this.id = id;
	}

	public EngineeredTransposableElementId getId() {
		return this.id;
	}

	public void setId(EngineeredTransposableElementId id) {
		this.id = id;
	}

}
