package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * EngineeredFusionGene generated by hbm2java
 */
public class EngineeredFusionGene implements java.io.Serializable {

	private EngineeredFusionGeneId id;

	public EngineeredFusionGene() {
	}

	public EngineeredFusionGene(EngineeredFusionGeneId id) {
		this.id = id;
	}

	public EngineeredFusionGeneId getId() {
		return this.id;
	}

	public void setId(EngineeredFusionGeneId id) {
		this.id = id;
	}

}
