package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Engineered generated by hbm2java
 */
public class Engineered implements java.io.Serializable {

	private EngineeredId id;

	public Engineered() {
	}

	public Engineered(EngineeredId id) {
		this.id = id;
	}

	public EngineeredId getId() {
		return this.id;
	}

	public void setId(EngineeredId id) {
		this.id = id;
	}

}
