package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * EnhancerBindingSite generated by hbm2java
 */
public class EnhancerBindingSite implements java.io.Serializable {

	private EnhancerBindingSiteId id;

	public EnhancerBindingSite() {
	}

	public EnhancerBindingSite(EnhancerBindingSiteId id) {
		this.id = id;
	}

	public EnhancerBindingSiteId getId() {
		return this.id;
	}

	public void setId(EnhancerBindingSiteId id) {
		this.id = id;
	}

}
