package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Enhancer generated by hbm2java
 */
public class Enhancer implements java.io.Serializable {

	private EnhancerId id;

	public Enhancer() {
	}

	public Enhancer(EnhancerId id) {
		this.id = id;
	}

	public EnhancerId getId() {
		return this.id;
	}

	public void setId(EnhancerId id) {
		this.id = id;
	}

}
