package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * EnhancerTrapConstruct generated by hbm2java
 */
public class EnhancerTrapConstruct implements java.io.Serializable {

	private EnhancerTrapConstructId id;

	public EnhancerTrapConstruct() {
	}

	public EnhancerTrapConstruct(EnhancerTrapConstructId id) {
		this.id = id;
	}

	public EnhancerTrapConstructId getId() {
		return this.id;
	}

	public void setId(EnhancerTrapConstructId id) {
		this.id = id;
	}

}
