package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Enzymatic generated by hbm2java
 */
public class Enzymatic implements java.io.Serializable {

	private EnzymaticId id;

	public Enzymatic() {
	}

	public Enzymatic(EnzymaticId id) {
		this.id = id;
	}

	public EnzymaticId getId() {
		return this.id;
	}

	public void setId(EnzymaticId id) {
		this.id = id;
	}

}
