package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * EnzymaticRna generated by hbm2java
 */
public class EnzymaticRna implements java.io.Serializable {

	private EnzymaticRnaId id;

	public EnzymaticRna() {
	}

	public EnzymaticRna(EnzymaticRnaId id) {
		this.id = id;
	}

	public EnzymaticRnaId getId() {
		return this.id;
	}

	public void setId(EnzymaticRnaId id) {
		this.id = id;
	}

}
