package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * EpigeneticallyModifiedGene generated by hbm2java
 */
public class EpigeneticallyModifiedGene implements java.io.Serializable {

	private EpigeneticallyModifiedGeneId id;

	public EpigeneticallyModifiedGene() {
	}

	public EpigeneticallyModifiedGene(EpigeneticallyModifiedGeneId id) {
		this.id = id;
	}

	public EpigeneticallyModifiedGeneId getId() {
		return this.id;
	}

	public void setId(EpigeneticallyModifiedGeneId id) {
		this.id = id;
	}

}
