package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Episome generated by hbm2java
 */
public class Episome implements java.io.Serializable {

	private EpisomeId id;

	public Episome() {
	}

	public Episome(EpisomeId id) {
		this.id = id;
	}

	public EpisomeId getId() {
		return this.id;
	}

	public void setId(EpisomeId id) {
		this.id = id;
	}

}
