package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * EukaryoticTerminator generated by hbm2java
 */
public class EukaryoticTerminator implements java.io.Serializable {

	private EukaryoticTerminatorId id;

	public EukaryoticTerminator() {
	}

	public EukaryoticTerminator(EukaryoticTerminatorId id) {
		this.id = id;
	}

	public EukaryoticTerminatorId getId() {
		return this.id;
	}

	public void setId(EukaryoticTerminatorId id) {
		this.id = id;
	}

}
