package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ExonVariant generated by hbm2java
 */
public class ExonVariant implements java.io.Serializable {

	private ExonVariantId id;

	public ExonVariant() {
	}

	public ExonVariant(ExonVariantId id) {
		this.id = id;
	}

	public ExonVariantId getId() {
		return this.id;
	}

	public void setId(ExonVariantId id) {
		this.id = id;
	}

}
