package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ExonRegion generated by hbm2java
 */
public class ExonRegion implements java.io.Serializable {

	private ExonRegionId id;

	public ExonRegion() {
	}

	public ExonRegion(ExonRegionId id) {
		this.id = id;
	}

	public ExonRegionId getId() {
		return this.id;
	}

	public void setId(ExonRegionId id) {
		this.id = id;
	}

}
