package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ExonicSpliceEnhancer generated by hbm2java
 */
public class ExonicSpliceEnhancer implements java.io.Serializable {

	private ExonicSpliceEnhancerId id;

	public ExonicSpliceEnhancer() {
	}

	public ExonicSpliceEnhancer(ExonicSpliceEnhancerId id) {
		this.id = id;
	}

	public ExonicSpliceEnhancerId getId() {
		return this.id;
	}

	public void setId(ExonicSpliceEnhancerId id) {
		this.id = id;
	}

}
