package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ExperimentallyDefinedBindingRegion generated by hbm2java
 */
public class ExperimentallyDefinedBindingRegion implements java.io.Serializable {

	private ExperimentallyDefinedBindingRegionId id;

	public ExperimentallyDefinedBindingRegion() {
	}

	public ExperimentallyDefinedBindingRegion(
			ExperimentallyDefinedBindingRegionId id) {
		this.id = id;
	}

	public ExperimentallyDefinedBindingRegionId getId() {
		return this.id;
	}

	public void setId(ExperimentallyDefinedBindingRegionId id) {
		this.id = id;
	}

}
