package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ExpressedSequenceMatch generated by hbm2java
 */
public class ExpressedSequenceMatch implements java.io.Serializable {

	private ExpressedSequenceMatchId id;

	public ExpressedSequenceMatch() {
	}

	public ExpressedSequenceMatch(ExpressedSequenceMatchId id) {
		this.id = id;
	}

	public ExpressedSequenceMatchId getId() {
		return this.id;
	}

	public void setId(ExpressedSequenceMatchId id) {
		this.id = id;
	}

}
