package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * FeatureAttribute generated by hbm2java
 */
public class FeatureAttribute implements java.io.Serializable {

	private FeatureAttributeId id;

	public FeatureAttribute() {
	}

	public FeatureAttribute(FeatureAttributeId id) {
		this.id = id;
	}

	public FeatureAttributeId getId() {
		return this.id;
	}

	public void setId(FeatureAttributeId id) {
		this.id = id;
	}

}
