package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * FinishedGenome generated by hbm2java
 */
public class FinishedGenome implements java.io.Serializable {

	private FinishedGenomeId id;

	public FinishedGenome() {
	}

	public FinishedGenome(FinishedGenomeId id) {
		this.id = id;
	}

	public FinishedGenomeId getId() {
		return this.id;
	}

	public void setId(FinishedGenomeId id) {
		this.id = id;
	}

}
