package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * FiveCarboxymethyluridine generated by hbm2java
 */
public class FiveCarboxymethyluridine implements java.io.Serializable {

	private FiveCarboxymethyluridineId id;

	public FiveCarboxymethyluridine() {
	}

	public FiveCarboxymethyluridine(FiveCarboxymethyluridineId id) {
		this.id = id;
	}

	public FiveCarboxymethyluridineId getId() {
		return this.id;
	}

	public void setId(FiveCarboxymethyluridineId id) {
		this.id = id;
	}

}
