package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * FivePrimeUtrVariant generated by hbm2java
 */
public class FivePrimeUtrVariant implements java.io.Serializable {

	private FivePrimeUtrVariantId id;

	public FivePrimeUtrVariant() {
	}

	public FivePrimeUtrVariant(FivePrimeUtrVariantId id) {
		this.id = id;
	}

	public FivePrimeUtrVariantId getId() {
		return this.id;
	}

	public void setId(FivePrimeUtrVariantId id) {
		this.id = id;
	}

}
