package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * FiveMethylcytidine generated by hbm2java
 */
public class FiveMethylcytidine implements java.io.Serializable {

	private FiveMethylcytidineId id;

	public FiveMethylcytidine() {
	}

	public FiveMethylcytidine(FiveMethylcytidineId id) {
		this.id = id;
	}

	public FiveMethylcytidineId getId() {
		return this.id;
	}

	public void setId(FiveMethylcytidineId id) {
		this.id = id;
	}

}
