package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * FivePrimeDHeptamer generated by hbm2java
 */
public class FivePrimeDHeptamer implements java.io.Serializable {

	private FivePrimeDHeptamerId id;

	public FivePrimeDHeptamer() {
	}

	public FivePrimeDHeptamer(FivePrimeDHeptamerId id) {
		this.id = id;
	}

	public FivePrimeDHeptamerId getId() {
		return this.id;
	}

	public void setId(FivePrimeDHeptamerId id) {
		this.id = id;
	}

}
