package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * FiveMethoxycarbonylmethylTwoPrimeOMethyluridine generated by hbm2java
 */
public class FiveMethoxycarbonylmethylTwoPrimeOMethyluridine implements
		java.io.Serializable {

	private FiveMethoxycarbonylmethylTwoPrimeOMethyluridineId id;

	public FiveMethoxycarbonylmethylTwoPrimeOMethyluridine() {
	}

	public FiveMethoxycarbonylmethylTwoPrimeOMethyluridine(
			FiveMethoxycarbonylmethylTwoPrimeOMethyluridineId id) {
		this.id = id;
	}

	public FiveMethoxycarbonylmethylTwoPrimeOMethyluridineId getId() {
		return this.id;
	}

	public void setId(FiveMethoxycarbonylmethylTwoPrimeOMethyluridineId id) {
		this.id = id;
	}

}
