package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * FiveTaurinomethylTwoThiouridine generated by hbm2java
 */
public class FiveTaurinomethylTwoThiouridine implements java.io.Serializable {

	private FiveTaurinomethylTwoThiouridineId id;

	public FiveTaurinomethylTwoThiouridine() {
	}

	public FiveTaurinomethylTwoThiouridine(FiveTaurinomethylTwoThiouridineId id) {
		this.id = id;
	}

	public FiveTaurinomethylTwoThiouridineId getId() {
		return this.id;
	}

	public void setId(FiveTaurinomethylTwoThiouridineId id) {
		this.id = id;
	}

}
