package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * FiveFormylTwoPrimeOMethylcytidine generated by hbm2java
 */
public class FiveFormylTwoPrimeOMethylcytidine implements java.io.Serializable {

	private FiveFormylTwoPrimeOMethylcytidineId id;

	public FiveFormylTwoPrimeOMethylcytidine() {
	}

	public FiveFormylTwoPrimeOMethylcytidine(
			FiveFormylTwoPrimeOMethylcytidineId id) {
		this.id = id;
	}

	public FiveFormylTwoPrimeOMethylcytidineId getId() {
		return this.id;
	}

	public void setId(FiveFormylTwoPrimeOMethylcytidineId id) {
		this.id = id;
	}

}
