package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * FivePrimeCodingExonCodingRegion generated by hbm2java
 */
public class FivePrimeCodingExonCodingRegion implements java.io.Serializable {

	private FivePrimeCodingExonCodingRegionId id;

	public FivePrimeCodingExonCodingRegion() {
	}

	public FivePrimeCodingExonCodingRegion(FivePrimeCodingExonCodingRegionId id) {
		this.id = id;
	}

	public FivePrimeCodingExonCodingRegionId getId() {
		return this.id;
	}

	public void setId(FivePrimeCodingExonCodingRegionId id) {
		this.id = id;
	}

}
