package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * FivePrimeTerminalInvertedRepeat generated by hbm2java
 */
public class FivePrimeTerminalInvertedRepeat implements java.io.Serializable {

	private FivePrimeTerminalInvertedRepeatId id;

	public FivePrimeTerminalInvertedRepeat() {
	}

	public FivePrimeTerminalInvertedRepeat(FivePrimeTerminalInvertedRepeatId id) {
		this.id = id;
	}

	public FivePrimeTerminalInvertedRepeatId getId() {
		return this.id;
	}

	public void setId(FivePrimeTerminalInvertedRepeatId id) {
		this.id = id;
	}

}
