package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * FiveCarbamoylmethyluridine generated by hbm2java
 */
public class FiveCarbamoylmethyluridine implements java.io.Serializable {

	private FiveCarbamoylmethyluridineId id;

	public FiveCarbamoylmethyluridine() {
	}

	public FiveCarbamoylmethyluridine(FiveCarbamoylmethyluridineId id) {
		this.id = id;
	}

	public FiveCarbamoylmethyluridineId getId() {
		return this.id;
	}

	public void setId(FiveCarbamoylmethyluridineId id) {
		this.id = id;
	}

}
