package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * FiveHydroxymethylcytidine generated by hbm2java
 */
public class FiveHydroxymethylcytidine implements java.io.Serializable {

	private FiveHydroxymethylcytidineId id;

	public FiveHydroxymethylcytidine() {
	}

	public FiveHydroxymethylcytidine(FiveHydroxymethylcytidineId id) {
		this.id = id;
	}

	public FiveHydroxymethylcytidineId getId() {
		return this.id;
	}

	public void setId(FiveHydroxymethylcytidineId id) {
		this.id = id;
	}

}
