package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * FivePrimeLtrComponent generated by hbm2java
 */
public class FivePrimeLtrComponent implements java.io.Serializable {

	private FivePrimeLtrComponentId id;

	public FivePrimeLtrComponent() {
	}

	public FivePrimeLtrComponent(FivePrimeLtrComponentId id) {
		this.id = id;
	}

	public FivePrimeLtrComponentId getId() {
		return this.id;
	}

	public void setId(FivePrimeLtrComponentId id) {
		this.id = id;
	}

}
