package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * FivePrimeNoncodingExon generated by hbm2java
 */
public class FivePrimeNoncodingExon implements java.io.Serializable {

	private FivePrimeNoncodingExonId id;

	public FivePrimeNoncodingExon() {
	}

	public FivePrimeNoncodingExon(FivePrimeNoncodingExonId id) {
		this.id = id;
	}

	public FivePrimeNoncodingExonId getId() {
		return this.id;
	}

	public void setId(FivePrimeNoncodingExonId id) {
		this.id = id;
	}

}
