package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * FivePrimeLtr generated by hbm2java
 */
public class FivePrimeLtr implements java.io.Serializable {

	private FivePrimeLtrId id;

	public FivePrimeLtr() {
	}

	public FivePrimeLtr(FivePrimeLtrId id) {
		this.id = id;
	}

	public FivePrimeLtrId getId() {
		return this.id;
	}

	public void setId(FivePrimeLtrId id) {
		this.id = id;
	}

}
