package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * FivePrimeCodingExon generated by hbm2java
 */
public class FivePrimeCodingExon implements java.io.Serializable {

	private FivePrimeCodingExonId id;

	public FivePrimeCodingExon() {
	}

	public FivePrimeCodingExon(FivePrimeCodingExonId id) {
		this.id = id;
	}

	public FivePrimeCodingExonId getId() {
		return this.id;
	}

	public void setId(FivePrimeCodingExonId id) {
		this.id = id;
	}

}
