package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * FivePrimeCodingExonNoncodingRegion generated by hbm2java
 */
public class FivePrimeCodingExonNoncodingRegion implements java.io.Serializable {

	private FivePrimeCodingExonNoncodingRegionId id;

	public FivePrimeCodingExonNoncodingRegion() {
	}

	public FivePrimeCodingExonNoncodingRegion(
			FivePrimeCodingExonNoncodingRegionId id) {
		this.id = id;
	}

	public FivePrimeCodingExonNoncodingRegionId getId() {
		return this.id;
	}

	public void setId(FivePrimeCodingExonNoncodingRegionId id) {
		this.id = id;
	}

}
