package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * FiveHydroxyuridine generated by hbm2java
 */
public class FiveHydroxyuridine implements java.io.Serializable {

	private FiveHydroxyuridineId id;

	public FiveHydroxyuridine() {
	}

	public FiveHydroxyuridine(FiveHydroxyuridineId id) {
		this.id = id;
	}

	public FiveHydroxyuridineId getId() {
		return this.id;
	}

	public void setId(FiveHydroxyuridineId id) {
		this.id = id;
	}

}
