package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * FivePrimeDRecombinationSignalSequence generated by hbm2java
 */
public class FivePrimeDRecombinationSignalSequence implements
		java.io.Serializable {

	private FivePrimeDRecombinationSignalSequenceId id;

	public FivePrimeDRecombinationSignalSequence() {
	}

	public FivePrimeDRecombinationSignalSequence(
			FivePrimeDRecombinationSignalSequenceId id) {
		this.id = id;
	}

	public FivePrimeDRecombinationSignalSequenceId getId() {
		return this.id;
	}

	public void setId(FivePrimeDRecombinationSignalSequenceId id) {
		this.id = id;
	}

}
