package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * FivePrimeCisSpliceSite generated by hbm2java
 */
public class FivePrimeCisSpliceSite implements java.io.Serializable {

	private FivePrimeCisSpliceSiteId id;

	public FivePrimeCisSpliceSite() {
	}

	public FivePrimeCisSpliceSite(FivePrimeCisSpliceSiteId id) {
		this.id = id;
	}

	public FivePrimeCisSpliceSiteId getId() {
		return this.id;
	}

	public void setId(FivePrimeCisSpliceSiteId id) {
		this.id = id;
	}

}
