package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * FivePrimeUtr generated by hbm2java
 */
public class FivePrimeUtr implements java.io.Serializable {

	private FivePrimeUtrId id;

	public FivePrimeUtr() {
	}

	public FivePrimeUtr(FivePrimeUtrId id) {
		this.id = id;
	}

	public FivePrimeUtrId getId() {
		return this.id;
	}

	public void setId(FivePrimeUtrId id) {
		this.id = id;
	}

}
