package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * FiveIsopentenylaminomethylTwoThiouridine generated by hbm2java
 */
public class FiveIsopentenylaminomethylTwoThiouridine implements
		java.io.Serializable {

	private FiveIsopentenylaminomethylTwoThiouridineId id;

	public FiveIsopentenylaminomethylTwoThiouridine() {
	}

	public FiveIsopentenylaminomethylTwoThiouridine(
			FiveIsopentenylaminomethylTwoThiouridineId id) {
		this.id = id;
	}

	public FiveIsopentenylaminomethylTwoThiouridineId getId() {
		return this.id;
	}

	public void setId(FiveIsopentenylaminomethylTwoThiouridineId id) {
		this.id = id;
	}

}
