package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Floxed generated by hbm2java
 */
public class Floxed implements java.io.Serializable {

	private FloxedId id;

	public Floxed() {
	}

	public Floxed(FloxedId id) {
		this.id = id;
	}

	public FloxedId getId() {
		return this.id;
	}

	public void setId(FloxedId id) {
		this.id = id;
	}

}
