package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ForeignGene generated by hbm2java
 */
public class ForeignGene implements java.io.Serializable {

	private ForeignGeneId id;

	public ForeignGene() {
	}

	public ForeignGene(ForeignGeneId id) {
		this.id = id;
	}

	public ForeignGeneId getId() {
		return this.id;
	}

	public void setId(ForeignGeneId id) {
		this.id = id;
	}

}
