package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ForwardPrimer generated by hbm2java
 */
public class ForwardPrimer implements java.io.Serializable {

	private ForwardPrimerId id;

	public ForwardPrimer() {
	}

	public ForwardPrimer(ForwardPrimerId id) {
		this.id = id;
	}

	public ForwardPrimerId getId() {
		return this.id;
	}

	public void setId(ForwardPrimerId id) {
		this.id = id;
	}

}
