package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Fragmentary generated by hbm2java
 */
public class Fragmentary implements java.io.Serializable {

	private FragmentaryId id;

	public Fragmentary() {
	}

	public Fragmentary(FragmentaryId id) {
		this.id = id;
	}

	public FragmentaryId getId() {
		return this.id;
	}

	public void setId(FragmentaryId id) {
		this.id = id;
	}

}
