package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * FrameRestoringVariant generated by hbm2java
 */
public class FrameRestoringVariant implements java.io.Serializable {

	private FrameRestoringVariantId id;

	public FrameRestoringVariant() {
	}

	public FrameRestoringVariant(FrameRestoringVariantId id) {
		this.id = id;
	}

	public FrameRestoringVariantId getId() {
		return this.id;
	}

	public void setId(FrameRestoringVariantId id) {
		this.id = id;
	}

}
