package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * FreeDuplication generated by hbm2java
 */
public class FreeDuplication implements java.io.Serializable {

	private FreeDuplicationId id;

	public FreeDuplication() {
	}

	public FreeDuplication(FreeDuplicationId id) {
		this.id = id;
	}

	public FreeDuplicationId getId() {
		return this.id;
	}

	public void setId(FreeDuplicationId id) {
		this.id = id;
	}

}
