package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * FrtSite generated by hbm2java
 */
public class FrtSite implements java.io.Serializable {

	private FrtSiteId id;

	public FrtSite() {
	}

	public FrtSite(FrtSiteId id) {
		this.id = id;
	}

	public FrtSiteId getId() {
		return this.id;
	}

	public void setId(FrtSiteId id) {
		this.id = id;
	}

}
