package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * GagaMotif generated by hbm2java
 */
public class GagaMotif implements java.io.Serializable {

	private GagaMotifId id;

	public GagaMotif() {
	}

	public GagaMotif(GagaMotifId id) {
		this.id = id;
	}

	public GagaMotifId getId() {
		return this.id;
	}

	public void setId(GagaMotifId id) {
		this.id = id;
	}

}
