package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * GalactosylQueuosine generated by hbm2java
 */
public class GalactosylQueuosine implements java.io.Serializable {

	private GalactosylQueuosineId id;

	public GalactosylQueuosine() {
	}

	public GalactosylQueuosine(GalactosylQueuosineId id) {
		this.id = id;
	}

	public GalactosylQueuosineId getId() {
		return this.id;
	}

	public void setId(GalactosylQueuosineId id) {
		this.id = id;
	}

}
