package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * GammaTurn generated by hbm2java
 */
public class GammaTurn implements java.io.Serializable {

	private GammaTurnId id;

	public GammaTurn() {
	}

	public GammaTurn(GammaTurnId id) {
		this.id = id;
	}

	public GammaTurnId getId() {
		return this.id;
	}

	public void setId(GammaTurnId id) {
		this.id = id;
	}

}
