package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * GammaTurnClassic generated by hbm2java
 */
public class GammaTurnClassic implements java.io.Serializable {

	private GammaTurnClassicId id;

	public GammaTurnClassic() {
	}

	public GammaTurnClassic(GammaTurnClassicId id) {
		this.id = id;
	}

	public GammaTurnClassicId getId() {
		return this.id;
	}

	public void setId(GammaTurnClassicId id) {
		this.id = id;
	}

}
