package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * GammaTurnInverse generated by hbm2java
 */
public class GammaTurnInverse implements java.io.Serializable {

	private GammaTurnInverseId id;

	public GammaTurnInverse() {
	}

	public GammaTurnInverse(GammaTurnInverseId id) {
		this.id = id;
	}

	public GammaTurnInverseId getId() {
		return this.id;
	}

	public void setId(GammaTurnInverseId id) {
		this.id = id;
	}

}
