package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Gap generated by hbm2java
 */
public class Gap implements java.io.Serializable {

	private GapId id;

	public Gap() {
	}

	public Gap(GapId id) {
		this.id = id;
	}

	public GapId getId() {
		return this.id;
	}

	public void setId(GapId id) {
		this.id = id;
	}

}
