package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Gene generated by hbm2java
 */
public class Gene implements java.io.Serializable {

	private GeneId id;

	public Gene() {
	}

	public Gene(GeneId id) {
		this.id = id;
	}

	public GeneId getId() {
		return this.id;
	}

	public void setId(GeneId id) {
		this.id = id;
	}

}
