package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * GeneSubarray generated by hbm2java
 */
public class GeneSubarray implements java.io.Serializable {

	private GeneSubarrayId id;

	public GeneSubarray() {
	}

	public GeneSubarray(GeneSubarrayId id) {
		this.id = id;
	}

	public GeneSubarrayId getId() {
		return this.id;
	}

	public void setId(GeneSubarrayId id) {
		this.id = id;
	}

}
