package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * GeneAttribute generated by hbm2java
 */
public class GeneAttribute implements java.io.Serializable {

	private GeneAttributeId id;

	public GeneAttribute() {
	}

	public GeneAttribute(GeneAttributeId id) {
		this.id = id;
	}

	public GeneAttributeId getId() {
		return this.id;
	}

	public void setId(GeneAttributeId id) {
		this.id = id;
	}

}
