package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * GeneticMarker generated by hbm2java
 */
public class GeneticMarker implements java.io.Serializable {

	private GeneticMarkerId id;

	public GeneticMarker() {
	}

	public GeneticMarker(GeneticMarkerId id) {
		this.id = id;
	}

	public GeneticMarkerId getId() {
		return this.id;
	}

	public void setId(GeneticMarkerId id) {
		this.id = id;
	}

}
