package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * GeneRearrangedAtDnaLevel generated by hbm2java
 */
public class GeneRearrangedAtDnaLevel implements java.io.Serializable {

	private GeneRearrangedAtDnaLevelId id;

	public GeneRearrangedAtDnaLevel() {
	}

	public GeneRearrangedAtDnaLevel(GeneRearrangedAtDnaLevelId id) {
		this.id = id;
	}

	public GeneRearrangedAtDnaLevelId getId() {
		return this.id;
	}

	public void setId(GeneRearrangedAtDnaLevelId id) {
		this.id = id;
	}

}
