package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * GeneGroup generated by hbm2java
 */
public class GeneGroup implements java.io.Serializable {

	private GeneGroupId id;

	public GeneGroup() {
	}

	public GeneGroup(GeneGroupId id) {
		this.id = id;
	}

	public GeneGroupId getId() {
		return this.id;
	}

	public void setId(GeneGroupId id) {
		this.id = id;
	}

}
