package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * GeneSegment generated by hbm2java
 */
public class GeneSegment implements java.io.Serializable {

	private GeneSegmentId id;

	public GeneSegment() {
	}

	public GeneSegment(GeneSegmentId id) {
		this.id = id;
	}

	public GeneSegmentId getId() {
		return this.id;
	}

	public void setId(GeneSegmentId id) {
		this.id = id;
	}

}
