package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * GeneWithEditedTranscript generated by hbm2java
 */
public class GeneWithEditedTranscript implements java.io.Serializable {

	private GeneWithEditedTranscriptId id;

	public GeneWithEditedTranscript() {
	}

	public GeneWithEditedTranscript(GeneWithEditedTranscriptId id) {
		this.id = id;
	}

	public GeneWithEditedTranscriptId getId() {
		return this.id;
	}

	public void setId(GeneWithEditedTranscriptId id) {
		this.id = id;
	}

}
