package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * GeneWithStopCodonRedefinedAsSelenocysteine generated by hbm2java
 */
public class GeneWithStopCodonRedefinedAsSelenocysteine implements
		java.io.Serializable {

	private GeneWithStopCodonRedefinedAsSelenocysteineId id;

	public GeneWithStopCodonRedefinedAsSelenocysteine() {
	}

	public GeneWithStopCodonRedefinedAsSelenocysteine(
			GeneWithStopCodonRedefinedAsSelenocysteineId id) {
		this.id = id;
	}

	public GeneWithStopCodonRedefinedAsSelenocysteineId getId() {
		return this.id;
	}

	public void setId(GeneWithStopCodonRedefinedAsSelenocysteineId id) {
		this.id = id;
	}

}
