package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * GeneWithTransSplicedTranscript generated by hbm2java
 */
public class GeneWithTransSplicedTranscript implements java.io.Serializable {

	private GeneWithTransSplicedTranscriptId id;

	public GeneWithTransSplicedTranscript() {
	}

	public GeneWithTransSplicedTranscript(GeneWithTransSplicedTranscriptId id) {
		this.id = id;
	}

	public GeneWithTransSplicedTranscriptId getId() {
		return this.id;
	}

	public void setId(GeneWithTransSplicedTranscriptId id) {
		this.id = id;
	}

}
