package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * GeneSilencedByHistoneModification generated by hbm2java
 */
public class GeneSilencedByHistoneModification implements java.io.Serializable {

	private GeneSilencedByHistoneModificationId id;

	public GeneSilencedByHistoneModification() {
	}

	public GeneSilencedByHistoneModification(
			GeneSilencedByHistoneModificationId id) {
		this.id = id;
	}

	public GeneSilencedByHistoneModificationId getId() {
		return this.id;
	}

	public void setId(GeneSilencedByHistoneModificationId id) {
		this.id = id;
	}

}
