package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * GeneSilencedByDnaMethylation generated by hbm2java
 */
public class GeneSilencedByDnaMethylation implements java.io.Serializable {

	private GeneSilencedByDnaMethylationId id;

	public GeneSilencedByDnaMethylation() {
	}

	public GeneSilencedByDnaMethylation(GeneSilencedByDnaMethylationId id) {
		this.id = id;
	}

	public GeneSilencedByDnaMethylationId getId() {
		return this.id;
	}

	public void setId(GeneSilencedByDnaMethylationId id) {
		this.id = id;
	}

}
