package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * GeneWithTranscriptWithTranslationalFrameshift generated by hbm2java
 */
public class GeneWithTranscriptWithTranslationalFrameshift implements
		java.io.Serializable {

	private GeneWithTranscriptWithTranslationalFrameshiftId id;

	public GeneWithTranscriptWithTranslationalFrameshift() {
	}

	public GeneWithTranscriptWithTranslationalFrameshift(
			GeneWithTranscriptWithTranslationalFrameshiftId id) {
		this.id = id;
	}

	public GeneWithTranscriptWithTranslationalFrameshiftId getId() {
		return this.id;
	}

	public void setId(GeneWithTranscriptWithTranslationalFrameshiftId id) {
		this.id = id;
	}

}
