package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * GenomicIsland generated by hbm2java
 */
public class GenomicIsland implements java.io.Serializable {

	private GenomicIslandId id;

	public GenomicIsland() {
	}

	public GenomicIsland(GenomicIslandId id) {
		this.id = id;
	}

	public GenomicIslandId getId() {
		return this.id;
	}

	public void setId(GenomicIslandId id) {
		this.id = id;
	}

}
