package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * GlutamicAcidTrnaPrimaryTranscript generated by hbm2java
 */
public class GlutamicAcidTrnaPrimaryTranscript implements java.io.Serializable {

	private GlutamicAcidTrnaPrimaryTranscriptId id;

	public GlutamicAcidTrnaPrimaryTranscript() {
	}

	public GlutamicAcidTrnaPrimaryTranscript(
			GlutamicAcidTrnaPrimaryTranscriptId id) {
		this.id = id;
	}

	public GlutamicAcidTrnaPrimaryTranscriptId getId() {
		return this.id;
	}

	public void setId(GlutamicAcidTrnaPrimaryTranscriptId id) {
		this.id = id;
	}

}
