package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * GlutamicAcid generated by hbm2java
 */
public class GlutamicAcid implements java.io.Serializable {

	private GlutamicAcidId id;

	public GlutamicAcid() {
	}

	public GlutamicAcid(GlutamicAcidId id) {
		this.id = id;
	}

	public GlutamicAcidId getId() {
		return this.id;
	}

	public void setId(GlutamicAcidId id) {
		this.id = id;
	}

}
