package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * GlycineTrnaPrimaryTranscript generated by hbm2java
 */
public class GlycineTrnaPrimaryTranscript implements java.io.Serializable {

	private GlycineTrnaPrimaryTranscriptId id;

	public GlycineTrnaPrimaryTranscript() {
	}

	public GlycineTrnaPrimaryTranscript(GlycineTrnaPrimaryTranscriptId id) {
		this.id = id;
	}

	public GlycineTrnaPrimaryTranscriptId getId() {
		return this.id;
	}

	public void setId(GlycineTrnaPrimaryTranscriptId id) {
		this.id = id;
	}

}
