package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * GoldenPath generated by hbm2java
 */
public class GoldenPath implements java.io.Serializable {

	private GoldenPathId id;

	public GoldenPath() {
	}

	public GoldenPath(GoldenPathId id) {
		this.id = id;
	}

	public GoldenPathId getId() {
		return this.id;
	}

	public void setId(GoldenPathId id) {
		this.id = id;
	}

}
