package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * GrnaGene generated by hbm2java
 */
public class GrnaGene implements java.io.Serializable {

	private GrnaGeneId id;

	public GrnaGene() {
	}

	public GrnaGene(GrnaGeneId id) {
		this.id = id;
	}

	public GrnaGeneId getId() {
		return this.id;
	}

	public void setId(GrnaGeneId id) {
		this.id = id;
	}

}
