package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * GrnaEncoding generated by hbm2java
 */
public class GrnaEncoding implements java.io.Serializable {

	private GrnaEncodingId id;

	public GrnaEncoding() {
	}

	public GrnaEncoding(GrnaEncodingId id) {
		this.id = id;
	}

	public GrnaEncodingId getId() {
		return this.id;
	}

	public void setId(GrnaEncodingId id) {
		this.id = id;
	}

}
