package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * GroupIibIntron generated by hbm2java
 */
public class GroupIibIntron implements java.io.Serializable {

	private GroupIibIntronId id;

	public GroupIibIntron() {
	}

	public GroupIibIntron(GroupIibIntronId id) {
		this.id = id;
	}

	public GroupIibIntronId getId() {
		return this.id;
	}

	public void setId(GroupIibIntronId id) {
		this.id = id;
	}

}
