package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * GroupIiaIntron generated by hbm2java
 */
public class GroupIiaIntron implements java.io.Serializable {

	private GroupIiaIntronId id;

	public GroupIiaIntron() {
	}

	public GroupIiaIntron(GroupIiaIntronId id) {
		this.id = id;
	}

	public GroupIiaIntronId getId() {
		return this.id;
	}

	public void setId(GroupIiaIntronId id) {
		this.id = id;
	}

}
