package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * GroupIiIntron generated by hbm2java
 */
public class GroupIiIntron implements java.io.Serializable {

	private GroupIiIntronId id;

	public GroupIiIntron() {
	}

	public GroupIiIntron(GroupIiIntronId id) {
		this.id = id;
	}

	public GroupIiIntronId getId() {
		return this.id;
	}

	public void setId(GroupIiIntronId id) {
		this.id = id;
	}

}
