package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * GToTTransversion generated by hbm2java
 */
public class GToTTransversion implements java.io.Serializable {

	private GToTTransversionId id;

	public GToTTransversion() {
	}

	public GToTTransversion(GToTTransversionId id) {
		this.id = id;
	}

	public GToTTransversionId getId() {
		return this.id;
	}

	public void setId(GToTTransversionId id) {
		this.id = id;
	}

}
