package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * H3k14AcetylationSite generated by hbm2java
 */
public class H3k14AcetylationSite implements java.io.Serializable {

	private H3k14AcetylationSiteId id;

	public H3k14AcetylationSite() {
	}

	public H3k14AcetylationSite(H3k14AcetylationSiteId id) {
		this.id = id;
	}

	public H3k14AcetylationSiteId getId() {
		return this.id;
	}

	public void setId(H3k14AcetylationSiteId id) {
		this.id = id;
	}

}
