package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * H3k36MethylationSite generated by hbm2java
 */
public class H3k36MethylationSite implements java.io.Serializable {

	private H3k36MethylationSiteId id;

	public H3k36MethylationSite() {
	}

	public H3k36MethylationSite(H3k36MethylationSiteId id) {
		this.id = id;
	}

	public H3k36MethylationSiteId getId() {
		return this.id;
	}

	public void setId(H3k36MethylationSiteId id) {
		this.id = id;
	}

}
