package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * H3k36DimethylationSite generated by hbm2java
 */
public class H3k36DimethylationSite implements java.io.Serializable {

	private H3k36DimethylationSiteId id;

	public H3k36DimethylationSite() {
	}

	public H3k36DimethylationSite(H3k36DimethylationSiteId id) {
		this.id = id;
	}

	public H3k36DimethylationSiteId getId() {
		return this.id;
	}

	public void setId(H3k36DimethylationSiteId id) {
		this.id = id;
	}

}
