package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * H3k4Trimethylation generated by hbm2java
 */
public class H3k4Trimethylation implements java.io.Serializable {

	private H3k4TrimethylationId id;

	public H3k4Trimethylation() {
	}

	public H3k4Trimethylation(H3k4TrimethylationId id) {
		this.id = id;
	}

	public H3k4TrimethylationId getId() {
		return this.id;
	}

	public void setId(H3k4TrimethylationId id) {
		this.id = id;
	}

}
