package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * H3k4DimethylationSite generated by hbm2java
 */
public class H3k4DimethylationSite implements java.io.Serializable {

	private H3k4DimethylationSiteId id;

	public H3k4DimethylationSite() {
	}

	public H3k4DimethylationSite(H3k4DimethylationSiteId id) {
		this.id = id;
	}

	public H3k4DimethylationSiteId getId() {
		return this.id;
	}

	public void setId(H3k4DimethylationSiteId id) {
		this.id = id;
	}

}
