package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * H3k4MonomethylationSite generated by hbm2java
 */
public class H3k4MonomethylationSite implements java.io.Serializable {

	private H3k4MonomethylationSiteId id;

	public H3k4MonomethylationSite() {
	}

	public H3k4MonomethylationSite(H3k4MonomethylationSiteId id) {
		this.id = id;
	}

	public H3k4MonomethylationSiteId getId() {
		return this.id;
	}

	public void setId(H3k4MonomethylationSiteId id) {
		this.id = id;
	}

}
