package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * H3k79MonomethylationSite generated by hbm2java
 */
public class H3k79MonomethylationSite implements java.io.Serializable {

	private H3k79MonomethylationSiteId id;

	public H3k79MonomethylationSite() {
	}

	public H3k79MonomethylationSite(H3k79MonomethylationSiteId id) {
		this.id = id;
	}

	public H3k79MonomethylationSiteId getId() {
		return this.id;
	}

	public void setId(H3k79MonomethylationSiteId id) {
		this.id = id;
	}

}
