package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * H3k9MonomethylationSite generated by hbm2java
 */
public class H3k9MonomethylationSite implements java.io.Serializable {

	private H3k9MonomethylationSiteId id;

	public H3k9MonomethylationSite() {
	}

	public H3k9MonomethylationSite(H3k9MonomethylationSiteId id) {
		this.id = id;
	}

	public H3k9MonomethylationSiteId getId() {
		return this.id;
	}

	public void setId(H3k9MonomethylationSiteId id) {
		this.id = id;
	}

}
