package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * H3k9AcetylationSite generated by hbm2java
 */
public class H3k9AcetylationSite implements java.io.Serializable {

	private H3k9AcetylationSiteId id;

	public H3k9AcetylationSite() {
	}

	public H3k9AcetylationSite(H3k9AcetylationSiteId id) {
		this.id = id;
	}

	public H3k9AcetylationSiteId getId() {
		return this.id;
	}

	public void setId(H3k9AcetylationSiteId id) {
		this.id = id;
	}

}
