package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * H3k9MethylationSite generated by hbm2java
 */
public class H3k9MethylationSite implements java.io.Serializable {

	private H3k9MethylationSiteId id;

	public H3k9MethylationSite() {
	}

	public H3k9MethylationSite(H3k9MethylationSiteId id) {
		this.id = id;
	}

	public H3k9MethylationSiteId getId() {
		return this.id;
	}

	public void setId(H3k9MethylationSiteId id) {
		this.id = id;
	}

}
