package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * H4k5AcylationSite generated by hbm2java
 */
public class H4k5AcylationSite implements java.io.Serializable {

	private H4k5AcylationSiteId id;

	public H4k5AcylationSite() {
	}

	public H4k5AcylationSite(H4k5AcylationSiteId id) {
		this.id = id;
	}

	public H4k5AcylationSiteId getId() {
		return this.id;
	}

	public void setId(H4k5AcylationSiteId id) {
		this.id = id;
	}

}
