package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Helitron generated by hbm2java
 */
public class Helitron implements java.io.Serializable {

	private HelitronId id;

	public Helitron() {
	}

	public Helitron(HelitronId id) {
		this.id = id;
	}

	public HelitronId getId() {
		return this.id;
	}

	public void setId(HelitronId id) {
		this.id = id;
	}

}
