package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * HeritablePhenotypicMarker generated by hbm2java
 */
public class HeritablePhenotypicMarker implements java.io.Serializable {

	private HeritablePhenotypicMarkerId id;

	public HeritablePhenotypicMarker() {
	}

	public HeritablePhenotypicMarker(HeritablePhenotypicMarkerId id) {
		this.id = id;
	}

	public HeritablePhenotypicMarkerId getId() {
		return this.id;
	}

	public void setId(HeritablePhenotypicMarkerId id) {
		this.id = id;
	}

}
