package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * HistoneAcetylationSite generated by hbm2java
 */
public class HistoneAcetylationSite implements java.io.Serializable {

	private HistoneAcetylationSiteId id;

	public HistoneAcetylationSite() {
	}

	public HistoneAcetylationSite(HistoneAcetylationSiteId id) {
		this.id = id;
	}

	public HistoneAcetylationSiteId getId() {
		return this.id;
	}

	public void setId(HistoneAcetylationSiteId id) {
		this.id = id;
	}

}
