package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * HistoneMethylationSite generated by hbm2java
 */
public class HistoneMethylationSite implements java.io.Serializable {

	private HistoneMethylationSiteId id;

	public HistoneMethylationSite() {
	}

	public HistoneMethylationSite(HistoneMethylationSiteId id) {
		this.id = id;
	}

	public HistoneMethylationSiteId getId() {
		return this.id;
	}

	public void setId(HistoneMethylationSiteId id) {
		this.id = id;
	}

}
