package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * HomologousRegion generated by hbm2java
 */
public class HomologousRegion implements java.io.Serializable {

	private HomologousRegionId id;

	public HomologousRegion() {
	}

	public HomologousRegion(HomologousRegionId id) {
		this.id = id;
	}

	public HomologousRegionId getId() {
		return this.id;
	}

	public void setId(HomologousRegionId id) {
		this.id = id;
	}

}
