package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * HoogsteenBasePair generated by hbm2java
 */
public class HoogsteenBasePair implements java.io.Serializable {

	private HoogsteenBasePairId id;

	public HoogsteenBasePair() {
	}

	public HoogsteenBasePair(HoogsteenBasePairId id) {
		this.id = id;
	}

	public HoogsteenBasePairId getId() {
		return this.id;
	}

	public void setId(HoogsteenBasePairId id) {
		this.id = id;
	}

}
