package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * HPseudoknot generated by hbm2java
 */
public class HPseudoknot implements java.io.Serializable {

	private HPseudoknotId id;

	public HPseudoknot() {
	}

	public HPseudoknot(HPseudoknotId id) {
		this.id = id;
	}

	public HPseudoknotId getId() {
		return this.id;
	}

	public void setId(HPseudoknotId id) {
		this.id = id;
	}

}
