package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Imprinted generated by hbm2java
 */
public class Imprinted implements java.io.Serializable {

	private ImprintedId id;

	public Imprinted() {
	}

	public Imprinted(ImprintedId id) {
		this.id = id;
	}

	public ImprintedId getId() {
		return this.id;
	}

	public void setId(ImprintedId id) {
		this.id = id;
	}

}
