package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * InactiveLigandBindingSite generated by hbm2java
 */
public class InactiveLigandBindingSite implements java.io.Serializable {

	private InactiveLigandBindingSiteId id;

	public InactiveLigandBindingSite() {
	}

	public InactiveLigandBindingSite(InactiveLigandBindingSiteId id) {
		this.id = id;
	}

	public InactiveLigandBindingSiteId getId() {
		return this.id;
	}

	public void setId(InactiveLigandBindingSiteId id) {
		this.id = id;
	}

}
