package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * InitiatorCodonChange generated by hbm2java
 */
public class InitiatorCodonChange implements java.io.Serializable {

	private InitiatorCodonChangeId id;

	public InitiatorCodonChange() {
	}

	public InitiatorCodonChange(InitiatorCodonChangeId id) {
		this.id = id;
	}

	public InitiatorCodonChangeId getId() {
		return this.id;
	}

	public void setId(InitiatorCodonChangeId id) {
		this.id = id;
	}

}
