package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Inr1Motif generated by hbm2java
 */
public class Inr1Motif implements java.io.Serializable {

	private Inr1MotifId id;

	public Inr1Motif() {
	}

	public Inr1Motif(Inr1MotifId id) {
		this.id = id;
	}

	public Inr1MotifId getId() {
		return this.id;
	}

	public void setId(Inr1MotifId id) {
		this.id = id;
	}

}
