package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Insertional generated by hbm2java
 */
public class Insertional implements java.io.Serializable {

	private InsertionalId id;

	public Insertional() {
	}

	public Insertional(InsertionalId id) {
		this.id = id;
	}

	public InsertionalId getId() {
		return this.id;
	}

	public void setId(InsertionalId id) {
		this.id = id;
	}

}
