package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * InsertionAttribute generated by hbm2java
 */
public class InsertionAttribute implements java.io.Serializable {

	private InsertionAttributeId id;

	public InsertionAttribute() {
	}

	public InsertionAttribute(InsertionAttributeId id) {
		this.id = id;
	}

	public InsertionAttributeId getId() {
		return this.id;
	}

	public void setId(InsertionAttributeId id) {
		this.id = id;
	}

}
