package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * InsideIntronAntiparallel generated by hbm2java
 */
public class InsideIntronAntiparallel implements java.io.Serializable {

	private InsideIntronAntiparallelId id;

	public InsideIntronAntiparallel() {
	}

	public InsideIntronAntiparallel(InsideIntronAntiparallelId id) {
		this.id = id;
	}

	public InsideIntronAntiparallelId getId() {
		return this.id;
	}

	public void setId(InsideIntronAntiparallelId id) {
		this.id = id;
	}

}
