package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Interband generated by hbm2java
 */
public class Interband implements java.io.Serializable {

	private InterbandId id;

	public Interband() {
	}

	public Interband(InterbandId id) {
		this.id = id;
	}

	public InterbandId getId() {
		return this.id;
	}

	public void setId(InterbandId id) {
		this.id = id;
	}

}
