package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * InternalGuideSequence generated by hbm2java
 */
public class InternalGuideSequence implements java.io.Serializable {

	private InternalGuideSequenceId id;

	public InternalGuideSequence() {
	}

	public InternalGuideSequence(InternalGuideSequenceId id) {
		this.id = id;
	}

	public InternalGuideSequenceId getId() {
		return this.id;
	}

	public void setId(InternalGuideSequenceId id) {
		this.id = id;
	}

}
