package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Integron generated by hbm2java
 */
public class Integron implements java.io.Serializable {

	private IntegronId id;

	public Integron() {
	}

	public Integron(IntegronId id) {
		this.id = id;
	}

	public IntegronId getId() {
		return this.id;
	}

	public void setId(IntegronId id) {
		this.id = id;
	}

}
