package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * InternalRibosomeEntrySite generated by hbm2java
 */
public class InternalRibosomeEntrySite implements java.io.Serializable {

	private InternalRibosomeEntrySiteId id;

	public InternalRibosomeEntrySite() {
	}

	public InternalRibosomeEntrySite(InternalRibosomeEntrySiteId id) {
		this.id = id;
	}

	public InternalRibosomeEntrySiteId getId() {
		return this.id;
	}

	public void setId(InternalRibosomeEntrySiteId id) {
		this.id = id;
	}

}
