package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * IntegratedMobileGeneticElement generated by hbm2java
 */
public class IntegratedMobileGeneticElement implements java.io.Serializable {

	private IntegratedMobileGeneticElementId id;

	public IntegratedMobileGeneticElement() {
	}

	public IntegratedMobileGeneticElement(IntegratedMobileGeneticElementId id) {
		this.id = id;
	}

	public IntegratedMobileGeneticElementId getId() {
		return this.id;
	}

	public void setId(IntegratedMobileGeneticElementId id) {
		this.id = id;
	}

}
