package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * InteriorExon generated by hbm2java
 */
public class InteriorExon implements java.io.Serializable {

	private InteriorExonId id;

	public InteriorExon() {
	}

	public InteriorExon(InteriorExonId id) {
		this.id = id;
	}

	public InteriorExonId getId() {
		return this.id;
	}

	public void setId(InteriorExonId id) {
		this.id = id;
	}

}
