package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * InternalUtr generated by hbm2java
 */
public class InternalUtr implements java.io.Serializable {

	private InternalUtrId id;

	public InternalUtr() {
	}

	public InternalUtr(InternalUtrId id) {
		this.id = id;
	}

	public InternalUtrId getId() {
		return this.id;
	}

	public void setId(InternalUtrId id) {
		this.id = id;
	}

}
