package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * InterchromosomalDuplication generated by hbm2java
 */
public class InterchromosomalDuplication implements java.io.Serializable {

	private InterchromosomalDuplicationId id;

	public InterchromosomalDuplication() {
	}

	public InterchromosomalDuplication(InterchromosomalDuplicationId id) {
		this.id = id;
	}

	public InterchromosomalDuplicationId getId() {
		return this.id;
	}

	public void setId(InterchromosomalDuplicationId id) {
		this.id = id;
	}

}
