package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * IntronVariant generated by hbm2java
 */
public class IntronVariant implements java.io.Serializable {

	private IntronVariantId id;

	public IntronVariant() {
	}

	public IntronVariant(IntronVariantId id) {
		this.id = id;
	}

	public IntronVariantId getId() {
		return this.id;
	}

	public void setId(IntronVariantId id) {
		this.id = id;
	}

}
