package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * IntrachromosomalMutation generated by hbm2java
 */
public class IntrachromosomalMutation implements java.io.Serializable {

	private IntrachromosomalMutationId id;

	public IntrachromosomalMutation() {
	}

	public IntrachromosomalMutation(IntrachromosomalMutationId id) {
		this.id = id;
	}

	public IntrachromosomalMutationId getId() {
		return this.id;
	}

	public void setId(IntrachromosomalMutationId id) {
		this.id = id;
	}

}
