package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * IntronDomain generated by hbm2java
 */
public class IntronDomain implements java.io.Serializable {

	private IntronDomainId id;

	public IntronDomain() {
	}

	public IntronDomain(IntronDomainId id) {
		this.id = id;
	}

	public IntronDomainId getId() {
		return this.id;
	}

	public void setId(IntronDomainId id) {
		this.id = id;
	}

}
