package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * InvalidatedByGenomicContamination generated by hbm2java
 */
public class InvalidatedByGenomicContamination implements java.io.Serializable {

	private InvalidatedByGenomicContaminationId id;

	public InvalidatedByGenomicContamination() {
	}

	public InvalidatedByGenomicContamination(
			InvalidatedByGenomicContaminationId id) {
		this.id = id;
	}

	public InvalidatedByGenomicContaminationId getId() {
		return this.id;
	}

	public void setId(InvalidatedByGenomicContaminationId id) {
		this.id = id;
	}

}
