package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * InvalidatedByPartialProcessing generated by hbm2java
 */
public class InvalidatedByPartialProcessing implements java.io.Serializable {

	private InvalidatedByPartialProcessingId id;

	public InvalidatedByPartialProcessing() {
	}

	public InvalidatedByPartialProcessing(InvalidatedByPartialProcessingId id) {
		this.id = id;
	}

	public InvalidatedByPartialProcessingId getId() {
		return this.id;
	}

	public void setId(InvalidatedByPartialProcessingId id) {
		this.id = id;
	}

}
