package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * InvertInterTransposition generated by hbm2java
 */
public class InvertInterTransposition implements java.io.Serializable {

	private InvertInterTranspositionId id;

	public InvertInterTransposition() {
	}

	public InvertInterTransposition(InvertInterTranspositionId id) {
		this.id = id;
	}

	public InvertInterTranspositionId getId() {
		return this.id;
	}

	public void setId(InvertInterTranspositionId id) {
		this.id = id;
	}

}
