package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * InversionSitePart generated by hbm2java
 */
public class InversionSitePart implements java.io.Serializable {

	private InversionSitePartId id;

	public InversionSitePart() {
	}

	public InversionSitePart(InversionSitePartId id) {
		this.id = id;
	}

	public InversionSitePartId getId() {
		return this.id;
	}

	public void setId(InversionSitePartId id) {
		this.id = id;
	}

}
