package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * InversionDerivedDeficiencyPlusDuplication generated by hbm2java
 */
public class InversionDerivedDeficiencyPlusDuplication implements
		java.io.Serializable {

	private InversionDerivedDeficiencyPlusDuplicationId id;

	public InversionDerivedDeficiencyPlusDuplication() {
	}

	public InversionDerivedDeficiencyPlusDuplication(
			InversionDerivedDeficiencyPlusDuplicationId id) {
		this.id = id;
	}

	public InversionDerivedDeficiencyPlusDuplicationId getId() {
		return this.id;
	}

	public void setId(InversionDerivedDeficiencyPlusDuplicationId id) {
		this.id = id;
	}

}
