package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Inversion generated by hbm2java
 */
public class Inversion implements java.io.Serializable {

	private InversionId id;

	public Inversion() {
	}

	public Inversion(InversionId id) {
		this.id = id;
	}

	public InversionId getId() {
		return this.id;
	}

	public void setId(InversionId id) {
		this.id = id;
	}

}
