package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * InvertedInsertionalDuplication generated by hbm2java
 */
public class InvertedInsertionalDuplication implements java.io.Serializable {

	private InvertedInsertionalDuplicationId id;

	public InvertedInsertionalDuplication() {
	}

	public InvertedInsertionalDuplication(InvertedInsertionalDuplicationId id) {
		this.id = id;
	}

	public InvertedInsertionalDuplicationId getId() {
		return this.id;
	}

	public void setId(InvertedInsertionalDuplicationId id) {
		this.id = id;
	}

}
