package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * InvertedRepeat generated by hbm2java
 */
public class InvertedRepeat implements java.io.Serializable {

	private InvertedRepeatId id;

	public InvertedRepeat() {
	}

	public InvertedRepeat(InvertedRepeatId id) {
		this.id = id;
	}

	public InvertedRepeatId getId() {
		return this.id;
	}

	public void setId(InvertedRepeatId id) {
		this.id = id;
	}

}
