package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * InversionDerivedBipartiteDuplication generated by hbm2java
 */
public class InversionDerivedBipartiteDuplication implements
		java.io.Serializable {

	private InversionDerivedBipartiteDuplicationId id;

	public InversionDerivedBipartiteDuplication() {
	}

	public InversionDerivedBipartiteDuplication(
			InversionDerivedBipartiteDuplicationId id) {
		this.id = id;
	}

	public InversionDerivedBipartiteDuplicationId getId() {
		return this.id;
	}

	public void setId(InversionDerivedBipartiteDuplicationId id) {
		this.id = id;
	}

}
