package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * IrlinvSite generated by hbm2java
 */
public class IrlinvSite implements java.io.Serializable {

	private IrlinvSiteId id;

	public IrlinvSite() {
	}

	public IrlinvSite(IrlinvSiteId id) {
		this.id = id;
	}

	public IrlinvSiteId getId() {
		return this.id;
	}

	public void setId(IrlinvSiteId id) {
		this.id = id;
	}

}
