package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * JCCluster generated by hbm2java
 */
public class JCCluster implements java.io.Serializable {

	private JCClusterId id;

	public JCCluster() {
	}

	public JCCluster(JCClusterId id) {
		this.id = id;
	}

	public JCClusterId getId() {
		return this.id;
	}

	public void setId(JCClusterId id) {
		this.id = id;
	}

}
