package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * JNonamer generated by hbm2java
 */
public class JNonamer implements java.io.Serializable {

	private JNonamerId id;

	public JNonamer() {
	}

	public JNonamer(JNonamerId id) {
		this.id = id;
	}

	public JNonamerId getId() {
		return this.id;
	}

	public void setId(JNonamerId id) {
		this.id = id;
	}

}
