package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * JSpacer generated by hbm2java
 */
public class JSpacer implements java.io.Serializable {

	private JSpacerId id;

	public JSpacer() {
	}

	public JSpacer(JSpacerId id) {
		this.id = id;
	}

	public JSpacerId getId() {
		return this.id;
	}

	public void setId(JSpacerId id) {
		this.id = id;
	}

}
