package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * LaevosynapticChromosome generated by hbm2java
 */
public class LaevosynapticChromosome implements java.io.Serializable {

	private LaevosynapticChromosomeId id;

	public LaevosynapticChromosome() {
	}

	public LaevosynapticChromosome(LaevosynapticChromosomeId id) {
		this.id = id;
	}

	public LaevosynapticChromosomeId getId() {
		return this.id;
	}

	public void setId(LaevosynapticChromosomeId id) {
		this.id = id;
	}

}
