package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * LambdaVector generated by hbm2java
 */
public class LambdaVector implements java.io.Serializable {

	private LambdaVectorId id;

	public LambdaVector() {
	}

	public LambdaVector(LambdaVectorId id) {
		this.id = id;
	}

	public LambdaVectorId getId() {
		return this.id;
	}

	public void setId(LambdaVectorId id) {
		this.id = id;
	}

}
