package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * LeftHandedPeptideHelix generated by hbm2java
 */
public class LeftHandedPeptideHelix implements java.io.Serializable {

	private LeftHandedPeptideHelixId id;

	public LeftHandedPeptideHelix() {
	}

	public LeftHandedPeptideHelix(LeftHandedPeptideHelixId id) {
		this.id = id;
	}

	public LeftHandedPeptideHelixId getId() {
		return this.id;
	}

	public void setId(LeftHandedPeptideHelixId id) {
		this.id = id;
	}

}
