package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * LeucoplastGene generated by hbm2java
 */
public class LeucoplastGene implements java.io.Serializable {

	private LeucoplastGeneId id;

	public LeucoplastGene() {
	}

	public LeucoplastGene(LeucoplastGeneId id) {
		this.id = id;
	}

	public LeucoplastGeneId getId() {
		return this.id;
	}

	public void setId(LeucoplastGeneId id) {
		this.id = id;
	}

}
