package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * LeucineTrnaPrimaryTranscript generated by hbm2java
 */
public class LeucineTrnaPrimaryTranscript implements java.io.Serializable {

	private LeucineTrnaPrimaryTranscriptId id;

	public LeucineTrnaPrimaryTranscript() {
	}

	public LeucineTrnaPrimaryTranscript(LeucineTrnaPrimaryTranscriptId id) {
		this.id = id;
	}

	public LeucineTrnaPrimaryTranscriptId getId() {
		return this.id;
	}

	public void setId(LeucineTrnaPrimaryTranscriptId id) {
		this.id = id;
	}

}
