package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * LevelOfTranscriptVariant generated by hbm2java
 */
public class LevelOfTranscriptVariant implements java.io.Serializable {

	private LevelOfTranscriptVariantId id;

	public LevelOfTranscriptVariant() {
	}

	public LevelOfTranscriptVariant(LevelOfTranscriptVariantId id) {
		this.id = id;
	}

	public LevelOfTranscriptVariantId getId() {
		return this.id;
	}

	public void setId(LevelOfTranscriptVariantId id) {
		this.id = id;
	}

}
