package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * LigandBindingSite generated by hbm2java
 */
public class LigandBindingSite implements java.io.Serializable {

	private LigandBindingSiteId id;

	public LigandBindingSite() {
	}

	public LigandBindingSite(LigandBindingSiteId id) {
		this.id = id;
	}

	public LigandBindingSiteId getId() {
		return this.id;
	}

	public void setId(LigandBindingSiteId id) {
		this.id = id;
	}

}
