package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * LnaOligo generated by hbm2java
 */
public class LnaOligo implements java.io.Serializable {

	private LnaOligoId id;

	public LnaOligo() {
	}

	public LnaOligo(LnaOligoId id) {
		this.id = id;
	}

	public LnaOligoId getId() {
		return this.id;
	}

	public void setId(LnaOligoId id) {
		this.id = id;
	}

}
