package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * LossOfHeterozygosity generated by hbm2java
 */
public class LossOfHeterozygosity implements java.io.Serializable {

	private LossOfHeterozygosityId id;

	public LossOfHeterozygosity() {
	}

	public LossOfHeterozygosity(LossOfHeterozygosityId id) {
		this.id = id;
	}

	public LossOfHeterozygosityId getId() {
		return this.id;
	}

	public void setId(LossOfHeterozygosityId id) {
		this.id = id;
	}

}
