package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * LoxpSite generated by hbm2java
 */
public class LoxpSite implements java.io.Serializable {

	private LoxpSiteId id;

	public LoxpSite() {
	}

	public LoxpSite(LoxpSiteId id) {
		this.id = id;
	}

	public LoxpSiteId getId() {
		return this.id;
	}

	public void setId(LoxpSiteId id) {
		this.id = id;
	}

}
