package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * LysylTrna generated by hbm2java
 */
public class LysylTrna implements java.io.Serializable {

	private LysylTrnaId id;

	public LysylTrna() {
	}

	public LysylTrna(LysylTrnaId id) {
		this.id = id;
	}

	public LysylTrnaId getId() {
		return this.id;
	}

	public void setId(LysylTrnaId id) {
		this.id = id;
	}

}
