package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * MannosylQueuosine generated by hbm2java
 */
public class MannosylQueuosine implements java.io.Serializable {

	private MannosylQueuosineId id;

	public MannosylQueuosine() {
	}

	public MannosylQueuosine(MannosylQueuosineId id) {
		this.id = id;
	}

	public MannosylQueuosineId getId() {
		return this.id;
	}

	public void setId(MannosylQueuosineId id) {
		this.id = id;
	}

}
