package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * MatureTranscriptRegion generated by hbm2java
 */
public class MatureTranscriptRegion implements java.io.Serializable {

	private MatureTranscriptRegionId id;

	public MatureTranscriptRegion() {
	}

	public MatureTranscriptRegion(MatureTranscriptRegionId id) {
		this.id = id;
	}

	public MatureTranscriptRegionId getId() {
		return this.id;
	}

	public void setId(MatureTranscriptRegionId id) {
		this.id = id;
	}

}
