package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * MatureTranscript generated by hbm2java
 */
public class MatureTranscript implements java.io.Serializable {

	private MatureTranscriptId id;

	public MatureTranscript() {
	}

	public MatureTranscript(MatureTranscriptId id) {
		this.id = id;
	}

	public MatureTranscriptId getId() {
		return this.id;
	}

	public void setId(MatureTranscriptId id) {
		this.id = id;
	}

}
