package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * MatureProteinRegion generated by hbm2java
 */
public class MatureProteinRegion implements java.io.Serializable {

	private MatureProteinRegionId id;

	public MatureProteinRegion() {
	}

	public MatureProteinRegion(MatureProteinRegionId id) {
		this.id = id;
	}

	public MatureProteinRegionId getId() {
		return this.id;
	}

	public void setId(MatureProteinRegionId id) {
		this.id = id;
	}

}
