package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * MemberOfRegulon generated by hbm2java
 */
public class MemberOfRegulon implements java.io.Serializable {

	private MemberOfRegulonId id;

	public MemberOfRegulon() {
	}

	public MemberOfRegulon(MemberOfRegulonId id) {
		this.id = id;
	}

	public MemberOfRegulonId getId() {
		return this.id;
	}

	public void setId(MemberOfRegulonId id) {
		this.id = id;
	}

}
