package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * MethylationGuideSnorna generated by hbm2java
 */
public class MethylationGuideSnorna implements java.io.Serializable {

	private MethylationGuideSnornaId id;

	public MethylationGuideSnorna() {
	}

	public MethylationGuideSnorna(MethylationGuideSnornaId id) {
		this.id = id;
	}

	public MethylationGuideSnornaId getId() {
		return this.id;
	}

	public void setId(MethylationGuideSnornaId id) {
		this.id = id;
	}

}
