package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Methionine generated by hbm2java
 */
public class Methionine implements java.io.Serializable {

	private MethionineId id;

	public Methionine() {
	}

	public Methionine(MethionineId id) {
		this.id = id;
	}

	public MethionineId getId() {
		return this.id;
	}

	public void setId(MethionineId id) {
		this.id = id;
	}

}
