package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * MethylationGuideSnornaPrimaryTranscript generated by hbm2java
 */
public class MethylationGuideSnornaPrimaryTranscript implements
		java.io.Serializable {

	private MethylationGuideSnornaPrimaryTranscriptId id;

	public MethylationGuideSnornaPrimaryTranscript() {
	}

	public MethylationGuideSnornaPrimaryTranscript(
			MethylationGuideSnornaPrimaryTranscriptId id) {
		this.id = id;
	}

	public MethylationGuideSnornaPrimaryTranscriptId getId() {
		return this.id;
	}

	public void setId(MethylationGuideSnornaPrimaryTranscriptId id) {
		this.id = id;
	}

}
