package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Methylinosine generated by hbm2java
 */
public class Methylinosine implements java.io.Serializable {

	private MethylinosineId id;

	public Methylinosine() {
	}

	public Methylinosine(MethylinosineId id) {
		this.id = id;
	}

	public MethylinosineId getId() {
		return this.id;
	}

	public void setId(MethylinosineId id) {
		this.id = id;
	}

}
