package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * MethylatedA generated by hbm2java
 */
public class MethylatedA implements java.io.Serializable {

	private MethylatedAId id;

	public MethylatedA() {
	}

	public MethylatedA(MethylatedAId id) {
		this.id = id;
	}

	public MethylatedAId getId() {
		return this.id;
	}

	public void setId(MethylatedAId id) {
		this.id = id;
	}

}
