package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * MethylatedBaseFeature generated by hbm2java
 */
public class MethylatedBaseFeature implements java.io.Serializable {

	private MethylatedBaseFeatureId id;

	public MethylatedBaseFeature() {
	}

	public MethylatedBaseFeature(MethylatedBaseFeatureId id) {
		this.id = id;
	}

	public MethylatedBaseFeatureId getId() {
		return this.id;
	}

	public void setId(MethylatedBaseFeatureId id) {
		this.id = id;
	}

}
