package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Methylwyosine generated by hbm2java
 */
public class Methylwyosine implements java.io.Serializable {

	private MethylwyosineId id;

	public Methylwyosine() {
	}

	public Methylwyosine(MethylwyosineId id) {
		this.id = id;
	}

	public MethylwyosineId getId() {
		return this.id;
	}

	public void setId(MethylwyosineId id) {
		this.id = id;
	}

}
