package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * MethylatedC generated by hbm2java
 */
public class MethylatedC implements java.io.Serializable {

	private MethylatedCId id;

	public MethylatedC() {
	}

	public MethylatedC(MethylatedCId id) {
		this.id = id;
	}

	public MethylatedCId getId() {
		return this.id;
	}

	public void setId(MethylatedCId id) {
		this.id = id;
	}

}
