package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * MethionylTrna generated by hbm2java
 */
public class MethionylTrna implements java.io.Serializable {

	private MethionylTrnaId id;

	public MethionylTrna() {
	}

	public MethionylTrna(MethionylTrnaId id) {
		this.id = id;
	}

	public MethionylTrnaId getId() {
		return this.id;
	}

	public void setId(MethionylTrnaId id) {
		this.id = id;
	}

}
