package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * MicfRna generated by hbm2java
 */
public class MicfRna implements java.io.Serializable {

	private MicfRnaId id;

	public MicfRna() {
	}

	public MicfRna(MicfRnaId id) {
		this.id = id;
	}

	public MicfRnaId getId() {
		return this.id;
	}

	public void setId(MicfRnaId id) {
		this.id = id;
	}

}
