package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * MicronuclearChromosome generated by hbm2java
 */
public class MicronuclearChromosome implements java.io.Serializable {

	private MicronuclearChromosomeId id;

	public MicronuclearChromosome() {
	}

	public MicronuclearChromosome(MicronuclearChromosomeId id) {
		this.id = id;
	}

	public MicronuclearChromosomeId getId() {
		return this.id;
	}

	public void setId(MicronuclearChromosomeId id) {
		this.id = id;
	}

}
