package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * MiniExonDonorRna generated by hbm2java
 */
public class MiniExonDonorRna implements java.io.Serializable {

	private MiniExonDonorRnaId id;

	public MiniExonDonorRna() {
	}

	public MiniExonDonorRna(MiniExonDonorRnaId id) {
		this.id = id;
	}

	public MiniExonDonorRnaId getId() {
		return this.id;
	}

	public void setId(MiniExonDonorRnaId id) {
		this.id = id;
	}

}
