package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Minicircle generated by hbm2java
 */
public class Minicircle implements java.io.Serializable {

	private MinicircleId id;

	public Minicircle() {
	}

	public Minicircle(MinicircleId id) {
		this.id = id;
	}

	public MinicircleId getId() {
		return this.id;
	}

	public void setId(MinicircleId id) {
		this.id = id;
	}

}
