package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * MiniGene generated by hbm2java
 */
public class MiniGene implements java.io.Serializable {

	private MiniGeneId id;

	public MiniGene() {
	}

	public MiniGene(MiniGeneId id) {
		this.id = id;
	}

	public MiniGeneId getId() {
		return this.id;
	}

	public void setId(MiniGeneId id) {
		this.id = id;
	}

}
