package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Minus2Frameshift generated by hbm2java
 */
public class Minus2Frameshift implements java.io.Serializable {

	private Minus2FrameshiftId id;

	public Minus2Frameshift() {
	}

	public Minus2Frameshift(Minus2FrameshiftId id) {
		this.id = id;
	}

	public Minus2FrameshiftId getId() {
		return this.id;
	}

	public void setId(Minus2FrameshiftId id) {
		this.id = id;
	}

}
