package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Minus1Frameshift generated by hbm2java
 */
public class Minus1Frameshift implements java.io.Serializable {

	private Minus1FrameshiftId id;

	public Minus1Frameshift() {
	}

	public Minus1Frameshift(Minus1FrameshiftId id) {
		this.id = id;
	}

	public Minus1FrameshiftId getId() {
		return this.id;
	}

	public void setId(Minus1FrameshiftId id) {
		this.id = id;
	}

}
