package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Minus1FrameshiftVariant generated by hbm2java
 */
public class Minus1FrameshiftVariant implements java.io.Serializable {

	private Minus1FrameshiftVariantId id;

	public Minus1FrameshiftVariant() {
	}

	public Minus1FrameshiftVariant(Minus1FrameshiftVariantId id) {
		this.id = id;
	}

	public Minus1FrameshiftVariantId getId() {
		return this.id;
	}

	public void setId(Minus1FrameshiftVariantId id) {
		this.id = id;
	}

}
