package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Mirna generated by hbm2java
 */
public class Mirna implements java.io.Serializable {

	private MirnaId id;

	public Mirna() {
	}

	public Mirna(MirnaId id) {
		this.id = id;
	}

	public MirnaId getId() {
		return this.id;
	}

	public void setId(MirnaId id) {
		this.id = id;
	}

}
