package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Mnp generated by hbm2java
 */
public class Mnp implements java.io.Serializable {

	private MnpId id;

	public Mnp() {
	}

	public Mnp(MnpId id) {
		this.id = id;
	}

	public MnpId getId() {
		return this.id;
	}

	public void setId(MnpId id) {
		this.id = id;
	}

}
