package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * MobileGeneticElement generated by hbm2java
 */
public class MobileGeneticElement implements java.io.Serializable {

	private MobileGeneticElementId id;

	public MobileGeneticElement() {
	}

	public MobileGeneticElement(MobileGeneticElementId id) {
		this.id = id;
	}

	public MobileGeneticElementId getId() {
		return this.id;
	}

	public void setId(MobileGeneticElementId id) {
		this.id = id;
	}

}
