package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ModifiedAminoAcidFeature generated by hbm2java
 */
public class ModifiedAminoAcidFeature implements java.io.Serializable {

	private ModifiedAminoAcidFeatureId id;

	public ModifiedAminoAcidFeature() {
	}

	public ModifiedAminoAcidFeature(ModifiedAminoAcidFeatureId id) {
		this.id = id;
	}

	public ModifiedAminoAcidFeatureId getId() {
		return this.id;
	}

	public void setId(ModifiedAminoAcidFeatureId id) {
		this.id = id;
	}

}
