package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ModifiedLSerine generated by hbm2java
 */
public class ModifiedLSerine implements java.io.Serializable {

	private ModifiedLSerineId id;

	public ModifiedLSerine() {
	}

	public ModifiedLSerine(ModifiedLSerineId id) {
		this.id = id;
	}

	public ModifiedLSerineId getId() {
		return this.id;
	}

	public void setId(ModifiedLSerineId id) {
		this.id = id;
	}

}
