package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ModifiedLLysine generated by hbm2java
 */
public class ModifiedLLysine implements java.io.Serializable {

	private ModifiedLLysineId id;

	public ModifiedLLysine() {
	}

	public ModifiedLLysine(ModifiedLLysineId id) {
		this.id = id;
	}

	public ModifiedLLysineId getId() {
		return this.id;
	}

	public void setId(ModifiedLLysineId id) {
		this.id = id;
	}

}
