package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ModifiedLAsparticAcid generated by hbm2java
 */
public class ModifiedLAsparticAcid implements java.io.Serializable {

	private ModifiedLAsparticAcidId id;

	public ModifiedLAsparticAcid() {
	}

	public ModifiedLAsparticAcid(ModifiedLAsparticAcidId id) {
		this.id = id;
	}

	public ModifiedLAsparticAcidId getId() {
		return this.id;
	}

	public void setId(ModifiedLAsparticAcidId id) {
		this.id = id;
	}

}
