package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ModifiedLMethionine generated by hbm2java
 */
public class ModifiedLMethionine implements java.io.Serializable {

	private ModifiedLMethionineId id;

	public ModifiedLMethionine() {
	}

	public ModifiedLMethionine(ModifiedLMethionineId id) {
		this.id = id;
	}

	public ModifiedLMethionineId getId() {
		return this.id;
	}

	public void setId(ModifiedLMethionineId id) {
		this.id = id;
	}

}
