package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ModifiedUridine generated by hbm2java
 */
public class ModifiedUridine implements java.io.Serializable {

	private ModifiedUridineId id;

	public ModifiedUridine() {
	}

	public ModifiedUridine(ModifiedUridineId id) {
		this.id = id;
	}

	public ModifiedUridineId getId() {
		return this.id;
	}

	public void setId(ModifiedUridineId id) {
		this.id = id;
	}

}
