package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ModifiedLCysteine generated by hbm2java
 */
public class ModifiedLCysteine implements java.io.Serializable {

	private ModifiedLCysteineId id;

	public ModifiedLCysteine() {
	}

	public ModifiedLCysteine(ModifiedLCysteineId id) {
		this.id = id;
	}

	public ModifiedLCysteineId getId() {
		return this.id;
	}

	public void setId(ModifiedLCysteineId id) {
		this.id = id;
	}

}
