package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ModifiedLIsoleucine generated by hbm2java
 */
public class ModifiedLIsoleucine implements java.io.Serializable {

	private ModifiedLIsoleucineId id;

	public ModifiedLIsoleucine() {
	}

	public ModifiedLIsoleucine(ModifiedLIsoleucineId id) {
		this.id = id;
	}

	public ModifiedLIsoleucineId getId() {
		return this.id;
	}

	public void setId(ModifiedLIsoleucineId id) {
		this.id = id;
	}

}
