package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ModifiedLTryptophan generated by hbm2java
 */
public class ModifiedLTryptophan implements java.io.Serializable {

	private ModifiedLTryptophanId id;

	public ModifiedLTryptophan() {
	}

	public ModifiedLTryptophan(ModifiedLTryptophanId id) {
		this.id = id;
	}

	public ModifiedLTryptophanId getId() {
		return this.id;
	}

	public void setId(ModifiedLTryptophanId id) {
		this.id = id;
	}

}
