package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * N22PrimeODimethylguanosine generated by hbm2java
 */
public class N22PrimeODimethylguanosine implements java.io.Serializable {

	private N22PrimeODimethylguanosineId id;

	public N22PrimeODimethylguanosine() {
	}

	public N22PrimeODimethylguanosine(N22PrimeODimethylguanosineId id) {
		this.id = id;
	}

	public N22PrimeODimethylguanosineId getId() {
		return this.id;
	}

	public void setId(N22PrimeODimethylguanosineId id) {
		this.id = id;
	}

}
