package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * N272prirmeOTrimethylguanosine generated by hbm2java
 */
public class N272prirmeOTrimethylguanosine implements java.io.Serializable {

	private N272prirmeOTrimethylguanosineId id;

	public N272prirmeOTrimethylguanosine() {
	}

	public N272prirmeOTrimethylguanosine(N272prirmeOTrimethylguanosineId id) {
		this.id = id;
	}

	public N272prirmeOTrimethylguanosineId getId() {
		return this.id;
	}

	public void setId(N272prirmeOTrimethylguanosineId id) {
		this.id = id;
	}

}
