package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * N27Dimethylguanosine generated by hbm2java
 */
public class N27Dimethylguanosine implements java.io.Serializable {

	private N27DimethylguanosineId id;

	public N27Dimethylguanosine() {
	}

	public N27Dimethylguanosine(N27DimethylguanosineId id) {
		this.id = id;
	}

	public N27DimethylguanosineId getId() {
		return this.id;
	}

	public void setId(N27DimethylguanosineId id) {
		this.id = id;
	}

}
