package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * N2N22PrimeOTrimethylguanosine generated by hbm2java
 */
public class N2N22PrimeOTrimethylguanosine implements java.io.Serializable {

	private N2N22PrimeOTrimethylguanosineId id;

	public N2N22PrimeOTrimethylguanosine() {
	}

	public N2N22PrimeOTrimethylguanosine(N2N22PrimeOTrimethylguanosineId id) {
		this.id = id;
	}

	public N2N22PrimeOTrimethylguanosineId getId() {
		return this.id;
	}

	public void setId(N2N22PrimeOTrimethylguanosineId id) {
		this.id = id;
	}

}
