package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * N4N42PrimeOTrimethylcytidine generated by hbm2java
 */
public class N4N42PrimeOTrimethylcytidine implements java.io.Serializable {

	private N4N42PrimeOTrimethylcytidineId id;

	public N4N42PrimeOTrimethylcytidine() {
	}

	public N4N42PrimeOTrimethylcytidine(N4N42PrimeOTrimethylcytidineId id) {
		this.id = id;
	}

	public N4N42PrimeOTrimethylcytidineId getId() {
		return this.id;
	}

	public void setId(N4N42PrimeOTrimethylcytidineId id) {
		this.id = id;
	}

}
