package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * N6Hydroxynorvalylcarbamoyladenosine generated by hbm2java
 */
public class N6Hydroxynorvalylcarbamoyladenosine implements
		java.io.Serializable {

	private N6HydroxynorvalylcarbamoyladenosineId id;

	public N6Hydroxynorvalylcarbamoyladenosine() {
	}

	public N6Hydroxynorvalylcarbamoyladenosine(
			N6HydroxynorvalylcarbamoyladenosineId id) {
		this.id = id;
	}

	public N6HydroxynorvalylcarbamoyladenosineId getId() {
		return this.id;
	}

	public void setId(N6HydroxynorvalylcarbamoyladenosineId id) {
		this.id = id;
	}

}
