package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * N6Isopentenyladenosine generated by hbm2java
 */
public class N6Isopentenyladenosine implements java.io.Serializable {

	private N6IsopentenyladenosineId id;

	public N6Isopentenyladenosine() {
	}

	public N6Isopentenyladenosine(N6IsopentenyladenosineId id) {
		this.id = id;
	}

	public N6IsopentenyladenosineId getId() {
		return this.id;
	}

	public void setId(N6IsopentenyladenosineId id) {
		this.id = id;
	}

}
