package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * N6Threonylcarbamoyladenosine generated by hbm2java
 */
public class N6Threonylcarbamoyladenosine implements java.io.Serializable {

	private N6ThreonylcarbamoyladenosineId id;

	public N6Threonylcarbamoyladenosine() {
	}

	public N6Threonylcarbamoyladenosine(N6ThreonylcarbamoyladenosineId id) {
		this.id = id;
	}

	public N6ThreonylcarbamoyladenosineId getId() {
		return this.id;
	}

	public void setId(N6ThreonylcarbamoyladenosineId id) {
		this.id = id;
	}

}
