package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * NcTranscriptVariant generated by hbm2java
 */
public class NcTranscriptVariant implements java.io.Serializable {

	private NcTranscriptVariantId id;

	public NcTranscriptVariant() {
	}

	public NcTranscriptVariant(NcTranscriptVariantId id) {
		this.id = id;
	}

	public NcTranscriptVariantId getId() {
		return this.id;
	}

	public void setId(NcTranscriptVariantId id) {
		this.id = id;
	}

}
