package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * NegativeSenseSsrnaViralSequence generated by hbm2java
 */
public class NegativeSenseSsrnaViralSequence implements java.io.Serializable {

	private NegativeSenseSsrnaViralSequenceId id;

	public NegativeSenseSsrnaViralSequence() {
	}

	public NegativeSenseSsrnaViralSequence(NegativeSenseSsrnaViralSequenceId id) {
		this.id = id;
	}

	public NegativeSenseSsrnaViralSequenceId getId() {
		return this.id;
	}

	public void setId(NegativeSenseSsrnaViralSequenceId id) {
		this.id = id;
	}

}
