package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * NegativelyAutoregulatedGene generated by hbm2java
 */
public class NegativelyAutoregulatedGene implements java.io.Serializable {

	private NegativelyAutoregulatedGeneId id;

	public NegativelyAutoregulatedGene() {
	}

	public NegativelyAutoregulatedGene(NegativelyAutoregulatedGeneId id) {
		this.id = id;
	}

	public NegativelyAutoregulatedGeneId getId() {
		return this.id;
	}

	public void setId(NegativelyAutoregulatedGeneId id) {
		this.id = id;
	}

}
