package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * NestedRepeat generated by hbm2java
 */
public class NestedRepeat implements java.io.Serializable {

	private NestedRepeatId id;

	public NestedRepeat() {
	}

	public NestedRepeat(NestedRepeatId id) {
		this.id = id;
	}

	public NestedRepeatId getId() {
		return this.id;
	}

	public void setId(NestedRepeatId id) {
		this.id = id;
	}

}
