package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * NmdTranscriptVariant generated by hbm2java
 */
public class NmdTranscriptVariant implements java.io.Serializable {

	private NmdTranscriptVariantId id;

	public NmdTranscriptVariant() {
	}

	public NmdTranscriptVariant(NmdTranscriptVariantId id) {
		this.id = id;
	}

	public NmdTranscriptVariantId getId() {
		return this.id;
	}

	public void setId(NmdTranscriptVariantId id) {
		this.id = id;
	}

}
