package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * NonamerOfRecombinationFeatureOfVertebrateImSysGene generated by hbm2java
 */
public class NonamerOfRecombinationFeatureOfVertebrateImSysGene implements
		java.io.Serializable {

	private NonamerOfRecombinationFeatureOfVertebrateImSysGeneId id;

	public NonamerOfRecombinationFeatureOfVertebrateImSysGene() {
	}

	public NonamerOfRecombinationFeatureOfVertebrateImSysGene(
			NonamerOfRecombinationFeatureOfVertebrateImSysGeneId id) {
		this.id = id;
	}

	public NonamerOfRecombinationFeatureOfVertebrateImSysGeneId getId() {
		return this.id;
	}

	public void setId(NonamerOfRecombinationFeatureOfVertebrateImSysGeneId id) {
		this.id = id;
	}

}
