package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * NonCytoplasmicPolypeptideRegion generated by hbm2java
 */
public class NonCytoplasmicPolypeptideRegion implements java.io.Serializable {

	private NonCytoplasmicPolypeptideRegionId id;

	public NonCytoplasmicPolypeptideRegion() {
	}

	public NonCytoplasmicPolypeptideRegion(NonCytoplasmicPolypeptideRegionId id) {
		this.id = id;
	}

	public NonCytoplasmicPolypeptideRegionId getId() {
		return this.id;
	}

	public void setId(NonCytoplasmicPolypeptideRegionId id) {
		this.id = id;
	}

}
