package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * NoncodingExon generated by hbm2java
 */
public class NoncodingExon implements java.io.Serializable {

	private NoncodingExonId id;

	public NoncodingExon() {
	}

	public NoncodingExon(NoncodingExonId id) {
		this.id = id;
	}

	public NoncodingExonId getId() {
		return this.id;
	}

	public void setId(NoncodingExonId id) {
		this.id = id;
	}

}
