package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * NonConservativeAminoAcidSubstitution generated by hbm2java
 */
public class NonConservativeAminoAcidSubstitution implements
		java.io.Serializable {

	private NonConservativeAminoAcidSubstitutionId id;

	public NonConservativeAminoAcidSubstitution() {
	}

	public NonConservativeAminoAcidSubstitution(
			NonConservativeAminoAcidSubstitutionId id) {
		this.id = id;
	}

	public NonConservativeAminoAcidSubstitutionId getId() {
		return this.id;
	}

	public void setId(NonConservativeAminoAcidSubstitutionId id) {
		this.id = id;
	}

}
