package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * NonCodingExonVariant generated by hbm2java
 */
public class NonCodingExonVariant implements java.io.Serializable {

	private NonCodingExonVariantId id;

	public NonCodingExonVariant() {
	}

	public NonCodingExonVariant(NonCodingExonVariantId id) {
		this.id = id;
	}

	public NonCodingExonVariantId getId() {
		return this.id;
	}

	public void setId(NonCodingExonVariantId id) {
		this.id = id;
	}

}
