package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * NonCanonicalFivePrimeSpliceSite generated by hbm2java
 */
public class NonCanonicalFivePrimeSpliceSite implements java.io.Serializable {

	private NonCanonicalFivePrimeSpliceSiteId id;

	public NonCanonicalFivePrimeSpliceSite() {
	}

	public NonCanonicalFivePrimeSpliceSite(NonCanonicalFivePrimeSpliceSiteId id) {
		this.id = id;
	}

	public NonCanonicalFivePrimeSpliceSiteId getId() {
		return this.id;
	}

	public void setId(NonCanonicalFivePrimeSpliceSiteId id) {
		this.id = id;
	}

}
