package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * NonLtrRetrotransposonPolymericTract generated by hbm2java
 */
public class NonLtrRetrotransposonPolymericTract implements
		java.io.Serializable {

	private NonLtrRetrotransposonPolymericTractId id;

	public NonLtrRetrotransposonPolymericTract() {
	}

	public NonLtrRetrotransposonPolymericTract(
			NonLtrRetrotransposonPolymericTractId id) {
		this.id = id;
	}

	public NonLtrRetrotransposonPolymericTractId getId() {
		return this.id;
	}

	public void setId(NonLtrRetrotransposonPolymericTractId id) {
		this.id = id;
	}

}
