package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * NonTerminalResidue generated by hbm2java
 */
public class NonTerminalResidue implements java.io.Serializable {

	private NonTerminalResidueId id;

	public NonTerminalResidue() {
	}

	public NonTerminalResidue(NonTerminalResidueId id) {
		this.id = id;
	}

	public NonTerminalResidueId getId() {
		return this.id;
	}

	public void setId(NonTerminalResidueId id) {
		this.id = id;
	}

}
