package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * NonTranscribedRegion generated by hbm2java
 */
public class NonTranscribedRegion implements java.io.Serializable {

	private NonTranscribedRegionId id;

	public NonTranscribedRegion() {
	}

	public NonTranscribedRegion(NonTranscribedRegionId id) {
		this.id = id;
	}

	public NonTranscribedRegionId getId() {
		return this.id;
	}

	public void setId(NonTranscribedRegionId id) {
		this.id = id;
	}

}
