package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * NTerminalRegion generated by hbm2java
 */
public class NTerminalRegion implements java.io.Serializable {

	private NTerminalRegionId id;

	public NTerminalRegion() {
	}

	public NTerminalRegion(NTerminalRegionId id) {
		this.id = id;
	}

	public NTerminalRegionId getId() {
		return this.id;
	}

	public void setId(NTerminalRegionId id) {
		this.id = id;
	}

}
