package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * NucleotideMotif generated by hbm2java
 */
public class NucleotideMotif implements java.io.Serializable {

	private NucleotideMotifId id;

	public NucleotideMotif() {
	}

	public NucleotideMotif(NucleotideMotifId id) {
		this.id = id;
	}

	public NucleotideMotifId getId() {
		return this.id;
	}

	public void setId(NucleotideMotifId id) {
		this.id = id;
	}

}
