package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * NucleotideBindingSite generated by hbm2java
 */
public class NucleotideBindingSite implements java.io.Serializable {

	private NucleotideBindingSiteId id;

	public NucleotideBindingSite() {
	}

	public NucleotideBindingSite(NucleotideBindingSiteId id) {
		this.id = id;
	}

	public NucleotideBindingSiteId getId() {
		return this.id;
	}

	public void setId(NucleotideBindingSiteId id) {
		this.id = id;
	}

}
