package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * NucleotideToProteinBindingSite generated by hbm2java
 */
public class NucleotideToProteinBindingSite implements java.io.Serializable {

	private NucleotideToProteinBindingSiteId id;

	public NucleotideToProteinBindingSite() {
	}

	public NucleotideToProteinBindingSite(NucleotideToProteinBindingSiteId id) {
		this.id = id;
	}

	public NucleotideToProteinBindingSiteId getId() {
		return this.id;
	}

	public void setId(NucleotideToProteinBindingSiteId id) {
		this.id = id;
	}

}
