package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * NuclearLocalizationSignal generated by hbm2java
 */
public class NuclearLocalizationSignal implements java.io.Serializable {

	private NuclearLocalizationSignalId id;

	public NuclearLocalizationSignal() {
	}

	public NuclearLocalizationSignal(NuclearLocalizationSignalId id) {
		this.id = id;
	}

	public NuclearLocalizationSignalId getId() {
		return this.id;
	}

	public void setId(NuclearLocalizationSignalId id) {
		this.id = id;
	}

}
