package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * OligoUTail generated by hbm2java
 */
public class OligoUTail implements java.io.Serializable {

	private OligoUTailId id;

	public OligoUTail() {
	}

	public OligoUTail(OligoUTailId id) {
		this.id = id;
	}

	public OligoUTailId getId() {
		return this.id;
	}

	public void setId(OligoUTailId id) {
		this.id = id;
	}

}
