package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * OneMethylinosine generated by hbm2java
 */
public class OneMethylinosine implements java.io.Serializable {

	private OneMethylinosineId id;

	public OneMethylinosine() {
	}

	public OneMethylinosine(OneMethylinosineId id) {
		this.id = id;
	}

	public OneMethylinosineId getId() {
		return this.id;
	}

	public void setId(OneMethylinosineId id) {
		this.id = id;
	}

}
