package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * OneMethylguanosine generated by hbm2java
 */
public class OneMethylguanosine implements java.io.Serializable {

	private OneMethylguanosineId id;

	public OneMethylguanosine() {
	}

	public OneMethylguanosine(OneMethylguanosineId id) {
		this.id = id;
	}

	public OneMethylguanosineId getId() {
		return this.id;
	}

	public void setId(OneMethylguanosineId id) {
		this.id = id;
	}

}
