package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * OneTwoPrimeODimethylinosine generated by hbm2java
 */
public class OneTwoPrimeODimethylinosine implements java.io.Serializable {

	private OneTwoPrimeODimethylinosineId id;

	public OneTwoPrimeODimethylinosine() {
	}

	public OneTwoPrimeODimethylinosine(OneTwoPrimeODimethylinosineId id) {
		this.id = id;
	}

	public OneTwoPrimeODimethylinosineId getId() {
		return this.id;
	}

	public void setId(OneTwoPrimeODimethylinosineId id) {
		this.id = id;
	}

}
