package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * OneTwoPrimeODimethylguanosine generated by hbm2java
 */
public class OneTwoPrimeODimethylguanosine implements java.io.Serializable {

	private OneTwoPrimeODimethylguanosineId id;

	public OneTwoPrimeODimethylguanosine() {
	}

	public OneTwoPrimeODimethylguanosine(OneTwoPrimeODimethylguanosineId id) {
		this.id = id;
	}

	public OneTwoPrimeODimethylguanosineId getId() {
		return this.id;
	}

	public void setId(OneTwoPrimeODimethylguanosineId id) {
		this.id = id;
	}

}
