package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * OpenChromatinRegion generated by hbm2java
 */
public class OpenChromatinRegion implements java.io.Serializable {

	private OpenChromatinRegionId id;

	public OpenChromatinRegion() {
	}

	public OpenChromatinRegion(OpenChromatinRegionId id) {
		this.id = id;
	}

	public OpenChromatinRegionId getId() {
		return this.id;
	}

	public void setId(OpenChromatinRegionId id) {
		this.id = id;
	}

}
