package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * OperonMember generated by hbm2java
 */
public class OperonMember implements java.io.Serializable {

	private OperonMemberId id;

	public OperonMember() {
	}

	public OperonMember(OperonMemberId id) {
		this.id = id;
	}

	public OperonMemberId getId() {
		return this.id;
	}

	public void setId(OperonMemberId id) {
		this.id = id;
	}

}
