package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Operon generated by hbm2java
 */
public class Operon implements java.io.Serializable {

	private OperonId id;

	public Operon() {
	}

	public Operon(OperonId id) {
		this.id = id;
	}

	public OperonId getId() {
		return this.id;
	}

	public void setId(OperonId id) {
		this.id = id;
	}

}
