package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * OrganelleSequence generated by hbm2java
 */
public class OrganelleSequence implements java.io.Serializable {

	private OrganelleSequenceId id;

	public OrganelleSequence() {
	}

	public OrganelleSequence(OrganelleSequenceId id) {
		this.id = id;
	}

	public OrganelleSequenceId getId() {
		return this.id;
	}

	public void setId(OrganelleSequenceId id) {
		this.id = id;
	}

}
