package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Oriv generated by hbm2java
 */
public class Oriv implements java.io.Serializable {

	private OrivId id;

	public Oriv() {
	}

	public Oriv(OrivId id) {
		this.id = id;
	}

	public OrivId getId() {
		return this.id;
	}

	public void setId(OrivId id) {
		this.id = id;
	}

}
