package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Orphan generated by hbm2java
 */
public class Orphan implements java.io.Serializable {

	private OrphanId id;

	public Orphan() {
	}

	public Orphan(OrphanId id) {
		this.id = id;
	}

	public OrphanId getId() {
		return this.id;
	}

	public void setId(OrphanId id) {
		this.id = id;
	}

}
