package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * OrthologousRegion generated by hbm2java
 */
public class OrthologousRegion implements java.io.Serializable {

	private OrthologousRegionId id;

	public OrthologousRegion() {
	}

	public OrthologousRegion(OrthologousRegionId id) {
		this.id = id;
	}

	public OrthologousRegionId getId() {
		return this.id;
	}

	public void setId(OrthologousRegionId id) {
		this.id = id;
	}

}
