package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Orthologous generated by hbm2java
 */
public class Orthologous implements java.io.Serializable {

	private OrthologousId id;

	public Orthologous() {
	}

	public Orthologous(OrthologousId id) {
		this.id = id;
	}

	public OrthologousId getId() {
		return this.id;
	}

	public void setId(OrthologousId id) {
		this.id = id;
	}

}
