package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Outron generated by hbm2java
 */
public class Outron implements java.io.Serializable {

	private OutronId id;

	public Outron() {
	}

	public Outron(OutronId id) {
		this.id = id;
	}

	public OutronId getId() {
		return this.id;
	}

	public void setId(OutronId id) {
		this.id = id;
	}

}
