package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * OverlappingEstSet generated by hbm2java
 */
public class OverlappingEstSet implements java.io.Serializable {

	private OverlappingEstSetId id;

	public OverlappingEstSet() {
	}

	public OverlappingEstSet(OverlappingEstSetId id) {
		this.id = id;
	}

	public OverlappingEstSetId getId() {
		return this.id;
	}

	public void setId(OverlappingEstSetId id) {
		this.id = id;
	}

}
