package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * OverlappingFeatureSet generated by hbm2java
 */
public class OverlappingFeatureSet implements java.io.Serializable {

	private OverlappingFeatureSetId id;

	public OverlappingFeatureSet() {
	}

	public OverlappingFeatureSet(OverlappingFeatureSetId id) {
		this.id = id;
	}

	public OverlappingFeatureSetId getId() {
		return this.id;
	}

	public void setId(OverlappingFeatureSetId id) {
		this.id = id;
	}

}
