package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Overlapping generated by hbm2java
 */
public class Overlapping implements java.io.Serializable {

	private OverlappingId id;

	public Overlapping() {
	}

	public Overlapping(OverlappingId id) {
		this.id = id;
	}

	public OverlappingId getId() {
		return this.id;
	}

	public void setId(OverlappingId id) {
		this.id = id;
	}

}
