package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * PacEnd generated by hbm2java
 */
public class PacEnd implements java.io.Serializable {

	private PacEndId id;

	public PacEnd() {
	}

	public PacEnd(PacEndId id) {
		this.id = id;
	}

	public PacEndId getId() {
		return this.id;
	}

	public void setId(PacEndId id) {
		this.id = id;
	}

}
