package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * PairedEndFragment generated by hbm2java
 */
public class PairedEndFragment implements java.io.Serializable {

	private PairedEndFragmentId id;

	public PairedEndFragment() {
	}

	public PairedEndFragment(PairedEndFragmentId id) {
		this.id = id;
	}

	public PairedEndFragmentId getId() {
		return this.id;
	}

	public void setId(PairedEndFragmentId id) {
		this.id = id;
	}

}
