package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Paracentric generated by hbm2java
 */
public class Paracentric implements java.io.Serializable {

	private ParacentricId id;

	public Paracentric() {
	}

	public Paracentric(ParacentricId id) {
		this.id = id;
	}

	public ParacentricId getId() {
		return this.id;
	}

	public void setId(ParacentricId id) {
		this.id = id;
	}

}
