package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * PcrProduct generated by hbm2java
 */
public class PcrProduct implements java.io.Serializable {

	private PcrProductId id;

	public PcrProduct() {
	}

	public PcrProduct(PcrProductId id) {
		this.id = id;
	}

	public PcrProductId getId() {
		return this.id;
	}

	public void setId(PcrProductId id) {
		this.id = id;
	}

}
