package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * PeptideCoil generated by hbm2java
 */
public class PeptideCoil implements java.io.Serializable {

	private PeptideCoilId id;

	public PeptideCoil() {
	}

	public PeptideCoil(PeptideCoilId id) {
		this.id = id;
	}

	public PeptideCoilId getId() {
		return this.id;
	}

	public void setId(PeptideCoilId id) {
		this.id = id;
	}

}
