package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * PeptideHelix generated by hbm2java
 */
public class PeptideHelix implements java.io.Serializable {

	private PeptideHelixId id;

	public PeptideHelix() {
	}

	public PeptideHelix(PeptideHelixId id) {
		this.id = id;
	}

	public PeptideHelixId getId() {
		return this.id;
	}

	public void setId(PeptideHelixId id) {
		this.id = id;
	}

}
