package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Peroxywybutosine generated by hbm2java
 */
public class Peroxywybutosine implements java.io.Serializable {

	private PeroxywybutosineId id;

	public Peroxywybutosine() {
	}

	public Peroxywybutosine(PeroxywybutosineId id) {
		this.id = id;
	}

	public PeroxywybutosineId getId() {
		return this.id;
	}

	public void setId(PeroxywybutosineId id) {
		this.id = id;
	}

}
