package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * PhageSequence generated by hbm2java
 */
public class PhageSequence implements java.io.Serializable {

	private PhageSequenceId id;

	public PhageSequence() {
	}

	public PhageSequence(PhageSequenceId id) {
		this.id = id;
	}

	public PhageSequenceId getId() {
		return this.id;
	}

	public void setId(PhageSequenceId id) {
		this.id = id;
	}

}
