package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Phagemid generated by hbm2java
 */
public class Phagemid implements java.io.Serializable {

	private PhagemidId id;

	public Phagemid() {
	}

	public Phagemid(PhagemidId id) {
		this.id = id;
	}

	public PhagemidId getId() {
		return this.id;
	}

	public void setId(PhagemidId id) {
		this.id = id;
	}

}
