package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Phenylalanine generated by hbm2java
 */
public class Phenylalanine implements java.io.Serializable {

	private PhenylalanineId id;

	public Phenylalanine() {
	}

	public Phenylalanine(PhenylalanineId id) {
		this.id = id;
	}

	public PhenylalanineId getId() {
		return this.id;
	}

	public void setId(PhenylalanineId id) {
		this.id = id;
	}

}
