package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * PlastidSequence generated by hbm2java
 */
public class PlastidSequence implements java.io.Serializable {

	private PlastidSequenceId id;

	public PlastidSequence() {
	}

	public PlastidSequence(PlastidSequenceId id) {
		this.id = id;
	}

	public PlastidSequenceId getId() {
		return this.id;
	}

	public void setId(PlastidSequenceId id) {
		this.id = id;
	}

}
