package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Plasmid generated by hbm2java
 */
public class Plasmid implements java.io.Serializable {

	private PlasmidId id;

	public Plasmid() {
	}

	public Plasmid(PlasmidId id) {
		this.id = id;
	}

	public PlasmidId getId() {
		return this.id;
	}

	public void setId(PlasmidId id) {
		this.id = id;
	}

}
