package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Plus2Framshift generated by hbm2java
 */
public class Plus2Framshift implements java.io.Serializable {

	private Plus2FramshiftId id;

	public Plus2Framshift() {
	}

	public Plus2Framshift(Plus2FramshiftId id) {
		this.id = id;
	}

	public Plus2FramshiftId getId() {
		return this.id;
	}

	public void setId(Plus2FramshiftId id) {
		this.id = id;
	}

}
