package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Plus2FrameshiftVariant generated by hbm2java
 */
public class Plus2FrameshiftVariant implements java.io.Serializable {

	private Plus2FrameshiftVariantId id;

	public Plus2FrameshiftVariant() {
	}

	public Plus2FrameshiftVariant(Plus2FrameshiftVariantId id) {
		this.id = id;
	}

	public Plus2FrameshiftVariantId getId() {
		return this.id;
	}

	public void setId(Plus2FrameshiftVariantId id) {
		this.id = id;
	}

}
