package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Plus1TranslationallyFrameshifted generated by hbm2java
 */
public class Plus1TranslationallyFrameshifted implements java.io.Serializable {

	private Plus1TranslationallyFrameshiftedId id;

	public Plus1TranslationallyFrameshifted() {
	}

	public Plus1TranslationallyFrameshifted(
			Plus1TranslationallyFrameshiftedId id) {
		this.id = id;
	}

	public Plus1TranslationallyFrameshiftedId getId() {
		return this.id;
	}

	public void setId(Plus1TranslationallyFrameshiftedId id) {
		this.id = id;
	}

}
