package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Plus2TranslationalFrameshift generated by hbm2java
 */
public class Plus2TranslationalFrameshift implements java.io.Serializable {

	private Plus2TranslationalFrameshiftId id;

	public Plus2TranslationalFrameshift() {
	}

	public Plus2TranslationalFrameshift(Plus2TranslationalFrameshiftId id) {
		this.id = id;
	}

	public Plus2TranslationalFrameshiftId getId() {
		return this.id;
	}

	public void setId(Plus2TranslationalFrameshiftId id) {
		this.id = id;
	}

}
