package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * PointCentromere generated by hbm2java
 */
public class PointCentromere implements java.io.Serializable {

	private PointCentromereId id;

	public PointCentromere() {
	}

	public PointCentromere(PointCentromereId id) {
		this.id = id;
	}

	public PointCentromereId getId() {
		return this.id;
	}

	public void setId(PointCentromereId id) {
		this.id = id;
	}

}
