package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Polinton generated by hbm2java
 */
public class Polinton implements java.io.Serializable {

	private PolintonId id;

	public Polinton() {
	}

	public Polinton(PolintonId id) {
		this.id = id;
	}

	public PolintonId getId() {
		return this.id;
	}

	public void setId(PolintonId id) {
		this.id = id;
	}

}
