package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * PolypeptideSequenceVariant generated by hbm2java
 */
public class PolypeptideSequenceVariant implements java.io.Serializable {

	private PolypeptideSequenceVariantId id;

	public PolypeptideSequenceVariant() {
	}

	public PolypeptideSequenceVariant(PolypeptideSequenceVariantId id) {
		this.id = id;
	}

	public PolypeptideSequenceVariantId getId() {
		return this.id;
	}

	public void setId(PolypeptideSequenceVariantId id) {
		this.id = id;
	}

}
