package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * PolypeptideSecondaryStructure generated by hbm2java
 */
public class PolypeptideSecondaryStructure implements java.io.Serializable {

	private PolypeptideSecondaryStructureId id;

	public PolypeptideSecondaryStructure() {
	}

	public PolypeptideSecondaryStructure(PolypeptideSecondaryStructureId id) {
		this.id = id;
	}

	public PolypeptideSecondaryStructureId getId() {
		return this.id;
	}

	public void setId(PolypeptideSecondaryStructureId id) {
		this.id = id;
	}

}
