package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * PolymeraseSynthesisRead generated by hbm2java
 */
public class PolymeraseSynthesisRead implements java.io.Serializable {

	private PolymeraseSynthesisReadId id;

	public PolymeraseSynthesisRead() {
	}

	public PolymeraseSynthesisRead(PolymeraseSynthesisReadId id) {
		this.id = id;
	}

	public PolymeraseSynthesisReadId getId() {
		return this.id;
	}

	public void setId(PolymeraseSynthesisReadId id) {
		this.id = id;
	}

}
