package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * PolyadenylationVariant generated by hbm2java
 */
public class PolyadenylationVariant implements java.io.Serializable {

	private PolyadenylationVariantId id;

	public PolyadenylationVariant() {
	}

	public PolyadenylationVariant(PolyadenylationVariantId id) {
		this.id = id;
	}

	public PolyadenylationVariantId getId() {
		return this.id;
	}

	public void setId(PolyadenylationVariantId id) {
		this.id = id;
	}

}
