package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * PolypeptidePartialLossOfFunction generated by hbm2java
 */
public class PolypeptidePartialLossOfFunction implements java.io.Serializable {

	private PolypeptidePartialLossOfFunctionId id;

	public PolypeptidePartialLossOfFunction() {
	}

	public PolypeptidePartialLossOfFunction(
			PolypeptidePartialLossOfFunctionId id) {
		this.id = id;
	}

	public PolypeptidePartialLossOfFunctionId getId() {
		return this.id;
	}

	public void setId(PolypeptidePartialLossOfFunctionId id) {
		this.id = id;
	}

}
