package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * PolypeptideBindingMotif generated by hbm2java
 */
public class PolypeptideBindingMotif implements java.io.Serializable {

	private PolypeptideBindingMotifId id;

	public PolypeptideBindingMotif() {
	}

	public PolypeptideBindingMotif(PolypeptideBindingMotifId id) {
		this.id = id;
	}

	public PolypeptideBindingMotifId getId() {
		return this.id;
	}

	public void setId(PolypeptideBindingMotifId id) {
		this.id = id;
	}

}
