package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * PolypeptideLossOfFunctionVariant generated by hbm2java
 */
public class PolypeptideLossOfFunctionVariant implements java.io.Serializable {

	private PolypeptideLossOfFunctionVariantId id;

	public PolypeptideLossOfFunctionVariant() {
	}

	public PolypeptideLossOfFunctionVariant(
			PolypeptideLossOfFunctionVariantId id) {
		this.id = id;
	}

	public PolypeptideLossOfFunctionVariantId getId() {
		return this.id;
	}

	public void setId(PolypeptideLossOfFunctionVariantId id) {
		this.id = id;
	}

}
