package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Polyploid generated by hbm2java
 */
public class Polyploid implements java.io.Serializable {

	private PolyploidId id;

	public Polyploid() {
	}

	public Polyploid(PolyploidId id) {
		this.id = id;
	}

	public PolyploidId getId() {
		return this.id;
	}

	public void setId(PolyploidId id) {
		this.id = id;
	}

}
