package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * PolypeptideTruncation generated by hbm2java
 */
public class PolypeptideTruncation implements java.io.Serializable {

	private PolypeptideTruncationId id;

	public PolypeptideTruncation() {
	}

	public PolypeptideTruncation(PolypeptideTruncationId id) {
		this.id = id;
	}

	public PolypeptideTruncationId getId() {
		return this.id;
	}

	public void setId(PolypeptideTruncationId id) {
		this.id = id;
	}

}
