package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * PolypeptideZincIonContactSite generated by hbm2java
 */
public class PolypeptideZincIonContactSite implements java.io.Serializable {

	private PolypeptideZincIonContactSiteId id;

	public PolypeptideZincIonContactSite() {
	}

	public PolypeptideZincIonContactSite(PolypeptideZincIonContactSiteId id) {
		this.id = id;
	}

	public PolypeptideZincIonContactSiteId getId() {
		return this.id;
	}

	public void setId(PolypeptideZincIonContactSiteId id) {
		this.id = id;
	}

}
