package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * PolymerAttribute generated by hbm2java
 */
public class PolymerAttribute implements java.io.Serializable {

	private PolymerAttributeId id;

	public PolymerAttribute() {
	}

	public PolymerAttribute(PolymerAttributeId id) {
		this.id = id;
	}

	public PolymerAttributeId getId() {
		return this.id;
	}

	public void setId(PolymerAttributeId id) {
		this.id = id;
	}

}
