package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Polypeptide generated by hbm2java
 */
public class Polypeptide implements java.io.Serializable {

	private PolypeptideId id;

	public Polypeptide() {
	}

	public Polypeptide(PolypeptideId id) {
		this.id = id;
	}

	public PolypeptideId getId() {
		return this.id;
	}

	public void setId(PolypeptideId id) {
		this.id = id;
	}

}
