package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * PolypeptideRegion generated by hbm2java
 */
public class PolypeptideRegion implements java.io.Serializable {

	private PolypeptideRegionId id;

	public PolypeptideRegion() {
	}

	public PolypeptideRegion(PolypeptideRegionId id) {
		this.id = id;
	}

	public PolypeptideRegionId getId() {
		return this.id;
	}

	public void setId(PolypeptideRegionId id) {
		this.id = id;
	}

}
