package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * PolyaSignalSequence generated by hbm2java
 */
public class PolyaSignalSequence implements java.io.Serializable {

	private PolyaSignalSequenceId id;

	public PolyaSignalSequence() {
	}

	public PolyaSignalSequence(PolyaSignalSequenceId id) {
		this.id = id;
	}

	public PolyaSignalSequenceId getId() {
		return this.id;
	}

	public void setId(PolyaSignalSequenceId id) {
		this.id = id;
	}

}
