package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * PolypeptideIronIonContactSite generated by hbm2java
 */
public class PolypeptideIronIonContactSite implements java.io.Serializable {

	private PolypeptideIronIonContactSiteId id;

	public PolypeptideIronIonContactSite() {
	}

	public PolypeptideIronIonContactSite(PolypeptideIronIonContactSiteId id) {
		this.id = id;
	}

	public PolypeptideIronIonContactSiteId getId() {
		return this.id;
	}

	public void setId(PolypeptideIronIonContactSiteId id) {
		this.id = id;
	}

}
