package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * PolypeptideCopperIonContactSite generated by hbm2java
 */
public class PolypeptideCopperIonContactSite implements java.io.Serializable {

	private PolypeptideCopperIonContactSiteId id;

	public PolypeptideCopperIonContactSite() {
	}

	public PolypeptideCopperIonContactSite(PolypeptideCopperIonContactSiteId id) {
		this.id = id;
	}

	public PolypeptideCopperIonContactSiteId getId() {
		return this.id;
	}

	public void setId(PolypeptideCopperIonContactSiteId id) {
		this.id = id;
	}

}
