package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * PositiveSenseSsrnaViralSequence generated by hbm2java
 */
public class PositiveSenseSsrnaViralSequence implements java.io.Serializable {

	private PositiveSenseSsrnaViralSequenceId id;

	public PositiveSenseSsrnaViralSequence() {
	}

	public PositiveSenseSsrnaViralSequence(PositiveSenseSsrnaViralSequenceId id) {
		this.id = id;
	}

	public PositiveSenseSsrnaViralSequenceId getId() {
		return this.id;
	}

	public void setId(PositiveSenseSsrnaViralSequenceId id) {
		this.id = id;
	}

}
