package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * PossibleAssemblyError generated by hbm2java
 */
public class PossibleAssemblyError implements java.io.Serializable {

	private PossibleAssemblyErrorId id;

	public PossibleAssemblyError() {
	}

	public PossibleAssemblyError(PossibleAssemblyErrorId id) {
		this.id = id;
	}

	public PossibleAssemblyErrorId getId() {
		return this.id;
	}

	public void setId(PossibleAssemblyErrorId id) {
		this.id = id;
	}

}
