package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * PostTranslationallyRegulatedGene generated by hbm2java
 */
public class PostTranslationallyRegulatedGene implements java.io.Serializable {

	private PostTranslationallyRegulatedGeneId id;

	public PostTranslationallyRegulatedGene() {
	}

	public PostTranslationallyRegulatedGene(
			PostTranslationallyRegulatedGeneId id) {
		this.id = id;
	}

	public PostTranslationallyRegulatedGeneId getId() {
		return this.id;
	}

	public void setId(PostTranslationallyRegulatedGeneId id) {
		this.id = id;
	}

}
