package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * PostTranslationallyRegulatedByProteinStability generated by hbm2java
 */
public class PostTranslationallyRegulatedByProteinStability implements
		java.io.Serializable {

	private PostTranslationallyRegulatedByProteinStabilityId id;

	public PostTranslationallyRegulatedByProteinStability() {
	}

	public PostTranslationallyRegulatedByProteinStability(
			PostTranslationallyRegulatedByProteinStabilityId id) {
		this.id = id;
	}

	public PostTranslationallyRegulatedByProteinStabilityId getId() {
		return this.id;
	}

	public void setId(PostTranslationallyRegulatedByProteinStabilityId id) {
		this.id = id;
	}

}
