package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * PostTranslationallyModifiedRegion generated by hbm2java
 */
public class PostTranslationallyModifiedRegion implements java.io.Serializable {

	private PostTranslationallyModifiedRegionId id;

	public PostTranslationallyModifiedRegion() {
	}

	public PostTranslationallyModifiedRegion(
			PostTranslationallyModifiedRegionId id) {
		this.id = id;
	}

	public PostTranslationallyModifiedRegionId getId() {
		return this.id;
	}

	public void setId(PostTranslationallyModifiedRegionId id) {
		this.id = id;
	}

}
