package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * PreEditedMrna generated by hbm2java
 */
public class PreEditedMrna implements java.io.Serializable {

	private PreEditedMrnaId id;

	public PreEditedMrna() {
	}

	public PreEditedMrna(PreEditedMrnaId id) {
		this.id = id;
	}

	public PreEditedMrnaId getId() {
		return this.id;
	}

	public void setId(PreEditedMrnaId id) {
		this.id = id;
	}

}
