package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * PrimerBindingSite generated by hbm2java
 */
public class PrimerBindingSite implements java.io.Serializable {

	private PrimerBindingSiteId id;

	public PrimerBindingSite() {
	}

	public PrimerBindingSite(PrimerBindingSiteId id) {
		this.id = id;
	}

	public PrimerBindingSiteId getId() {
		return this.id;
	}

	public void setId(PrimerBindingSiteId id) {
		this.id = id;
	}

}
