package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ProlylTrna generated by hbm2java
 */
public class ProlylTrna implements java.io.Serializable {

	private ProlylTrnaId id;

	public ProlylTrna() {
	}

	public ProlylTrna(ProlylTrnaId id) {
		this.id = id;
	}

	public ProlylTrnaId getId() {
		return this.id;
	}

	public void setId(ProlylTrnaId id) {
		this.id = id;
	}

}
