package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Promoter generated by hbm2java
 */
public class Promoter implements java.io.Serializable {

	private PromoterId id;

	public Promoter() {
	}

	public Promoter(PromoterId id) {
		this.id = id;
	}

	public PromoterId getId() {
		return this.id;
	}

	public void setId(PromoterId id) {
		this.id = id;
	}

}
