package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * PromoterTargetingSequence generated by hbm2java
 */
public class PromoterTargetingSequence implements java.io.Serializable {

	private PromoterTargetingSequenceId id;

	public PromoterTargetingSequence() {
	}

	public PromoterTargetingSequence(PromoterTargetingSequenceId id) {
		this.id = id;
	}

	public PromoterTargetingSequenceId getId() {
		return this.id;
	}

	public void setId(PromoterTargetingSequenceId id) {
		this.id = id;
	}

}
