package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ProplastidGene generated by hbm2java
 */
public class ProplastidGene implements java.io.Serializable {

	private ProplastidGeneId id;

	public ProplastidGene() {
	}

	public ProplastidGene(ProplastidGeneId id) {
		this.id = id;
	}

	public ProplastidGeneId getId() {
		return this.id;
	}

	public void setId(ProplastidGeneId id) {
		this.id = id;
	}

}
