package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ProplastidSequence generated by hbm2java
 */
public class ProplastidSequence implements java.io.Serializable {

	private ProplastidSequenceId id;

	public ProplastidSequence() {
	}

	public ProplastidSequence(ProplastidSequenceId id) {
		this.id = id;
	}

	public ProplastidSequenceId getId() {
		return this.id;
	}

	public void setId(ProplastidSequenceId id) {
		this.id = id;
	}

}
