package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ProteinBindingSite generated by hbm2java
 */
public class ProteinBindingSite implements java.io.Serializable {

	private ProteinBindingSiteId id;

	public ProteinBindingSite() {
	}

	public ProteinBindingSite(ProteinBindingSiteId id) {
		this.id = id;
	}

	public ProteinBindingSiteId getId() {
		return this.id;
	}

	public void setId(ProteinBindingSiteId id) {
		this.id = id;
	}

}
