package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * PseMotif generated by hbm2java
 */
public class PseMotif implements java.io.Serializable {

	private PseMotifId id;

	public PseMotif() {
	}

	public PseMotif(PseMotifId id) {
		this.id = id;
	}

	public PseMotifId getId() {
		return this.id;
	}

	public void setId(PseMotifId id) {
		this.id = id;
	}

}
