package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * PurineTransition generated by hbm2java
 */
public class PurineTransition implements java.io.Serializable {

	private PurineTransitionId id;

	public PurineTransition() {
	}

	public PurineTransition(PurineTransitionId id) {
		this.id = id;
	}

	public PurineTransitionId getId() {
		return this.id;
	}

	public void setId(PurineTransitionId id) {
		this.id = id;
	}

}
