package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * PurineToPyrimidineTransversion generated by hbm2java
 */
public class PurineToPyrimidineTransversion implements java.io.Serializable {

	private PurineToPyrimidineTransversionId id;

	public PurineToPyrimidineTransversion() {
	}

	public PurineToPyrimidineTransversion(PurineToPyrimidineTransversionId id) {
		this.id = id;
	}

	public PurineToPyrimidineTransversionId getId() {
		return this.id;
	}

	public void setId(PurineToPyrimidineTransversionId id) {
		this.id = id;
	}

}
