package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * PyrimidineTransition generated by hbm2java
 */
public class PyrimidineTransition implements java.io.Serializable {

	private PyrimidineTransitionId id;

	public PyrimidineTransition() {
	}

	public PyrimidineTransition(PyrimidineTransitionId id) {
		this.id = id;
	}

	public PyrimidineTransitionId getId() {
		return this.id;
	}

	public void setId(PyrimidineTransitionId id) {
		this.id = id;
	}

}
