package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * PyrimidineToPurineTransversion generated by hbm2java
 */
public class PyrimidineToPurineTransversion implements java.io.Serializable {

	private PyrimidineToPurineTransversionId id;

	public PyrimidineToPurineTransversion() {
	}

	public PyrimidineToPurineTransversion(PyrimidineToPurineTransversionId id) {
		this.id = id;
	}

	public PyrimidineToPurineTransversionId getId() {
		return this.id;
	}

	public void setId(PyrimidineToPurineTransversionId id) {
		this.id = id;
	}

}
