package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * PyrrolysineTrnaPrimaryTranscript generated by hbm2java
 */
public class PyrrolysineTrnaPrimaryTranscript implements java.io.Serializable {

	private PyrrolysineTrnaPrimaryTranscriptId id;

	public PyrrolysineTrnaPrimaryTranscript() {
	}

	public PyrrolysineTrnaPrimaryTranscript(
			PyrrolysineTrnaPrimaryTranscriptId id) {
		this.id = id;
	}

	public PyrrolysineTrnaPrimaryTranscriptId getId() {
		return this.id;
	}

	public void setId(PyrrolysineTrnaPrimaryTranscriptId id) {
		this.id = id;
	}

}
