package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Qtl generated by hbm2java
 */
public class Qtl implements java.io.Serializable {

	private QtlId id;

	public Qtl() {
	}

	public Qtl(QtlId id) {
		this.id = id;
	}

	public QtlId getId() {
		return this.id;
	}

	public void setId(QtlId id) {
		this.id = id;
	}

}
