package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * QualityValue generated by hbm2java
 */
public class QualityValue implements java.io.Serializable {

	private QualityValueId id;

	public QualityValue() {
	}

	public QualityValue(QualityValueId id) {
		this.id = id;
	}

	public QualityValueId getId() {
		return this.id;
	}

	public void setId(QualityValueId id) {
		this.id = id;
	}

}
