package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Queuosine generated by hbm2java
 */
public class Queuosine implements java.io.Serializable {

	private QueuosineId id;

	public Queuosine() {
	}

	public Queuosine(QueuosineId id) {
		this.id = id;
	}

	public QueuosineId getId() {
		return this.id;
	}

	public void setId(QueuosineId id) {
		this.id = id;
	}

}
