package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * RandomSequence generated by hbm2java
 */
public class RandomSequence implements java.io.Serializable {

	private RandomSequenceId id;

	public RandomSequence() {
	}

	public RandomSequence(RandomSequenceId id) {
		this.id = id;
	}

	public RandomSequenceId getId() {
		return this.id;
	}

	public void setId(RandomSequenceId id) {
		this.id = id;
	}

}
