package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Rapd generated by hbm2java
 */
public class Rapd implements java.io.Serializable {

	private RapdId id;

	public Rapd() {
	}

	public Rapd(RapdId id) {
		this.id = id;
	}

	public RapdId getId() {
		return this.id;
	}

	public void setId(RapdId id) {
		this.id = id;
	}

}
