package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Rasirna generated by hbm2java
 */
public class Rasirna implements java.io.Serializable {

	private RasirnaId id;

	public Rasirna() {
	}

	public Rasirna(RasirnaId id) {
		this.id = id;
	}

	public RasirnaId getId() {
		return this.id;
	}

	public void setId(RasirnaId id) {
		this.id = id;
	}

}
