package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * RateOfTranscriptionVariant generated by hbm2java
 */
public class RateOfTranscriptionVariant implements java.io.Serializable {

	private RateOfTranscriptionVariantId id;

	public RateOfTranscriptionVariant() {
	}

	public RateOfTranscriptionVariant(RateOfTranscriptionVariantId id) {
		this.id = id;
	}

	public RateOfTranscriptionVariantId getId() {
		return this.id;
	}

	public void setId(RateOfTranscriptionVariantId id) {
		this.id = id;
	}

}
