package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ReadingFrame generated by hbm2java
 */
public class ReadingFrame implements java.io.Serializable {

	private ReadingFrameId id;

	public ReadingFrame() {
	}

	public ReadingFrame(ReadingFrameId id) {
		this.id = id;
	}

	public ReadingFrameId getId() {
		return this.id;
	}

	public void setId(ReadingFrameId id) {
		this.id = id;
	}

}
