package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * RecodingPseudoknot generated by hbm2java
 */
public class RecodingPseudoknot implements java.io.Serializable {

	private RecodingPseudoknotId id;

	public RecodingPseudoknot() {
	}

	public RecodingPseudoknot(RecodingPseudoknotId id) {
		this.id = id;
	}

	public RecodingPseudoknotId getId() {
		return this.id;
	}

	public void setId(RecodingPseudoknotId id) {
		this.id = id;
	}

}
