package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * RecombinationFeatureOfRearrangedGene generated by hbm2java
 */
public class RecombinationFeatureOfRearrangedGene implements
		java.io.Serializable {

	private RecombinationFeatureOfRearrangedGeneId id;

	public RecombinationFeatureOfRearrangedGene() {
	}

	public RecombinationFeatureOfRearrangedGene(
			RecombinationFeatureOfRearrangedGeneId id) {
		this.id = id;
	}

	public RecombinationFeatureOfRearrangedGeneId getId() {
		return this.id;
	}

	public void setId(RecombinationFeatureOfRearrangedGeneId id) {
		this.id = id;
	}

}
