package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * RecursiveSpliceSite generated by hbm2java
 */
public class RecursiveSpliceSite implements java.io.Serializable {

	private RecursiveSpliceSiteId id;

	public RecursiveSpliceSite() {
	}

	public RecursiveSpliceSite(RecursiveSpliceSiteId id) {
		this.id = id;
	}

	public RecursiveSpliceSiteId getId() {
		return this.id;
	}

	public void setId(RecursiveSpliceSiteId id) {
		this.id = id;
	}

}
