package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * RegionalCentromereCentralCore generated by hbm2java
 */
public class RegionalCentromereCentralCore implements java.io.Serializable {

	private RegionalCentromereCentralCoreId id;

	public RegionalCentromereCentralCore() {
	}

	public RegionalCentromereCentralCore(RegionalCentromereCentralCoreId id) {
		this.id = id;
	}

	public RegionalCentromereCentralCoreId getId() {
		return this.id;
	}

	public void setId(RegionalCentromereCentralCoreId id) {
		this.id = id;
	}

}
