package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * RepeatFragment generated by hbm2java
 */
public class RepeatFragment implements java.io.Serializable {

	private RepeatFragmentId id;

	public RepeatFragment() {
	}

	public RepeatFragment(RepeatFragmentId id) {
		this.id = id;
	}

	public RepeatFragmentId getId() {
		return this.id;
	}

	public void setId(RepeatFragmentId id) {
		this.id = id;
	}

}
