package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * RepeatUnit generated by hbm2java
 */
public class RepeatUnit implements java.io.Serializable {

	private RepeatUnitId id;

	public RepeatUnit() {
	}

	public RepeatUnit(RepeatUnitId id) {
		this.id = id;
	}

	public RepeatUnitId getId() {
		return this.id;
	}

	public void setId(RepeatUnitId id) {
		this.id = id;
	}

}
