package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * RescueMiniGene generated by hbm2java
 */
public class RescueMiniGene implements java.io.Serializable {

	private RescueMiniGeneId id;

	public RescueMiniGene() {
	}

	public RescueMiniGene(RescueMiniGeneId id) {
		this.id = id;
	}

	public RescueMiniGeneId getId() {
		return this.id;
	}

	public void setId(RescueMiniGeneId id) {
		this.id = id;
	}

}
