package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ResolutionSite generated by hbm2java
 */
public class ResolutionSite implements java.io.Serializable {

	private ResolutionSiteId id;

	public ResolutionSite() {
	}

	public ResolutionSite(ResolutionSiteId id) {
		this.id = id;
	}

	public ResolutionSiteId getId() {
		return this.id;
	}

	public void setId(ResolutionSiteId id) {
		this.id = id;
	}

}
