package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * RestrictionEnzymeBindingSite generated by hbm2java
 */
public class RestrictionEnzymeBindingSite implements java.io.Serializable {

	private RestrictionEnzymeBindingSiteId id;

	public RestrictionEnzymeBindingSite() {
	}

	public RestrictionEnzymeBindingSite(RestrictionEnzymeBindingSiteId id) {
		this.id = id;
	}

	public RestrictionEnzymeBindingSiteId getId() {
		return this.id;
	}

	public void setId(RestrictionEnzymeBindingSiteId id) {
		this.id = id;
	}

}
