package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * RestrictionEnzymeCleavageJunction generated by hbm2java
 */
public class RestrictionEnzymeCleavageJunction implements java.io.Serializable {

	private RestrictionEnzymeCleavageJunctionId id;

	public RestrictionEnzymeCleavageJunction() {
	}

	public RestrictionEnzymeCleavageJunction(
			RestrictionEnzymeCleavageJunctionId id) {
		this.id = id;
	}

	public RestrictionEnzymeCleavageJunctionId getId() {
		return this.id;
	}

	public void setId(RestrictionEnzymeCleavageJunctionId id) {
		this.id = id;
	}

}
