package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * RetinoicAcidResponsiveElement generated by hbm2java
 */
public class RetinoicAcidResponsiveElement implements java.io.Serializable {

	private RetinoicAcidResponsiveElementId id;

	public RetinoicAcidResponsiveElement() {
	}

	public RetinoicAcidResponsiveElement(RetinoicAcidResponsiveElementId id) {
		this.id = id;
	}

	public RetinoicAcidResponsiveElementId getId() {
		return this.id;
	}

	public void setId(RetinoicAcidResponsiveElementId id) {
		this.id = id;
	}

}
