package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * RflpFragment generated by hbm2java
 */
public class RflpFragment implements java.io.Serializable {

	private RflpFragmentId id;

	public RflpFragment() {
	}

	public RflpFragment(RflpFragmentId id) {
		this.id = id;
	}

	public RflpFragmentId getId() {
		return this.id;
	}

	public void setId(RflpFragmentId id) {
		this.id = id;
	}

}
