package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * RhoDependentBacterialTerminator generated by hbm2java
 */
public class RhoDependentBacterialTerminator implements java.io.Serializable {

	private RhoDependentBacterialTerminatorId id;

	public RhoDependentBacterialTerminator() {
	}

	public RhoDependentBacterialTerminator(RhoDependentBacterialTerminatorId id) {
		this.id = id;
	}

	public RhoDependentBacterialTerminatorId getId() {
		return this.id;
	}

	public void setId(RhoDependentBacterialTerminatorId id) {
		this.id = id;
	}

}
