package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * RightHandedPeptideHelix generated by hbm2java
 */
public class RightHandedPeptideHelix implements java.io.Serializable {

	private RightHandedPeptideHelixId id;

	public RightHandedPeptideHelix() {
	}

	public RightHandedPeptideHelix(RightHandedPeptideHelixId id) {
		this.id = id;
	}

	public RightHandedPeptideHelixId getId() {
		return this.id;
	}

	public void setId(RightHandedPeptideHelixId id) {
		this.id = id;
	}

}
