package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * RingChromosome generated by hbm2java
 */
public class RingChromosome implements java.io.Serializable {

	private RingChromosomeId id;

	public RingChromosome() {
	}

	public RingChromosome(RingChromosomeId id) {
		this.id = id;
	}

	public RingChromosomeId getId() {
		return this.id;
	}

	public void setId(RingChromosomeId id) {
		this.id = id;
	}

}
