package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Rna generated by hbm2java
 */
public class Rna implements java.io.Serializable {

	private RnaId id;

	public Rna() {
	}

	public Rna(RnaId id) {
		this.id = id;
	}

	public RnaId getId() {
		return this.id;
	}

	public void setId(RnaId id) {
		this.id = id;
	}

}
