package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * RnaChromosome generated by hbm2java
 */
public class RnaChromosome implements java.io.Serializable {

	private RnaChromosomeId id;

	public RnaChromosome() {
	}

	public RnaChromosome(RnaChromosomeId id) {
		this.id = id;
	}

	public RnaChromosomeId getId() {
		return this.id;
	}

	public void setId(RnaChromosomeId id) {
		this.id = id;
	}

}
