package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * RnapolIiiPromoterType1 generated by hbm2java
 */
public class RnapolIiiPromoterType1 implements java.io.Serializable {

	private RnapolIiiPromoterType1Id id;

	public RnapolIiiPromoterType1() {
	}

	public RnapolIiiPromoterType1(RnapolIiiPromoterType1Id id) {
		this.id = id;
	}

	public RnapolIiiPromoterType1Id getId() {
		return this.id;
	}

	public void setId(RnapolIiiPromoterType1Id id) {
		this.id = id;
	}

}
