package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * RnapolIiiPromoterType3 generated by hbm2java
 */
public class RnapolIiiPromoterType3 implements java.io.Serializable {

	private RnapolIiiPromoterType3Id id;

	public RnapolIiiPromoterType3() {
	}

	public RnapolIiiPromoterType3(RnapolIiiPromoterType3Id id) {
		this.id = id;
	}

	public RnapolIiiPromoterType3Id getId() {
		return this.id;
	}

	public void setId(RnapolIiiPromoterType3Id id) {
		this.id = id;
	}

}
