package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * RnapolIPromoter generated by hbm2java
 */
public class RnapolIPromoter implements java.io.Serializable {

	private RnapolIPromoterId id;

	public RnapolIPromoter() {
	}

	public RnapolIPromoter(RnapolIPromoterId id) {
		this.id = id;
	}

	public RnapolIPromoterId getId() {
		return this.id;
	}

	public void setId(RnapolIPromoterId id) {
		this.id = id;
	}

}
