package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * RpraRna generated by hbm2java
 */
public class RpraRna implements java.io.Serializable {

	private RpraRnaId id;

	public RpraRna() {
	}

	public RpraRna(RpraRnaId id) {
		this.id = id;
	}

	public RpraRnaId getId() {
		return this.id;
	}

	public void setId(RpraRnaId id) {
		this.id = id;
	}

}
