package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Rrna18s generated by hbm2java
 */
public class Rrna18s implements java.io.Serializable {

	private Rrna18sId id;

	public Rrna18s() {
	}

	public Rrna18s(Rrna18sId id) {
		this.id = id;
	}

	public Rrna18sId getId() {
		return this.id;
	}

	public void setId(Rrna18sId id) {
		this.id = id;
	}

}
