package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Rrna generated by hbm2java
 */
public class Rrna implements java.io.Serializable {

	private RrnaId id;

	public Rrna() {
	}

	public Rrna(RrnaId id) {
		this.id = id;
	}

	public RrnaId getId() {
		return this.id;
	}

	public void setId(RrnaId id) {
		this.id = id;
	}

}
