package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Rrna23s generated by hbm2java
 */
public class Rrna23s implements java.io.Serializable {

	private Rrna23sId id;

	public Rrna23s() {
	}

	public Rrna23s(Rrna23sId id) {
		this.id = id;
	}

	public Rrna23sId getId() {
		return this.id;
	}

	public void setId(Rrna23sId id) {
		this.id = id;
	}

}
