package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Rrna21s generated by hbm2java
 */
public class Rrna21s implements java.io.Serializable {

	private Rrna21sId id;

	public Rrna21s() {
	}

	public Rrna21s(Rrna21sId id) {
		this.id = id;
	}

	public Rrna21sId getId() {
		return this.id;
	}

	public void setId(Rrna21sId id) {
		this.id = id;
	}

}
