package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * RrnaPrimaryTranscript generated by hbm2java
 */
public class RrnaPrimaryTranscript implements java.io.Serializable {

	private RrnaPrimaryTranscriptId id;

	public RrnaPrimaryTranscript() {
	}

	public RrnaPrimaryTranscript(RrnaPrimaryTranscriptId id) {
		this.id = id;
	}

	public RrnaPrimaryTranscriptId getId() {
		return this.id;
	}

	public void setId(RrnaPrimaryTranscriptId id) {
		this.id = id;
	}

}
