package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ScrnaPrimaryTranscript generated by hbm2java
 */
public class ScrnaPrimaryTranscript implements java.io.Serializable {

	private ScrnaPrimaryTranscriptId id;

	public ScrnaPrimaryTranscript() {
	}

	public ScrnaPrimaryTranscript(ScrnaPrimaryTranscriptId id) {
		this.id = id;
	}

	public ScrnaPrimaryTranscriptId getId() {
		return this.id;
	}

	public void setId(ScrnaPrimaryTranscriptId id) {
		this.id = id;
	}

}
