package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ScrnaEncoding generated by hbm2java
 */
public class ScrnaEncoding implements java.io.Serializable {

	private ScrnaEncodingId id;

	public ScrnaEncoding() {
	}

	public ScrnaEncoding(ScrnaEncodingId id) {
		this.id = id;
	}

	public ScrnaEncodingId getId() {
		return this.id;
	}

	public void setId(ScrnaEncodingId id) {
		this.id = id;
	}

}
