package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * SequenceDifference generated by hbm2java
 */
public class SequenceDifference implements java.io.Serializable {

	private SequenceDifferenceId id;

	public SequenceDifference() {
	}

	public SequenceDifference(SequenceDifferenceId id) {
		this.id = id;
	}

	public SequenceDifferenceId getId() {
		return this.id;
	}

	public void setId(SequenceDifferenceId id) {
		this.id = id;
	}

}
