package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * SequencingPrimer generated by hbm2java
 */
public class SequencingPrimer implements java.io.Serializable {

	private SequencingPrimerId id;

	public SequencingPrimer() {
	}

	public SequencingPrimer(SequencingPrimerId id) {
		this.id = id;
	}

	public SequencingPrimerId getId() {
		return this.id;
	}

	public void setId(SequencingPrimerId id) {
		this.id = id;
	}

}
