package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * SequenceSecondaryStructure generated by hbm2java
 */
public class SequenceSecondaryStructure implements java.io.Serializable {

	private SequenceSecondaryStructureId id;

	public SequenceSecondaryStructure() {
	}

	public SequenceSecondaryStructure(SequenceSecondaryStructureId id) {
		this.id = id;
	}

	public SequenceSecondaryStructureId getId() {
		return this.id;
	}

	public void setId(SequenceSecondaryStructureId id) {
		this.id = id;
	}

}
