package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * SequenceMotif generated by hbm2java
 */
public class SequenceMotif implements java.io.Serializable {

	private SequenceMotifId id;

	public SequenceMotif() {
	}

	public SequenceMotif(SequenceMotifId id) {
		this.id = id;
	}

	public SequenceMotifId getId() {
		return this.id;
	}

	public void setId(SequenceMotifId id) {
		this.id = id;
	}

}
