package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * SequenceLocation generated by hbm2java
 */
public class SequenceLocation implements java.io.Serializable {

	private SequenceLocationId id;

	public SequenceLocation() {
	}

	public SequenceLocation(SequenceLocationId id) {
		this.id = id;
	}

	public SequenceLocationId getId() {
		return this.id;
	}

	public void setId(SequenceLocationId id) {
		this.id = id;
	}

}
