package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * SequenceRearrangementFeature generated by hbm2java
 */
public class SequenceRearrangementFeature implements java.io.Serializable {

	private SequenceRearrangementFeatureId id;

	public SequenceRearrangementFeature() {
	}

	public SequenceRearrangementFeature(SequenceRearrangementFeatureId id) {
		this.id = id;
	}

	public SequenceRearrangementFeatureId getId() {
		return this.id;
	}

	public void setId(SequenceRearrangementFeatureId id) {
		this.id = id;
	}

}
