package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * SequenceLengthVariation generated by hbm2java
 */
public class SequenceLengthVariation implements java.io.Serializable {

	private SequenceLengthVariationId id;

	public SequenceLengthVariation() {
	}

	public SequenceLengthVariation(SequenceLengthVariationId id) {
		this.id = id;
	}

	public SequenceLengthVariationId getId() {
		return this.id;
	}

	public void setId(SequenceLengthVariationId id) {
		this.id = id;
	}

}
