package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * SequenceAlteration generated by hbm2java
 */
public class SequenceAlteration implements java.io.Serializable {

	private SequenceAlterationId id;

	public SequenceAlteration() {
	}

	public SequenceAlteration(SequenceAlterationId id) {
		this.id = id;
	}

	public SequenceAlterationId getId() {
		return this.id;
	}

	public void setId(SequenceAlterationId id) {
		this.id = id;
	}

}
