package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * SequenceUncertainty generated by hbm2java
 */
public class SequenceUncertainty implements java.io.Serializable {

	private SequenceUncertaintyId id;

	public SequenceUncertainty() {
	}

	public SequenceUncertainty(SequenceUncertaintyId id) {
		this.id = id;
	}

	public SequenceUncertaintyId getId() {
		return this.id;
	}

	public void setId(SequenceUncertaintyId id) {
		this.id = id;
	}

}
