package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * SerineThreonineTurn generated by hbm2java
 */
public class SerineThreonineTurn implements java.io.Serializable {

	private SerineThreonineTurnId id;

	public SerineThreonineTurn() {
	}

	public SerineThreonineTurn(SerineThreonineTurnId id) {
		this.id = id;
	}

	public SerineThreonineTurnId getId() {
		return this.id;
	}

	public void setId(SerineThreonineTurnId id) {
		this.id = id;
	}

}
