package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * SerineTrnaPrimaryTranscript generated by hbm2java
 */
public class SerineTrnaPrimaryTranscript implements java.io.Serializable {

	private SerineTrnaPrimaryTranscriptId id;

	public SerineTrnaPrimaryTranscript() {
	}

	public SerineTrnaPrimaryTranscript(SerineTrnaPrimaryTranscriptId id) {
		this.id = id;
	}

	public SerineTrnaPrimaryTranscriptId getId() {
		return this.id;
	}

	public void setId(SerineTrnaPrimaryTranscriptId id) {
		this.id = id;
	}

}
