package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * SerylTrna generated by hbm2java
 */
public class SerylTrna implements java.io.Serializable {

	private SerylTrnaId id;

	public SerylTrna() {
	}

	public SerylTrna(SerylTrnaId id) {
		this.id = id;
	}

	public SerylTrnaId getId() {
		return this.id;
	}

	public void setId(SerylTrnaId id) {
		this.id = id;
	}

}
