package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * SevenAminomethylSevenDeazaguanosine generated by hbm2java
 */
public class SevenAminomethylSevenDeazaguanosine implements
		java.io.Serializable {

	private SevenAminomethylSevenDeazaguanosineId id;

	public SevenAminomethylSevenDeazaguanosine() {
	}

	public SevenAminomethylSevenDeazaguanosine(
			SevenAminomethylSevenDeazaguanosineId id) {
		this.id = id;
	}

	public SevenAminomethylSevenDeazaguanosineId getId() {
		return this.id;
	}

	public void setId(SevenAminomethylSevenDeazaguanosineId id) {
		this.id = id;
	}

}
