package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * SevenDeazaguanosine generated by hbm2java
 */
public class SevenDeazaguanosine implements java.io.Serializable {

	private SevenDeazaguanosineId id;

	public SevenDeazaguanosine() {
	}

	public SevenDeazaguanosine(SevenDeazaguanosineId id) {
		this.id = id;
	}

	public SevenDeazaguanosineId getId() {
		return this.id;
	}

	public void setId(SevenDeazaguanosineId id) {
		this.id = id;
	}

}
