package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ShadowEnhancer generated by hbm2java
 */
public class ShadowEnhancer implements java.io.Serializable {

	private ShadowEnhancerId id;

	public ShadowEnhancer() {
	}

	public ShadowEnhancer(ShadowEnhancerId id) {
		this.id = id;
	}

	public ShadowEnhancerId getId() {
		return this.id;
	}

	public void setId(ShadowEnhancerId id) {
		this.id = id;
	}

}
