package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Silenced generated by hbm2java
 */
public class Silenced implements java.io.Serializable {

	private SilencedId id;

	public Silenced() {
	}

	public Silenced(SilencedId id) {
		this.id = id;
	}

	public SilencedId getId() {
		return this.id;
	}

	public void setId(SilencedId id) {
		this.id = id;
	}

}
