package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * SilencedByRnaInterference generated by hbm2java
 */
public class SilencedByRnaInterference implements java.io.Serializable {

	private SilencedByRnaInterferenceId id;

	public SilencedByRnaInterference() {
	}

	public SilencedByRnaInterference(SilencedByRnaInterferenceId id) {
		this.id = id;
	}

	public SilencedByRnaInterferenceId getId() {
		return this.id;
	}

	public void setId(SilencedByRnaInterferenceId id) {
		this.id = id;
	}

}
