package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * SimpleSequenceLengthVariation generated by hbm2java
 */
public class SimpleSequenceLengthVariation implements java.io.Serializable {

	private SimpleSequenceLengthVariationId id;

	public SimpleSequenceLengthVariation() {
	}

	public SimpleSequenceLengthVariation(SimpleSequenceLengthVariationId id) {
		this.id = id;
	}

	public SimpleSequenceLengthVariationId getId() {
		return this.id;
	}

	public void setId(SimpleSequenceLengthVariationId id) {
		this.id = id;
	}

}
