package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * SingleStrandedCdna generated by hbm2java
 */
public class SingleStrandedCdna implements java.io.Serializable {

	private SingleStrandedCdnaId id;

	public SingleStrandedCdna() {
	}

	public SingleStrandedCdna(SingleStrandedCdnaId id) {
		this.id = id;
	}

	public SingleStrandedCdnaId getId() {
		return this.id;
	}

	public void setId(SingleStrandedCdnaId id) {
		this.id = id;
	}

}
