package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Sl5AcceptorSite generated by hbm2java
 */
public class Sl5AcceptorSite implements java.io.Serializable {

	private Sl5AcceptorSiteId id;

	public Sl5AcceptorSite() {
	}

	public Sl5AcceptorSite(Sl5AcceptorSiteId id) {
		this.id = id;
	}

	public Sl5AcceptorSiteId getId() {
		return this.id;
	}

	public void setId(Sl5AcceptorSiteId id) {
		this.id = id;
	}

}
