package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Sl9AcceptorSite generated by hbm2java
 */
public class Sl9AcceptorSite implements java.io.Serializable {

	private Sl9AcceptorSiteId id;

	public Sl9AcceptorSite() {
	}

	public Sl9AcceptorSite(Sl9AcceptorSiteId id) {
		this.id = id;
	}

	public Sl9AcceptorSiteId getId() {
		return this.id;
	}

	public void setId(Sl9AcceptorSiteId id) {
		this.id = id;
	}

}
