package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * SmallRegulatoryNcrna generated by hbm2java
 */
public class SmallRegulatoryNcrna implements java.io.Serializable {

	private SmallRegulatoryNcrnaId id;

	public SmallRegulatoryNcrna() {
	}

	public SmallRegulatoryNcrna(SmallRegulatoryNcrnaId id) {
		this.id = id;
	}

	public SmallRegulatoryNcrnaId getId() {
		return this.id;
	}

	public void setId(SmallRegulatoryNcrnaId id) {
		this.id = id;
	}

}
