package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Snp generated by hbm2java
 */
public class Snp implements java.io.Serializable {

	private SnpId id;

	public Snp() {
	}

	public Snp(SnpId id) {
		this.id = id;
	}

	public SnpId getId() {
		return this.id;
	}

	public void setId(SnpId id) {
		this.id = id;
	}

}
