package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * SnrnaGene generated by hbm2java
 */
public class SnrnaGene implements java.io.Serializable {

	private SnrnaGeneId id;

	public SnrnaGene() {
	}

	public SnrnaGene(SnrnaGeneId id) {
		this.id = id;
	}

	public SnrnaGeneId getId() {
		return this.id;
	}

	public void setId(SnrnaGeneId id) {
		this.id = id;
	}

}
