package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * SnrnaPrimaryTranscript generated by hbm2java
 */
public class SnrnaPrimaryTranscript implements java.io.Serializable {

	private SnrnaPrimaryTranscriptId id;

	public SnrnaPrimaryTranscript() {
	}

	public SnrnaPrimaryTranscript(SnrnaPrimaryTranscriptId id) {
		this.id = id;
	}

	public SnrnaPrimaryTranscriptId getId() {
		return this.id;
	}

	public void setId(SnrnaPrimaryTranscriptId id) {
		this.id = id;
	}

}
