package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * SpliceosomalIntron generated by hbm2java
 */
public class SpliceosomalIntron implements java.io.Serializable {

	private SpliceosomalIntronId id;

	public SpliceosomalIntron() {
	}

	public SpliceosomalIntron(SpliceosomalIntronId id) {
		this.id = id;
	}

	public SpliceosomalIntronId getId() {
		return this.id;
	}

	public void setId(SpliceosomalIntronId id) {
		this.id = id;
	}

}
