package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * SplicedLeaderRna generated by hbm2java
 */
public class SplicedLeaderRna implements java.io.Serializable {

	private SplicedLeaderRnaId id;

	public SplicedLeaderRna() {
	}

	public SplicedLeaderRna(SplicedLeaderRnaId id) {
		this.id = id;
	}

	public SplicedLeaderRnaId getId() {
		return this.id;
	}

	public void setId(SplicedLeaderRnaId id) {
		this.id = id;
	}

}
