package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * SplicingRegulatoryRegion generated by hbm2java
 */
public class SplicingRegulatoryRegion implements java.io.Serializable {

	private SplicingRegulatoryRegionId id;

	public SplicingRegulatoryRegion() {
	}

	public SplicingRegulatoryRegion(SplicingRegulatoryRegionId id) {
		this.id = id;
	}

	public SplicingRegulatoryRegionId getId() {
		return this.id;
	}

	public void setId(SplicingRegulatoryRegionId id) {
		this.id = id;
	}

}
