package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * SpliceDonorVariant generated by hbm2java
 */
public class SpliceDonorVariant implements java.io.Serializable {

	private SpliceDonorVariantId id;

	public SpliceDonorVariant() {
	}

	public SpliceDonorVariant(SpliceDonorVariantId id) {
		this.id = id;
	}

	public SpliceDonorVariantId getId() {
		return this.id;
	}

	public void setId(SpliceDonorVariantId id) {
		this.id = id;
	}

}
