package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * SpliceRegionVariant generated by hbm2java
 */
public class SpliceRegionVariant implements java.io.Serializable {

	private SpliceRegionVariantId id;

	public SpliceRegionVariant() {
	}

	public SpliceRegionVariant(SpliceRegionVariantId id) {
		this.id = id;
	}

	public SpliceRegionVariantId getId() {
		return this.id;
	}

	public void setId(SpliceRegionVariantId id) {
		this.id = id;
	}

}
