package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * SplicingVariant generated by hbm2java
 */
public class SplicingVariant implements java.io.Serializable {

	private SplicingVariantId id;

	public SplicingVariant() {
	}

	public SplicingVariant(SplicingVariantId id) {
		this.id = id;
	}

	public SplicingVariantId getId() {
		return this.id;
	}

	public void setId(SplicingVariantId id) {
		this.id = id;
	}

}
