package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * SpliceDonor5thBaseVariant generated by hbm2java
 */
public class SpliceDonor5thBaseVariant implements java.io.Serializable {

	private SpliceDonor5thBaseVariantId id;

	public SpliceDonor5thBaseVariant() {
	}

	public SpliceDonor5thBaseVariant(SpliceDonor5thBaseVariantId id) {
		this.id = id;
	}

	public SpliceDonor5thBaseVariantId getId() {
		return this.id;
	}

	public void setId(SpliceDonor5thBaseVariantId id) {
		this.id = id;
	}

}
