package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * SsOligo generated by hbm2java
 */
public class SsOligo implements java.io.Serializable {

	private SsOligoId id;

	public SsOligo() {
	}

	public SsOligo(SsOligoId id) {
		this.id = id;
	}

	public SsOligoId getId() {
		return this.id;
	}

	public void setId(SsOligoId id) {
		this.id = id;
	}

}
