package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * SsRnaViralSequence generated by hbm2java
 */
public class SsRnaViralSequence implements java.io.Serializable {

	private SsRnaViralSequenceId id;

	public SsRnaViralSequence() {
	}

	public SsRnaViralSequence(SsRnaViralSequenceId id) {
		this.id = id;
	}

	public SsRnaViralSequenceId getId() {
		return this.id;
	}

	public void setId(SsRnaViralSequenceId id) {
		this.id = id;
	}

}
