package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * StemLoop generated by hbm2java
 */
public class StemLoop implements java.io.Serializable {

	private StemLoopId id;

	public StemLoop() {
	}

	public StemLoop(StemLoopId id) {
		this.id = id;
	}

	public StemLoopId getId() {
		return this.id;
	}

	public void setId(StemLoopId id) {
		this.id = id;
	}

}
