package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * StickyEndRestrictionEnzymeCleavageSite generated by hbm2java
 */
public class StickyEndRestrictionEnzymeCleavageSite implements
		java.io.Serializable {

	private StickyEndRestrictionEnzymeCleavageSiteId id;

	public StickyEndRestrictionEnzymeCleavageSite() {
	}

	public StickyEndRestrictionEnzymeCleavageSite(
			StickyEndRestrictionEnzymeCleavageSiteId id) {
		this.id = id;
	}

	public StickyEndRestrictionEnzymeCleavageSiteId getId() {
		return this.id;
	}

	public void setId(StickyEndRestrictionEnzymeCleavageSiteId id) {
		this.id = id;
	}

}
