package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * StopCodonRedefinedAsSelenocysteine generated by hbm2java
 */
public class StopCodonRedefinedAsSelenocysteine implements java.io.Serializable {

	private StopCodonRedefinedAsSelenocysteineId id;

	public StopCodonRedefinedAsSelenocysteine() {
	}

	public StopCodonRedefinedAsSelenocysteine(
			StopCodonRedefinedAsSelenocysteineId id) {
		this.id = id;
	}

	public StopCodonRedefinedAsSelenocysteineId getId() {
		return this.id;
	}

	public void setId(StopCodonRedefinedAsSelenocysteineId id) {
		this.id = id;
	}

}
