package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * StopCodonRedefinedAsPyrrolysine generated by hbm2java
 */
public class StopCodonRedefinedAsPyrrolysine implements java.io.Serializable {

	private StopCodonRedefinedAsPyrrolysineId id;

	public StopCodonRedefinedAsPyrrolysine() {
	}

	public StopCodonRedefinedAsPyrrolysine(StopCodonRedefinedAsPyrrolysineId id) {
		this.id = id;
	}

	public StopCodonRedefinedAsPyrrolysineId getId() {
		return this.id;
	}

	public void setId(StopCodonRedefinedAsPyrrolysineId id) {
		this.id = id;
	}

}
