package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * StrnaPrimaryTranscript generated by hbm2java
 */
public class StrnaPrimaryTranscript implements java.io.Serializable {

	private StrnaPrimaryTranscriptId id;

	public StrnaPrimaryTranscript() {
	}

	public StrnaPrimaryTranscript(StrnaPrimaryTranscriptId id) {
		this.id = id;
	}

	public StrnaPrimaryTranscriptId getId() {
		return this.id;
	}

	public void setId(StrnaPrimaryTranscriptId id) {
		this.id = id;
	}

}
