package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * StrnaEncoding generated by hbm2java
 */
public class StrnaEncoding implements java.io.Serializable {

	private StrnaEncodingId id;

	public StrnaEncoding() {
	}

	public StrnaEncoding(StrnaEncodingId id) {
		this.id = id;
	}

	public StrnaEncodingId getId() {
		return this.id;
	}

	public void setId(StrnaEncodingId id) {
		this.id = id;
	}

}
