package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * StructuralVariant generated by hbm2java
 */
public class StructuralVariant implements java.io.Serializable {

	private StructuralVariantId id;

	public StructuralVariant() {
	}

	public StructuralVariant(StructuralVariantId id) {
		this.id = id;
	}

	public StructuralVariantId getId() {
		return this.id;
	}

	public void setId(StructuralVariantId id) {
		this.id = id;
	}

}
