package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * StructuralAlteration generated by hbm2java
 */
public class StructuralAlteration implements java.io.Serializable {

	private StructuralAlterationId id;

	public StructuralAlteration() {
	}

	public StructuralAlteration(StructuralAlterationId id) {
		this.id = id;
	}

	public StructuralAlterationId getId() {
		return this.id;
	}

	public void setId(StructuralAlterationId id) {
		this.id = id;
	}

}
