package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Sts generated by hbm2java
 */
public class Sts implements java.io.Serializable {

	private StsId id;

	public Sts() {
	}

	public Sts(StsId id) {
		this.id = id;
	}

	public StsId getId() {
		return this.id;
	}

	public void setId(StsId id) {
		this.id = id;
	}

}
