package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * StTurnLeftHandedTypeTwo generated by hbm2java
 */
public class StTurnLeftHandedTypeTwo implements java.io.Serializable {

	private StTurnLeftHandedTypeTwoId id;

	public StTurnLeftHandedTypeTwo() {
	}

	public StTurnLeftHandedTypeTwo(StTurnLeftHandedTypeTwoId id) {
		this.id = id;
	}

	public StTurnLeftHandedTypeTwoId getId() {
		return this.id;
	}

	public void setId(StTurnLeftHandedTypeTwoId id) {
		this.id = id;
	}

}
