package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * SupportedBySequenceSimilarity generated by hbm2java
 */
public class SupportedBySequenceSimilarity implements java.io.Serializable {

	private SupportedBySequenceSimilarityId id;

	public SupportedBySequenceSimilarity() {
	}

	public SupportedBySequenceSimilarity(SupportedBySequenceSimilarityId id) {
		this.id = id;
	}

	public SupportedBySequenceSimilarityId getId() {
		return this.id;
	}

	public void setId(SupportedBySequenceSimilarityId id) {
		this.id = id;
	}

}
