package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * SynonymousCodon generated by hbm2java
 */
public class SynonymousCodon implements java.io.Serializable {

	private SynonymousCodonId id;

	public SynonymousCodon() {
	}

	public SynonymousCodon(SynonymousCodonId id) {
		this.id = id;
	}

	public SynonymousCodonId getId() {
		return this.id;
	}

	public void setId(SynonymousCodonId id) {
		this.id = id;
	}

}
