package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * SyntenicRegion generated by hbm2java
 */
public class SyntenicRegion implements java.io.Serializable {

	private SyntenicRegionId id;

	public SyntenicRegion() {
	}

	public SyntenicRegion(SyntenicRegionId id) {
		this.id = id;
	}

	public SyntenicRegionId getId() {
		return this.id;
	}

	public void setId(SyntenicRegionId id) {
		this.id = id;
	}

}
