package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * SyntheticOligo generated by hbm2java
 */
public class SyntheticOligo implements java.io.Serializable {

	private SyntheticOligoId id;

	public SyntheticOligo() {
	}

	public SyntheticOligo(SyntheticOligoId id) {
		this.id = id;
	}

	public SyntheticOligoId getId() {
		return this.id;
	}

	public void setId(SyntheticOligoId id) {
		this.id = id;
	}

}
