package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * SyntheticSequence generated by hbm2java
 */
public class SyntheticSequence implements java.io.Serializable {

	private SyntheticSequenceId id;

	public SyntheticSequence() {
	}

	public SyntheticSequence(SyntheticSequenceId id) {
		this.id = id;
	}

	public SyntheticSequenceId getId() {
		return this.id;
	}

	public void setId(SyntheticSequenceId id) {
		this.id = id;
	}

}
