package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Tasirna generated by hbm2java
 */
public class Tasirna implements java.io.Serializable {

	private TasirnaId id;

	public Tasirna() {
	}

	public Tasirna(TasirnaId id) {
		this.id = id;
	}

	public TasirnaId getId() {
		return this.id;
	}

	public void setId(TasirnaId id) {
		this.id = id;
	}

}
