package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * TasirnaPrimaryTranscript generated by hbm2java
 */
public class TasirnaPrimaryTranscript implements java.io.Serializable {

	private TasirnaPrimaryTranscriptId id;

	public TasirnaPrimaryTranscript() {
	}

	public TasirnaPrimaryTranscript(TasirnaPrimaryTranscriptId id) {
		this.id = id;
	}

	public TasirnaPrimaryTranscriptId getId() {
		return this.id;
	}

	public void setId(TasirnaPrimaryTranscriptId id) {
		this.id = id;
	}

}
