package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * TataBox generated by hbm2java
 */
public class TataBox implements java.io.Serializable {

	private TataBoxId id;

	public TataBox() {
	}

	public TataBox(TataBoxId id) {
		this.id = id;
	}

	public TataBoxId getId() {
		return this.id;
	}

	public void setId(TataBoxId id) {
		this.id = id;
	}

}
