package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * TelomericRepeat generated by hbm2java
 */
public class TelomericRepeat implements java.io.Serializable {

	private TelomericRepeatId id;

	public TelomericRepeat() {
	}

	public TelomericRepeat(TelomericRepeatId id) {
		this.id = id;
	}

	public TelomericRepeatId getId() {
		return this.id;
	}

	public void setId(TelomericRepeatId id) {
		this.id = id;
	}

}
