package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * TemplateRegion generated by hbm2java
 */
public class TemplateRegion implements java.io.Serializable {

	private TemplateRegionId id;

	public TemplateRegion() {
	}

	public TemplateRegion(TemplateRegionId id) {
		this.id = id;
	}

	public TemplateRegionId getId() {
		return this.id;
	}

	public void setId(TemplateRegionId id) {
		this.id = id;
	}

}
