package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * TerminalInvertedRepeat generated by hbm2java
 */
public class TerminalInvertedRepeat implements java.io.Serializable {

	private TerminalInvertedRepeatId id;

	public TerminalInvertedRepeat() {
	}

	public TerminalInvertedRepeat(TerminalInvertedRepeatId id) {
		this.id = id;
	}

	public TerminalInvertedRepeatId getId() {
		return this.id;
	}

	public void setId(TerminalInvertedRepeatId id) {
		this.id = id;
	}

}
