package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * TerminalInvertedRepeatElement generated by hbm2java
 */
public class TerminalInvertedRepeatElement implements java.io.Serializable {

	private TerminalInvertedRepeatElementId id;

	public TerminalInvertedRepeatElement() {
	}

	public TerminalInvertedRepeatElement(TerminalInvertedRepeatElementId id) {
		this.id = id;
	}

	public TerminalInvertedRepeatElementId getId() {
		return this.id;
	}

	public void setId(TerminalInvertedRepeatElementId id) {
		this.id = id;
	}

}
