package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Terminator generated by hbm2java
 */
public class Terminator implements java.io.Serializable {

	private TerminatorId id;

	public Terminator() {
	}

	public Terminator(TerminatorId id) {
		this.id = id;
	}

	public TerminatorId getId() {
		return this.id;
	}

	public void setId(TerminatorId id) {
		this.id = id;
	}

}
