package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * TerminatorCodonVariant generated by hbm2java
 */
public class TerminatorCodonVariant implements java.io.Serializable {

	private TerminatorCodonVariantId id;

	public TerminatorCodonVariant() {
	}

	public TerminatorCodonVariant(TerminatorCodonVariantId id) {
		this.id = id;
	}

	public TerminatorCodonVariantId getId() {
		return this.id;
	}

	public void setId(TerminatorCodonVariantId id) {
		this.id = id;
	}

}
