package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * TetranucRepeatMicrosat generated by hbm2java
 */
public class TetranucRepeatMicrosat implements java.io.Serializable {

	private TetranucRepeatMicrosatId id;

	public TetranucRepeatMicrosat() {
	}

	public TetranucRepeatMicrosat(TetranucRepeatMicrosatId id) {
		this.id = id;
	}

	public TetranucRepeatMicrosatId getId() {
		return this.id;
	}

	public void setId(TetranucRepeatMicrosatId id) {
		this.id = id;
	}

}
