package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ThreePrimeDHeptamer generated by hbm2java
 */
public class ThreePrimeDHeptamer implements java.io.Serializable {

	private ThreePrimeDHeptamerId id;

	public ThreePrimeDHeptamer() {
	}

	public ThreePrimeDHeptamer(ThreePrimeDHeptamerId id) {
		this.id = id;
	}

	public ThreePrimeDHeptamerId getId() {
		return this.id;
	}

	public void setId(ThreePrimeDHeptamerId id) {
		this.id = id;
	}

}
