package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ThreePrimeUtrIntron generated by hbm2java
 */
public class ThreePrimeUtrIntron implements java.io.Serializable {

	private ThreePrimeUtrIntronId id;

	public ThreePrimeUtrIntron() {
	}

	public ThreePrimeUtrIntron(ThreePrimeUtrIntronId id) {
		this.id = id;
	}

	public ThreePrimeUtrIntronId getId() {
		return this.id;
	}

	public void setId(ThreePrimeUtrIntronId id) {
		this.id = id;
	}

}
