package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ThreePrimeRaceClone generated by hbm2java
 */
public class ThreePrimeRaceClone implements java.io.Serializable {

	private ThreePrimeRaceCloneId id;

	public ThreePrimeRaceClone() {
	}

	public ThreePrimeRaceClone(ThreePrimeRaceCloneId id) {
		this.id = id;
	}

	public ThreePrimeRaceCloneId getId() {
		return this.id;
	}

	public void setId(ThreePrimeRaceCloneId id) {
		this.id = id;
	}

}
