package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ThreePrimeTerminalInvertedRepeat generated by hbm2java
 */
public class ThreePrimeTerminalInvertedRepeat implements java.io.Serializable {

	private ThreePrimeTerminalInvertedRepeatId id;

	public ThreePrimeTerminalInvertedRepeat() {
	}

	public ThreePrimeTerminalInvertedRepeat(
			ThreePrimeTerminalInvertedRepeatId id) {
		this.id = id;
	}

	public ThreePrimeTerminalInvertedRepeatId getId() {
		return this.id;
	}

	public void setId(ThreePrimeTerminalInvertedRepeatId id) {
		this.id = id;
	}

}
