package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ThreedPolypeptideStructureVariant generated by hbm2java
 */
public class ThreedPolypeptideStructureVariant implements java.io.Serializable {

	private ThreedPolypeptideStructureVariantId id;

	public ThreedPolypeptideStructureVariant() {
	}

	public ThreedPolypeptideStructureVariant(
			ThreedPolypeptideStructureVariantId id) {
		this.id = id;
	}

	public ThreedPolypeptideStructureVariantId getId() {
		return this.id;
	}

	public void setId(ThreedPolypeptideStructureVariantId id) {
		this.id = id;
	}

}
