package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ThreePrimeStemLoopStructure generated by hbm2java
 */
public class ThreePrimeStemLoopStructure implements java.io.Serializable {

	private ThreePrimeStemLoopStructureId id;

	public ThreePrimeStemLoopStructure() {
	}

	public ThreePrimeStemLoopStructure(ThreePrimeStemLoopStructureId id) {
		this.id = id;
	}

	public ThreePrimeStemLoopStructureId getId() {
		return this.id;
	}

	public void setId(ThreePrimeStemLoopStructureId id) {
		this.id = id;
	}

}
