package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ThreeThreeAminoThreeCarboxypropylUridine generated by hbm2java
 */
public class ThreeThreeAminoThreeCarboxypropylUridine implements
		java.io.Serializable {

	private ThreeThreeAminoThreeCarboxypropylUridineId id;

	public ThreeThreeAminoThreeCarboxypropylUridine() {
	}

	public ThreeThreeAminoThreeCarboxypropylUridine(
			ThreeThreeAminoThreeCarboxypropylUridineId id) {
		this.id = id;
	}

	public ThreeThreeAminoThreeCarboxypropylUridineId getId() {
		return this.id;
	}

	public void setId(ThreeThreeAminoThreeCarboxypropylUridineId id) {
		this.id = id;
	}

}
