package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ThreePrimeFlankingRegion generated by hbm2java
 */
public class ThreePrimeFlankingRegion implements java.io.Serializable {

	private ThreePrimeFlankingRegionId id;

	public ThreePrimeFlankingRegion() {
	}

	public ThreePrimeFlankingRegion(ThreePrimeFlankingRegionId id) {
		this.id = id;
	}

	public ThreePrimeFlankingRegionId getId() {
		return this.id;
	}

	public void setId(ThreePrimeFlankingRegionId id) {
		this.id = id;
	}

}
