package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * TilingPathFragment generated by hbm2java
 */
public class TilingPathFragment implements java.io.Serializable {

	private TilingPathFragmentId id;

	public TilingPathFragment() {
	}

	public TilingPathFragment(TilingPathFragmentId id) {
		this.id = id;
	}

	public TilingPathFragmentId getId() {
		return this.id;
	}

	public void setId(TilingPathFragmentId id) {
		this.id = id;
	}

}
