package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * TmrnaPrimaryTranscript generated by hbm2java
 */
public class TmrnaPrimaryTranscript implements java.io.Serializable {

	private TmrnaPrimaryTranscriptId id;

	public TmrnaPrimaryTranscript() {
	}

	public TmrnaPrimaryTranscript(TmrnaPrimaryTranscriptId id) {
		this.id = id;
	}

	public TmrnaPrimaryTranscriptId getId() {
		return this.id;
	}

	public void setId(TmrnaPrimaryTranscriptId id) {
		this.id = id;
	}

}
