package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * TmrnaAcceptorPiece generated by hbm2java
 */
public class TmrnaAcceptorPiece implements java.io.Serializable {

	private TmrnaAcceptorPieceId id;

	public TmrnaAcceptorPiece() {
	}

	public TmrnaAcceptorPiece(TmrnaAcceptorPieceId id) {
		this.id = id;
	}

	public TmrnaAcceptorPieceId getId() {
		return this.id;
	}

	public void setId(TmrnaAcceptorPieceId id) {
		this.id = id;
	}

}
