package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Tna generated by hbm2java
 */
public class Tna implements java.io.Serializable {

	private TnaId id;

	public Tna() {
	}

	public Tna(TnaId id) {
		this.id = id;
	}

	public TnaId getId() {
		return this.id;
	}

	public void setId(TnaId id) {
		this.id = id;
	}

}
