package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * TnaOligo generated by hbm2java
 */
public class TnaOligo implements java.io.Serializable {

	private TnaOligoId id;

	public TnaOligo() {
	}

	public TnaOligo(TnaOligoId id) {
		this.id = id;
	}

	public TnaOligoId getId() {
		return this.id;
	}

	public void setId(TnaOligoId id) {
		this.id = id;
	}

}
