package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * TopologyAttribute generated by hbm2java
 */
public class TopologyAttribute implements java.io.Serializable {

	private TopologyAttributeId id;

	public TopologyAttribute() {
	}

	public TopologyAttribute(TopologyAttributeId id) {
		this.id = id;
	}

	public TopologyAttributeId getId() {
		return this.id;
	}

	public void setId(TopologyAttributeId id) {
		this.id = id;
	}

}
