package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * TranslationallyFrameshifted generated by hbm2java
 */
public class TranslationallyFrameshifted implements java.io.Serializable {

	private TranslationallyFrameshiftedId id;

	public TranslationallyFrameshifted() {
	}

	public TranslationallyFrameshifted(TranslationallyFrameshiftedId id) {
		this.id = id;
	}

	public TranslationallyFrameshiftedId getId() {
		return this.id;
	}

	public void setId(TranslationallyFrameshiftedId id) {
		this.id = id;
	}

}
