package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * TransposableElementGene generated by hbm2java
 */
public class TransposableElementGene implements java.io.Serializable {

	private TransposableElementGeneId id;

	public TransposableElementGene() {
	}

	public TransposableElementGene(TransposableElementGeneId id) {
		this.id = id;
	}

	public TransposableElementGeneId getId() {
		return this.id;
	}

	public void setId(TransposableElementGeneId id) {
		this.id = id;
	}

}
