package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * TranslationRegulatoryRegion generated by hbm2java
 */
public class TranslationRegulatoryRegion implements java.io.Serializable {

	private TranslationRegulatoryRegionId id;

	public TranslationRegulatoryRegion() {
	}

	public TranslationRegulatoryRegion(TranslationRegulatoryRegionId id) {
		this.id = id;
	}

	public TranslationRegulatoryRegionId getId() {
		return this.id;
	}

	public void setId(TranslationRegulatoryRegionId id) {
		this.id = id;
	}

}
