package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * TranslationalFrameshift generated by hbm2java
 */
public class TranslationalFrameshift implements java.io.Serializable {

	private TranslationalFrameshiftId id;

	public TranslationalFrameshift() {
	}

	public TranslationalFrameshift(TranslationalFrameshiftId id) {
		this.id = id;
	}

	public TranslationalFrameshiftId getId() {
		return this.id;
	}

	public void setId(TranslationalFrameshiftId id) {
		this.id = id;
	}

}
