package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * TranslationalProductStructureVariant generated by hbm2java
 */
public class TranslationalProductStructureVariant implements
		java.io.Serializable {

	private TranslationalProductStructureVariantId id;

	public TranslationalProductStructureVariant() {
	}

	public TranslationalProductStructureVariant(
			TranslationalProductStructureVariantId id) {
		this.id = id;
	}

	public TranslationalProductStructureVariantId getId() {
		return this.id;
	}

	public void setId(TranslationalProductStructureVariantId id) {
		this.id = id;
	}

}
