package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * TranscriptRegion generated by hbm2java
 */
public class TranscriptRegion implements java.io.Serializable {

	private TranscriptRegionId id;

	public TranscriptRegion() {
	}

	public TranscriptRegion(TranscriptRegionId id) {
		this.id = id;
	}

	public TranscriptRegionId getId() {
		return this.id;
	}

	public void setId(TranscriptRegionId id) {
		this.id = id;
	}

}
