package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * TransposonFragment generated by hbm2java
 */
public class TransposonFragment implements java.io.Serializable {

	private TransposonFragmentId id;

	public TransposonFragment() {
	}

	public TransposonFragment(TransposonFragmentId id) {
		this.id = id;
	}

	public TransposonFragmentId getId() {
		return this.id;
	}

	public void setId(TransposonFragmentId id) {
		this.id = id;
	}

}
