package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * TranscriptSecondaryStructureVariant generated by hbm2java
 */
public class TranscriptSecondaryStructureVariant implements
		java.io.Serializable {

	private TranscriptSecondaryStructureVariantId id;

	public TranscriptSecondaryStructureVariant() {
	}

	public TranscriptSecondaryStructureVariant(
			TranscriptSecondaryStructureVariantId id) {
		this.id = id;
	}

	public TranscriptSecondaryStructureVariantId getId() {
		return this.id;
	}

	public void setId(TranscriptSecondaryStructureVariantId id) {
		this.id = id;
	}

}
