package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * TranslocatonAttribute generated by hbm2java
 */
public class TranslocatonAttribute implements java.io.Serializable {

	private TranslocatonAttributeId id;

	public TranslocatonAttribute() {
	}

	public TranslocatonAttribute(TranslocatonAttributeId id) {
		this.id = id;
	}

	public TranslocatonAttributeId getId() {
		return this.id;
	}

	public void setId(TranslocatonAttributeId id) {
		this.id = id;
	}

}
