package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * TransgenicTransposableElement generated by hbm2java
 */
public class TransgenicTransposableElement implements java.io.Serializable {

	private TransgenicTransposableElementId id;

	public TransgenicTransposableElement() {
	}

	public TransgenicTransposableElement(TransgenicTransposableElementId id) {
		this.id = id;
	}

	public TransgenicTransposableElementId getId() {
		return this.id;
	}

	public void setId(TransgenicTransposableElementId id) {
		this.id = id;
	}

}
