package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * TranslationalProductFunctionVariant generated by hbm2java
 */
public class TranslationalProductFunctionVariant implements
		java.io.Serializable {

	private TranslationalProductFunctionVariantId id;

	public TranslationalProductFunctionVariant() {
	}

	public TranslationalProductFunctionVariant(
			TranslationalProductFunctionVariantId id) {
		this.id = id;
	}

	public TranslationalProductFunctionVariantId getId() {
		return this.id;
	}

	public void setId(TranslationalProductFunctionVariantId id) {
		this.id = id;
	}

}
