package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * TransposableElementFlankingRegion generated by hbm2java
 */
public class TransposableElementFlankingRegion implements java.io.Serializable {

	private TransposableElementFlankingRegionId id;

	public TransposableElementFlankingRegion() {
	}

	public TransposableElementFlankingRegion(
			TransposableElementFlankingRegionId id) {
		this.id = id;
	}

	public TransposableElementFlankingRegionId getId() {
		return this.id;
	}

	public void setId(TransposableElementFlankingRegionId id) {
		this.id = id;
	}

}
