package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * TransSpliceJunction generated by hbm2java
 */
public class TransSpliceJunction implements java.io.Serializable {

	private TransSpliceJunctionId id;

	public TransSpliceJunction() {
	}

	public TransSpliceJunction(TransSpliceJunctionId id) {
		this.id = id;
	}

	public TransSpliceJunctionId getId() {
		return this.id;
	}

	public void setId(TransSpliceJunctionId id) {
		this.id = id;
	}

}
