package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Transition generated by hbm2java
 */
public class Transition implements java.io.Serializable {

	private TransitionId id;

	public Transition() {
	}

	public Transition(TransitionId id) {
		this.id = id;
	}

	public TransitionId getId() {
		return this.id;
	}

	public void setId(TransitionId id) {
		this.id = id;
	}

}
