package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * TranslocationElement generated by hbm2java
 */
public class TranslocationElement implements java.io.Serializable {

	private TranslocationElementId id;

	public TranslocationElement() {
	}

	public TranslocationElement(TranslocationElementId id) {
		this.id = id;
	}

	public TranslocationElementId getId() {
		return this.id;
	}

	public void setId(TranslocationElementId id) {
		this.id = id;
	}

}
