package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * TranscriptFunctionVariant generated by hbm2java
 */
public class TranscriptFunctionVariant implements java.io.Serializable {

	private TranscriptFunctionVariantId id;

	public TranscriptFunctionVariant() {
	}

	public TranscriptFunctionVariant(TranscriptFunctionVariantId id) {
		this.id = id;
	}

	public TranscriptFunctionVariantId getId() {
		return this.id;
	}

	public void setId(TranscriptFunctionVariantId id) {
		this.id = id;
	}

}
