package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * TrinucRepeatMicrosat generated by hbm2java
 */
public class TrinucRepeatMicrosat implements java.io.Serializable {

	private TrinucRepeatMicrosatId id;

	public TrinucRepeatMicrosat() {
	}

	public TrinucRepeatMicrosat(TrinucRepeatMicrosatId id) {
		this.id = id;
	}

	public TrinucRepeatMicrosatId getId() {
		return this.id;
	}

	public void setId(TrinucRepeatMicrosatId id) {
		this.id = id;
	}

}
