package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Tss generated by hbm2java
 */
public class Tss implements java.io.Serializable {

	private TssId id;

	public Tss() {
	}

	public Tss(TssId id) {
		this.id = id;
	}

	public TssId getId() {
		return this.id;
	}

	public void setId(TssId id) {
		this.id = id;
	}

}
