package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * TwokbUpstreamVariant generated by hbm2java
 */
public class TwokbUpstreamVariant implements java.io.Serializable {

	private TwokbUpstreamVariantId id;

	public TwokbUpstreamVariant() {
	}

	public TwokbUpstreamVariant(TwokbUpstreamVariantId id) {
		this.id = id;
	}

	public TwokbUpstreamVariantId getId() {
		return this.id;
	}

	public void setId(TwokbUpstreamVariantId id) {
		this.id = id;
	}

}
