package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * TwoMethylthioN6Isopentenyladenosine generated by hbm2java
 */
public class TwoMethylthioN6Isopentenyladenosine implements
		java.io.Serializable {

	private TwoMethylthioN6IsopentenyladenosineId id;

	public TwoMethylthioN6Isopentenyladenosine() {
	}

	public TwoMethylthioN6Isopentenyladenosine(
			TwoMethylthioN6IsopentenyladenosineId id) {
		this.id = id;
	}

	public TwoMethylthioN6IsopentenyladenosineId getId() {
		return this.id;
	}

	public void setId(TwoMethylthioN6IsopentenyladenosineId id) {
		this.id = id;
	}

}
