package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * TwoPrimeORiboaPhosphate generated by hbm2java
 */
public class TwoPrimeORiboaPhosphate implements java.io.Serializable {

	private TwoPrimeORiboaPhosphateId id;

	public TwoPrimeORiboaPhosphate() {
	}

	public TwoPrimeORiboaPhosphate(TwoPrimeORiboaPhosphateId id) {
		this.id = id;
	}

	public TwoPrimeORiboaPhosphateId getId() {
		return this.id;
	}

	public void setId(TwoPrimeORiboaPhosphateId id) {
		this.id = id;
	}

}
