package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * TwoPrimeOMethylinosine generated by hbm2java
 */
public class TwoPrimeOMethylinosine implements java.io.Serializable {

	private TwoPrimeOMethylinosineId id;

	public TwoPrimeOMethylinosine() {
	}

	public TwoPrimeOMethylinosine(TwoPrimeOMethylinosineId id) {
		this.id = id;
	}

	public TwoPrimeOMethylinosineId getId() {
		return this.id;
	}

	public void setId(TwoPrimeOMethylinosineId id) {
		this.id = id;
	}

}
