package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * TwoPrimeOMethylpseudouridine generated by hbm2java
 */
public class TwoPrimeOMethylpseudouridine implements java.io.Serializable {

	private TwoPrimeOMethylpseudouridineId id;

	public TwoPrimeOMethylpseudouridine() {
	}

	public TwoPrimeOMethylpseudouridine(TwoPrimeOMethylpseudouridineId id) {
		this.id = id;
	}

	public TwoPrimeOMethylpseudouridineId getId() {
		return this.id;
	}

	public void setId(TwoPrimeOMethylpseudouridineId id) {
		this.id = id;
	}

}
