package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * TwoThioTwoPrimeOMethyluridine generated by hbm2java
 */
public class TwoThioTwoPrimeOMethyluridine implements java.io.Serializable {

	private TwoThioTwoPrimeOMethyluridineId id;

	public TwoThioTwoPrimeOMethyluridine() {
	}

	public TwoThioTwoPrimeOMethyluridine(TwoThioTwoPrimeOMethyluridineId id) {
		this.id = id;
	}

	public TwoThioTwoPrimeOMethyluridineId getId() {
		return this.id;
	}

	public void setId(TwoThioTwoPrimeOMethyluridineId id) {
		this.id = id;
	}

}
