package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * U11Snrna generated by hbm2java
 */
public class U11Snrna implements java.io.Serializable {

	private U11SnrnaId id;

	public U11Snrna() {
	}

	public U11Snrna(U11SnrnaId id) {
		this.id = id;
	}

	public U11SnrnaId getId() {
		return this.id;
	}

	public void setId(U11SnrnaId id) {
		this.id = id;
	}

}
