package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * U12Intron generated by hbm2java
 */
public class U12Intron implements java.io.Serializable {

	private U12IntronId id;

	public U12Intron() {
	}

	public U12Intron(U12IntronId id) {
		this.id = id;
	}

	public U12IntronId getId() {
		return this.id;
	}

	public void setId(U12IntronId id) {
		this.id = id;
	}

}
