package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * U12Snrna generated by hbm2java
 */
public class U12Snrna implements java.io.Serializable {

	private U12SnrnaId id;

	public U12Snrna() {
	}

	public U12Snrna(U12SnrnaId id) {
		this.id = id;
	}

	public U12SnrnaId getId() {
		return this.id;
	}

	public void setId(U12SnrnaId id) {
		this.id = id;
	}

}
