package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * U14SnornaPrimaryTranscript generated by hbm2java
 */
public class U14SnornaPrimaryTranscript implements java.io.Serializable {

	private U14SnornaPrimaryTranscriptId id;

	public U14SnornaPrimaryTranscript() {
	}

	public U14SnornaPrimaryTranscript(U14SnornaPrimaryTranscriptId id) {
		this.id = id;
	}

	public U14SnornaPrimaryTranscriptId getId() {
		return this.id;
	}

	public void setId(U14SnornaPrimaryTranscriptId id) {
		this.id = id;
	}

}
