package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * U1Snrna generated by hbm2java
 */
public class U1Snrna implements java.io.Serializable {

	private U1SnrnaId id;

	public U1Snrna() {
	}

	public U1Snrna(U1SnrnaId id) {
		this.id = id;
	}

	public U1SnrnaId getId() {
		return this.id;
	}

	public void setId(U1SnrnaId id) {
		this.id = id;
	}

}
