package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * U2Intron generated by hbm2java
 */
public class U2Intron implements java.io.Serializable {

	private U2IntronId id;

	public U2Intron() {
	}

	public U2Intron(U2IntronId id) {
		this.id = id;
	}

	public U2IntronId getId() {
		return this.id;
	}

	public void setId(U2IntronId id) {
		this.id = id;
	}

}
