package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * U3LtrRegion generated by hbm2java
 */
public class U3LtrRegion implements java.io.Serializable {

	private U3LtrRegionId id;

	public U3LtrRegion() {
	}

	public U3LtrRegion(U3LtrRegionId id) {
		this.id = id;
	}

	public U3LtrRegionId getId() {
		return this.id;
	}

	public void setId(U3LtrRegionId id) {
		this.id = id;
	}

}
