package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * U3Snorna generated by hbm2java
 */
public class U3Snorna implements java.io.Serializable {

	private U3SnornaId id;

	public U3Snorna() {
	}

	public U3Snorna(U3SnornaId id) {
		this.id = id;
	}

	public U3SnornaId getId() {
		return this.id;
	}

	public void setId(U3SnornaId id) {
		this.id = id;
	}

}
