package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * U3ThreePrimeLtrRegion generated by hbm2java
 */
public class U3ThreePrimeLtrRegion implements java.io.Serializable {

	private U3ThreePrimeLtrRegionId id;

	public U3ThreePrimeLtrRegion() {
	}

	public U3ThreePrimeLtrRegion(U3ThreePrimeLtrRegionId id) {
		this.id = id;
	}

	public U3ThreePrimeLtrRegionId getId() {
		return this.id;
	}

	public void setId(U3ThreePrimeLtrRegionId id) {
		this.id = id;
	}

}
