package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * U5FivePrimeLtrRegion generated by hbm2java
 */
public class U5FivePrimeLtrRegion implements java.io.Serializable {

	private U5FivePrimeLtrRegionId id;

	public U5FivePrimeLtrRegion() {
	}

	public U5FivePrimeLtrRegion(U5FivePrimeLtrRegionId id) {
		this.id = id;
	}

	public U5FivePrimeLtrRegionId getId() {
		return this.id;
	}

	public void setId(U5FivePrimeLtrRegionId id) {
		this.id = id;
	}

}
