package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * U5Snrna generated by hbm2java
 */
public class U5Snrna implements java.io.Serializable {

	private U5SnrnaId id;

	public U5Snrna() {
	}

	public U5Snrna(U5SnrnaId id) {
		this.id = id;
	}

	public U5SnrnaId getId() {
		return this.id;
	}

	public void setId(U5SnrnaId id) {
		this.id = id;
	}

}
