package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * U6atacSnrna generated by hbm2java
 */
public class U6atacSnrna implements java.io.Serializable {

	private U6atacSnrnaId id;

	public U6atacSnrna() {
	}

	public U6atacSnrna(U6atacSnrnaId id) {
		this.id = id;
	}

	public U6atacSnrnaId getId() {
		return this.id;
	}

	public void setId(U6atacSnrnaId id) {
		this.id = id;
	}

}
