package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * U6Snrna generated by hbm2java
 */
public class U6Snrna implements java.io.Serializable {

	private U6SnrnaId id;

	public U6Snrna() {
	}

	public U6Snrna(U6SnrnaId id) {
		this.id = id;
	}

	public U6SnrnaId getId() {
		return this.id;
	}

	public void setId(U6SnrnaId id) {
		this.id = id;
	}

}
