package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * UndermodifiedHydroxywybutosine generated by hbm2java
 */
public class UndermodifiedHydroxywybutosine implements java.io.Serializable {

	private UndermodifiedHydroxywybutosineId id;

	public UndermodifiedHydroxywybutosine() {
	}

	public UndermodifiedHydroxywybutosine(UndermodifiedHydroxywybutosineId id) {
		this.id = id;
	}

	public UndermodifiedHydroxywybutosineId getId() {
		return this.id;
	}

	public void setId(UndermodifiedHydroxywybutosineId id) {
		this.id = id;
	}

}
