package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * UninvertIntraTransposition generated by hbm2java
 */
public class UninvertIntraTransposition implements java.io.Serializable {

	private UninvertIntraTranspositionId id;

	public UninvertIntraTransposition() {
	}

	public UninvertIntraTransposition(UninvertIntraTranspositionId id) {
		this.id = id;
	}

	public UninvertIntraTranspositionId getId() {
		return this.id;
	}

	public void setId(UninvertIntraTranspositionId id) {
		this.id = id;
	}

}
