package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * UninvertInterTransposition generated by hbm2java
 */
public class UninvertInterTransposition implements java.io.Serializable {

	private UninvertInterTranspositionId id;

	public UninvertInterTransposition() {
	}

	public UninvertInterTransposition(UninvertInterTranspositionId id) {
		this.id = id;
	}

	public UninvertInterTranspositionId getId() {
		return this.id;
	}

	public void setId(UninvertInterTranspositionId id) {
		this.id = id;
	}

}
