package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * UniqueVariant generated by hbm2java
 */
public class UniqueVariant implements java.io.Serializable {

	private UniqueVariantId id;

	public UniqueVariant() {
	}

	public UniqueVariant(UniqueVariantId id) {
		this.id = id;
	}

	public UniqueVariantId getId() {
		return this.id;
	}

	public void setId(UniqueVariantId id) {
		this.id = id;
	}

}
