package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * UnorientedInterchromosomalTransposition generated by hbm2java
 */
public class UnorientedInterchromosomalTransposition implements
		java.io.Serializable {

	private UnorientedInterchromosomalTranspositionId id;

	public UnorientedInterchromosomalTransposition() {
	}

	public UnorientedInterchromosomalTransposition(
			UnorientedInterchromosomalTranspositionId id) {
		this.id = id;
	}

	public UnorientedInterchromosomalTranspositionId getId() {
		return this.id;
	}

	public void setId(UnorientedInterchromosomalTranspositionId id) {
		this.id = id;
	}

}
