package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * UntranslatedRegionPolycistronicMrna generated by hbm2java
 */
public class UntranslatedRegionPolycistronicMrna implements
		java.io.Serializable {

	private UntranslatedRegionPolycistronicMrnaId id;

	public UntranslatedRegionPolycistronicMrna() {
	}

	public UntranslatedRegionPolycistronicMrna(
			UntranslatedRegionPolycistronicMrnaId id) {
		this.id = id;
	}

	public UntranslatedRegionPolycistronicMrnaId getId() {
		return this.id;
	}

	public void setId(UntranslatedRegionPolycistronicMrnaId id) {
		this.id = id;
	}

}
