package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * UpstreamAugCodon generated by hbm2java
 */
public class UpstreamAugCodon implements java.io.Serializable {

	private UpstreamAugCodonId id;

	public UpstreamAugCodon() {
	}

	public UpstreamAugCodon(UpstreamAugCodonId id) {
		this.id = id;
	}

	public UpstreamAugCodonId getId() {
		return this.id;
	}

	public void setId(UpstreamAugCodonId id) {
		this.id = id;
	}

}
