package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ValineTrnaPrimaryTranscript generated by hbm2java
 */
public class ValineTrnaPrimaryTranscript implements java.io.Serializable {

	private ValineTrnaPrimaryTranscriptId id;

	public ValineTrnaPrimaryTranscript() {
	}

	public ValineTrnaPrimaryTranscript(ValineTrnaPrimaryTranscriptId id) {
		this.id = id;
	}

	public ValineTrnaPrimaryTranscriptId getId() {
		return this.id;
	}

	public void setId(ValineTrnaPrimaryTranscriptId id) {
		this.id = id;
	}

}
