package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * VCluster generated by hbm2java
 */
public class VCluster implements java.io.Serializable {

	private VClusterId id;

	public VCluster() {
	}

	public VCluster(VClusterId id) {
		this.id = id;
	}

	public VClusterId getId() {
		return this.id;
	}

	public void setId(VClusterId id) {
		this.id = id;
	}

}
