package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * VDDjCCluster generated by hbm2java
 */
public class VDDjCCluster implements java.io.Serializable {

	private VDDjCClusterId id;

	public VDDjCCluster() {
	}

	public VDDjCCluster(VDDjCClusterId id) {
		this.id = id;
	}

	public VDDjCClusterId getId() {
		return this.id;
	}

	public void setId(VDDjCClusterId id) {
		this.id = id;
	}

}
