package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * VDDjJCCluster generated by hbm2java
 */
public class VDDjJCCluster implements java.io.Serializable {

	private VDDjJCClusterId id;

	public VDDjJCCluster() {
	}

	public VDDjJCCluster(VDDjJCClusterId id) {
		this.id = id;
	}

	public VDDjJCClusterId getId() {
		return this.id;
	}

	public void setId(VDDjJCClusterId id) {
		this.id = id;
	}

}
