package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * VDDjCluster generated by hbm2java
 */
public class VDDjCluster implements java.io.Serializable {

	private VDDjClusterId id;

	public VDDjCluster() {
	}

	public VDDjCluster(VDDjClusterId id) {
		this.id = id;
	}

	public VDDjClusterId getId() {
		return this.id;
	}

	public void setId(VDDjClusterId id) {
		this.id = id;
	}

}
