package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * VDJCluster generated by hbm2java
 */
public class VDJCluster implements java.io.Serializable {

	private VDJClusterId id;

	public VDJCluster() {
	}

	public VDJCluster(VDJClusterId id) {
		this.id = id;
	}

	public VDJClusterId getId() {
		return this.id;
	}

	public void setId(VDJClusterId id) {
		this.id = id;
	}

}
