package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * VDjJCCluster generated by hbm2java
 */
public class VDjJCCluster implements java.io.Serializable {

	private VDjJCClusterId id;

	public VDjJCCluster() {
	}

	public VDjJCCluster(VDjJCClusterId id) {
		this.id = id;
	}

	public VDjJCClusterId getId() {
		return this.id;
	}

	public void setId(VDjJCClusterId id) {
		this.id = id;
	}

}
