package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * VdjJCluster generated by hbm2java
 */
public class VdjJCluster implements java.io.Serializable {

	private VdjJClusterId id;

	public VdjJCluster() {
	}

	public VdjJCluster(VdjJClusterId id) {
		this.id = id;
	}

	public VdjJClusterId getId() {
		return this.id;
	}

	public void setId(VdjJClusterId id) {
		this.id = id;
	}

}
