package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ViralSequence generated by hbm2java
 */
public class ViralSequence implements java.io.Serializable {

	private ViralSequenceId id;

	public ViralSequence() {
	}

	public ViralSequence(ViralSequenceId id) {
		this.id = id;
	}

	public ViralSequenceId getId() {
		return this.id;
	}

	public void setId(ViralSequenceId id) {
		this.id = id;
	}

}
