package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * VirtualSequence generated by hbm2java
 */
public class VirtualSequence implements java.io.Serializable {

	private VirtualSequenceId id;

	public VirtualSequence() {
	}

	public VirtualSequence(VirtualSequenceId id) {
		this.id = id;
	}

	public VirtualSequenceId getId() {
		return this.id;
	}

	public void setId(VirtualSequenceId id) {
		this.id = id;
	}

}
