package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * VJCluster generated by hbm2java
 */
public class VJCluster implements java.io.Serializable {

	private VJClusterId id;

	public VJCluster() {
	}

	public VJCluster(VJClusterId id) {
		this.id = id;
	}

	public VJClusterId getId() {
		return this.id;
	}

	public void setId(VJClusterId id) {
		this.id = id;
	}

}
