package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * VjJCluster generated by hbm2java
 */
public class VjJCluster implements java.io.Serializable {

	private VjJClusterId id;

	public VjJCluster() {
	}

	public VjJCluster(VjJClusterId id) {
		this.id = id;
	}

	public VjJClusterId getId() {
		return this.id;
	}

	public void setId(VjJClusterId id) {
		this.id = id;
	}

}
