package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * VNonamer generated by hbm2java
 */
public class VNonamer implements java.io.Serializable {

	private VNonamerId id;

	public VNonamer() {
	}

	public VNonamer(VNonamerId id) {
		this.id = id;
	}

	public VNonamerId getId() {
		return this.id;
	}

	public void setId(VNonamerId id) {
		this.id = id;
	}

}
