package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * VVdjCluster generated by hbm2java
 */
public class VVdjCluster implements java.io.Serializable {

	private VVdjClusterId id;

	public VVdjCluster() {
	}

	public VVdjCluster(VVdjClusterId id) {
		this.id = id;
	}

	public VVdjClusterId getId() {
		return this.id;
	}

	public void setId(VVdjClusterId id) {
		this.id = id;
	}

}
