package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * VVjCCluster generated by hbm2java
 */
public class VVjCCluster implements java.io.Serializable {

	private VVjCClusterId id;

	public VVjCCluster() {
	}

	public VVjCCluster(VVjCClusterId id) {
		this.id = id;
	}

	public VVjCClusterId getId() {
		return this.id;
	}

	public void setId(VVjCClusterId id) {
		this.id = id;
	}

}
