package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * VVjJCCluster generated by hbm2java
 */
public class VVjJCCluster implements java.io.Serializable {

	private VVjJCClusterId id;

	public VVjJCCluster() {
	}

	public VVjJCCluster(VVjJCClusterId id) {
		this.id = id;
	}

	public VVjJCClusterId getId() {
		return this.id;
	}

	public void setId(VVjJCClusterId id) {
		this.id = id;
	}

}
