package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * WcBasePair generated by hbm2java
 */
public class WcBasePair implements java.io.Serializable {

	private WcBasePairId id;

	public WcBasePair() {
	}

	public WcBasePair(WcBasePairId id) {
		this.id = id;
	}

	public WcBasePairId getId() {
		return this.id;
	}

	public void setId(WcBasePairId id) {
		this.id = id;
	}

}
