package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * WholeGenomeSequenceStatus generated by hbm2java
 */
public class WholeGenomeSequenceStatus implements java.io.Serializable {

	private WholeGenomeSequenceStatusId id;

	public WholeGenomeSequenceStatus() {
	}

	public WholeGenomeSequenceStatus(WholeGenomeSequenceStatusId id) {
		this.id = id;
	}

	public WholeGenomeSequenceStatusId getId() {
		return this.id;
	}

	public void setId(WholeGenomeSequenceStatusId id) {
		this.id = id;
	}

}
