package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * WildTypeRescueGene generated by hbm2java
 */
public class WildTypeRescueGene implements java.io.Serializable {

	private WildTypeRescueGeneId id;

	public WildTypeRescueGene() {
	}

	public WildTypeRescueGene(WildTypeRescueGeneId id) {
		this.id = id;
	}

	public WildTypeRescueGeneId getId() {
		return this.id;
	}

	public void setId(WildTypeRescueGeneId id) {
		this.id = id;
	}

}
