package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * XElementCombinatorialRepeat generated by hbm2java
 */
public class XElementCombinatorialRepeat implements java.io.Serializable {

	private XElementCombinatorialRepeatId id;

	public XElementCombinatorialRepeat() {
	}

	public XElementCombinatorialRepeat(XElementCombinatorialRepeatId id) {
		this.id = id;
	}

	public XElementCombinatorialRepeatId getId() {
		return this.id;
	}

	public void setId(XElementCombinatorialRepeatId id) {
		this.id = id;
	}

}
