package org.irri.iric.chado.so;

// Generated 05 26, 14 1:32:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Yac generated by hbm2java
 */
public class Yac implements java.io.Serializable {

	private YacId id;

	public Yac() {
	}

	public Yac(YacId id) {
		this.id = id;
	}

	public YacId getId() {
		return this.id;
	}

	public void setId(YacId id) {
		this.id = id;
	}

}
